<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'application-review-case-mgmt',
  'title' => 'Application Review & Case Management SOP',
  'category' => 'sops',
  'category_name' => 'Standard Operating Procedures',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Application Review & Case Management SOP',
    'document_type' => 'Standard Operating Procedure',
    'version' => '1.0',
    'last_updated' => '2026-09-07',
    'author' => 'ARCHR Development Team',
    'audience' => 'Admins, Caseworkers, Organizational Administrators',
    'complexity_level' => 'Intermediate',
    'estimated_reading_minutes' => '10',
    'tags' => 
    array (
      0 => 'case-management',
      1 => 'application-review',
      2 => 'assignment',
      3 => 'SOP',
    ),
    'visibility' => 'authenticated',
  ),
  'source' => 'sops\\application-review-case-mgmt.md',
  'html' => '<h1>Application Review &amp; Case Management</h1>
<blockquote>
<p><strong>Who this is for:</strong> Caseworkers, Admins, and Organizational Administrators who review incoming applications and turn them into active cases.</p>
</blockquote>
<h2>Why This Matters</h2>
<p>This is where applications become cases. It\'s the bridge between "someone asked for help" and "we\'re actually helping them." Mess this up and you get bottlenecks, dropped applicants, and the kind of frustration that makes partners pull out of the coalition. Get it right and the whole system flows smoothly.</p>
<p><strong>If you didn\'t review it, it doesn\'t exist.</strong> Every application needs eyes on it before it becomes a case.</p>
<hr />
<h2>Step 1: Check the Pending Applications Queue</h2>
<p>Your dashboard should show you a list of unclaimed applications. These are submissions from applicants that haven\'t been picked up by any organization yet.</p>
<p><strong>What to look for:</strong></p>
<ul>
<li><strong>Submission date</strong> — older applications first (FIFO, unless urgency dictates otherwise)</li>
<li><strong>Urgency flags</strong> — "Unable to stay in home," "No potable water," "Open to elements" — these jump the queue</li>
<li><strong>Completeness</strong> — does the application have basic contact info, address, and household details?</li>
</ul>
<blockquote>
<p><strong>Tip:</strong> An incomplete application is still worth reviewing. Sometimes missing info just means the applicant didn\'t know what to enter. You can fill gaps during first contact.</p>
</blockquote>
<hr />
<h2>Step 2: Review Applicant Information</h2>
<p>Open the application and check for:</p>
<table>
<thead>
<tr>
<th>Item</th>
<th>Why It Matters</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Home address / Placecode</strong></td>
<td>Confirms they\'re in your service area</td>
</tr>
<tr>
<td><strong>Contact information</strong></td>
<td>Phone, email — at least one must be valid</td>
</tr>
<tr>
<td><strong>Home ownership</strong></td>
<td>Must own the property to qualify for most programs</td>
</tr>
<tr>
<td><strong>Household size &amp; income</strong></td>
<td>Determines eligibility tier</td>
</tr>
<tr>
<td><strong>Repair needs listed</strong></td>
<td>Tells you what kind of work they need</td>
</tr>
<tr>
<td><strong>Damage cause</strong></td>
<td>Hurricane Helene-related? Different funding paths apply</td>
</tr>
<tr>
<td><strong>Eligibility flags</strong></td>
<td>Green = likely eligible, Yellow = needs review, Red = potential disqualifier</td>
</tr>
</tbody>
</table>
<p><strong>Remember our philosophy:</strong> Assume eligibility until proven otherwise. The system flags issues for <em>human review</em> — it never auto-denies. A yellow or red flag means "look closer," not "reject."</p>
<hr />
<h2>Step 3: Eligibility Check</h2>
<p>The system runs automatic eligibility checks based on:</p>
<ul>
<li><strong>Geography</strong> — is the property in your service area?</li>
<li><strong>Income</strong> — does household income fall within program guidelines?</li>
<li><strong>Home ownership</strong> — does the applicant own the property?</li>
<li><strong>Damage cause</strong> — is the damage related to a covered event?</li>
</ul>
<p><strong>What the flags mean:</strong></p>
<table>
<thead>
<tr>
<th>Flag Color</th>
<th>Meaning</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr>
<td>🟢 Green</td>
<td>Meets standard criteria</td>
<td>Proceed normally</td>
</tr>
<tr>
<td>🟡 Yellow</td>
<td>Something needs review</td>
<td>Look at the flagged item, decide if it\'s a real issue</td>
</tr>
<tr>
<td>🔴 Red</td>
<td>Potential disqualifier</td>
<td>Review carefully — this needs a human decision with documented reasoning</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Important:</strong> A red flag does NOT mean auto-denial. It means a human needs to review the situation and check boxes explaining the decision. We don\'t let algorithms turn people away.</p>
</blockquote>
<hr />
<h2>Step 4: Claim the Application (Create a Case)</h2>
<p>Once you\'ve reviewed the application and decided your organization can help:</p>
<ol>
<li><strong>Click "Claim"</strong> on the application record</li>
<li><strong>Select the repair needs</strong> your organization will handle (you might not handle all of them)</li>
<li><strong>Add a claim note</strong> — something brief like "Roof assessment scheduled for 9/15"</li>
<li><strong>Confirm</strong></li>
</ol>
<p><strong>What happens next:</strong></p>
<ul>
<li>A <strong>Case</strong> is created, linked to the original Application</li>
<li>The <strong>90-day progress clock</strong> starts — you now have 90 days to show progress, or the claim expires and another org can pick it up</li>
<li>The application status updates to show it\'s been claimed</li>
<li>Other organizations can see that these repair needs are taken (but can still claim unclaimed needs)</li>
</ul>
<blockquote>
<p><strong>The 90-day rule exists for a reason.</strong> It prevents applications from sitting in limbo. Any progress event — a task, a communication, a document upload — resets the clock. So keep the case moving.</p>
</blockquote>
<hr />
<h2>Step 5: Set Initial Case Status and Assign Staff</h2>
<p>After claiming:</p>
<ol>
<li><strong>Set the case status</strong> — typically starts at "New" or "Intake Review"</li>
<li><strong>Assign a caseworker</strong> — the primary point of contact for this household</li>
<li><strong>Log the first progress event</strong> — "Case claimed by [Org], assigned to [Caseworker]"</li>
</ol>
<p><strong>Best practice:</strong> Make first contact within 48 hours of claiming. Applicants who submit and then hear nothing get anxious, and anxious applicants call other organizations, which creates duplicate work and confusion.</p>
<hr />
<h2>Step 6: When to Accept vs. Pass on an Application</h2>
<p><strong>Accept when:</strong></p>
<ul>
<li>The repair need matches your organization\'s capabilities</li>
<li>You have capacity to handle it in a reasonable timeframe</li>
<li>The applicant is in your service area</li>
</ul>
<p><strong>Pass (don\'t claim) when:</strong></p>
<ul>
<li>The repair need is outside your scope (e.g., you do roofs, they need electrical)</li>
<li>You\'re at capacity and can\'t start work within 90 days</li>
<li>The applicant is outside your geographic service area</li>
</ul>
<p><strong>If you pass, log why.</strong> A quick note like "Electrical repair outside our scope — referred to [Other Org]" helps the next organization that looks at this application.</p>
<hr />
<h2>Common Scenarios</h2>
<h3>Scenario 1: Two Organizations, One Application</h3>
<p>An application has roof damage AND plumbing damage. Habitat claims the roof. CHC claims the plumbing. Two cases, one application. This is normal and expected. The Application layer is shared; each Case has its own timeline and progress.</p>
<h3>Scenario 2: Application Has Been Claimed but Nothing Is Happening</h3>
<p>Check the 90-day clock. If no progress events have been logged, the claim may be about to expire. You can reach out to the claiming organization or wait for the claim to expire and then claim it yourself.</p>
<h3>Scenario 3: Applicant Submitted Twice</h3>
<p>The system deduplicates submissions into a single Application. If the same household submits multiple times (forgot to upload docs, changed their mind, etc.), all submissions roll into one Application record. Check the submission history to see the full picture.</p>
<hr />
<h2>Quick Reference</h2>
<table>
<thead>
<tr>
<th>Action</th>
<th>Where</th>
<th>Who</th>
</tr>
</thead>
<tbody>
<tr>
<td>View pending applications</td>
<td>Case Search / Dashboard</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td>Review eligibility flags</td>
<td>Application detail view</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td>Claim repair needs</td>
<td>Application detail → "Claim" button</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td>Assign caseworker</td>
<td>Case detail → Staff assignment</td>
<td>Admin</td>
</tr>
<tr>
<td>Set case status</td>
<td>Case detail → Status dropdown</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td>Log progress event</td>
<td>Any case action auto-logs; manual via "Log Event"</td>
<td>Everyone</td>
</tr>
</tbody>
</table>
<hr />
<p><strong>Remember:</strong> Every application is a person who needs help. The faster you review, the faster they get it.</p>',
);
