<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'archr101',
  'title' => 'ARCHR 101 - From Submission to Roof Repair',
  'category' => 'archr101',
  'category_name' => 'ARCHR 101',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'ARCHR 101 - From Submission to Roof Repair',
    'document_type' => 'Introduction',
    'version' => '1',
    'last_updated' => '2026-07-11',
    'author' => 'ARCHR Development Team',
    'excerpt' => 'An overview of how this system works, from repair application, to completed home repair.',
    'audience' => 'All Platform Users (Requestors, Volunteers, Crew, Assessors, Subcontractors, Caseworkers, Project Managers, Bursars, Admins)',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '5-7 minutes',
    'tags' => '',
  ),
  'source' => 'archr101\\archr101.md',
  'html' => '<p><em>Eileen and the Baileys are a fictional family based on <a href="https://www.youtube.com/watch?v=dijMKwZMU2Q">Chuck Schumer\'s imaginary friends, Joe and Eileen Bailey</a>, who were covered in a special on Last Week Tonight by John Oliver. Who our Home Repair Requestors are is private, protected, and privileged information, and we haven\'t bothered to ask anyone to let us feature their home repair story, yet.</em></p>
<hr />
<h2>Meet Eileen Bailey</h2>
<p>Eileen Bailey is a home-owner in Swannanoa. The Baileys have lived in Buncombe County for twenty-five years. Before Hurricane Helene, the Bailey household was a space of memories and event hosting for family holidays. While the Baileys never had a ton of money, they had everything else.</p>
<p>Then Hurricane Helene happened. Many of the Baileys\' neighbors\' homes were completely devastated beyond repair. The Bailey household had a tree fall on it. No one was hurt. But there was catastrophic damage to the living room. A tree literally fell through it! The rest of the house was undamaged, but the flooding and opening created by the impact made the home unlivable and unprotected from the elements.</p>
<p>Eileen heard about ARCHR\'s Home Repair Program and submitted an application. In the aftermath of the storm, there was no electricity, water, or internet—sometimes for weeks, some places for months. So after the first opportunity the Baileys had to escape and charge their phones, they returned to take pictures of the damage and begin their intake application with ARCHR.</p>
<p>ARCHR has been operating since 2021, and when the storm hit, we already had the intake and management infrastructure to start running. This is why we were successful: because a plan was already in place for when disaster hit.</p>
<p>The Baileys could complete their intake application piecewise, saving their progress along the way. They could work on the application offline and submit it once they could go to their local public library, which had Wi-Fi internet up and running. When they finished and submitted the intake, a partnership of non-profits and aid workers was ready to receive it and mobilize.</p>
<p>Upon submission, a series of events was triggered. Several organizations committed to doing home repairs were alerted. Each had different eligibility criteria for taking on the repair. Because the Baileys were at 80% of the Average Median Income, and because Joe Bailey, a disabled textile worker, resides there, they were eligible for repair assistance with Disability Works, a local agency specializing in families with disabled members. That agency agreed before a storm happened that they would mobilize resources, staff, and volunteers after a disaster, towards home repair assistance. A dozen other organizations signed onto this pact before a disaster hit.</p>
<hr />
<h2>1. The Big Picture: What This Platform Does</h2>
<p>ARCHR connects people who need home repairs with people who can do them. The platform handles case management, document storage, financial tracking, and communication.</p>
<p><strong>The full journey:</strong> application → eligibility → assessment → planning → work → completion</p>
<p><em>For Eileen, this meant she could focus on her family while the system coordinated the repair of her home.</em></p>
<hr />
<h2>2. The Six Phases of a Repair Project</h2>
<table>
<thead>
<tr>
<th>Phase</th>
<th>What Happens</th>
<th>In Eileen\'s Story</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Phase 0: Submission &amp; Pre-Screening</strong></td>
<td>Application submitted; initial checks run</td>
<td>Eileen completes intake at the library</td>
</tr>
<tr>
<td><strong>Phase 1: Intake</strong></td>
<td>Case created; assessor assigned; documents collected</td>
<td>ARCHR creates Eileen\'s case record</td>
</tr>
<tr>
<td><strong>Phase 2: Processing</strong></td>
<td>Assessment performed; scope defined; budget set</td>
<td>An assessor visits the Bailey home</td>
</tr>
<tr>
<td><strong>Phase 3: Planning</strong></td>
<td>Contract created; resources scheduled</td>
<td>Disability Works plans the repair</td>
</tr>
<tr>
<td><strong>Phase 4: Project Execution</strong></td>
<td>Work performed; progress tracked</td>
<td>Crew repairs the Bailey home</td>
</tr>
<tr>
<td><strong>Phase 5: Completion &amp; Report</strong></td>
<td>Final walkthrough; certificate signed; costs reconciled</td>
<td>Eileen signs off on the completed work</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Learn more:</strong> <a href="help.php?doc=eligibility">Who Qualifies? Eligibility Determination</a> | <a href="help.php?doc=metrics-math-money">Metrics, Math, and Money</a></p>
</blockquote>
<hr />
<h2>3. Who Uses This Platform? (The Roles)</h2>
<table>
<thead>
<tr>
<th>Role</th>
<th>What They Do</th>
<th>In Eileen\'s Story</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Requestor</strong></td>
<td>Homeowner applying for help</td>
<td>Eileen Bailey</td>
</tr>
<tr>
<td><strong>Assessor</strong></td>
<td>Inspects property, writes reports</td>
<td>Inspects the Bailey home</td>
</tr>
<tr>
<td><strong>Caseworker</strong></td>
<td>Primary contact, manages application</td>
<td>Guides Eileen through the process</td>
</tr>
<tr>
<td><strong>Project Manager</strong></td>
<td>Oversees entire repair</td>
<td>Coordinates the Bailey repair</td>
</tr>
<tr>
<td><strong>Crew Lead</strong></td>
<td>Runs the on-site work</td>
<td>Leads the team at the Bailey house</td>
</tr>
<tr>
<td><strong>Crew Member</strong></td>
<td>Does the hands-on repairs</td>
<td>Fixes the Bailey living room</td>
</tr>
<tr>
<td><strong>Subcontractor</strong></td>
<td>Specialist trades</td>
<td>Does electrical work at the Bailey home</td>
</tr>
<tr>
<td><strong>Volunteer</strong></td>
<td>Helps with work, logs hours</td>
<td>Helps at the Bailey house</td>
</tr>
<tr>
<td><strong>Bursar</strong></td>
<td>Manages money, invoices, reimbursements</td>
<td>Pays the Bailey repair costs</td>
</tr>
<tr>
<td><strong>Admin (Organization)</strong></td>
<td>Manages their organization\'s cases</td>
<td>Manages Disability Works\' caseload</td>
</tr>
<tr>
<td><strong>Envoy</strong></td>
<td>Strategic leadership, approvals, reporting</td>
<td>Approves the Bailey repair contract</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Learn more:</strong> <a href="help.php?doc=making-an-account">How Do I Make an Account?</a></p>
</blockquote>
<hr />
<h2>4. The Four Big Systems</h2>
<h3>Tasks, Logs &amp; Events</h3>
<p>Everything that happens gets logged. Every task, every communication, every event. If it happened, it\'s in the system.</p>
<p><em>When Eileen called to ask about her application timeline, that call was logged. When the assessor visited, that visit was logged. When the crew finished the roof, that completion was logged.</em></p>
<blockquote>
<p><strong>Learn more:</strong> <a href="tasks-logs-events.md">Tasks, Logs &amp; Events</a></p>
</blockquote>
<h3>Document Bucket</h3>
<p>All files are organized by case in a standardized folder structure. Every document has a consistent naming convention.</p>
<p><em>The Bailey\'s intake form, assessment photos, contract, and completion certificate are all stored in their case folder, organized and easy to find.</em></p>
<blockquote>
<p><strong>Learn more:</strong> <a href="document-storage.md">Document Storage &amp; Generation</a></p>
</blockquote>
<h3>Progress Tracker</h3>
<p>An immutable ledger of what happened, when, and by whom. Nothing is ever deleted or overwritten.</p>
<p><em>Every step of the Bailey\'s journey—from application to completion—is recorded forever.</em></p>
<h3>Quick Add</h3>
<p>One-click logging from the field. Click "+ Add Event," select the task type, enter date and notes, and save.</p>
<p><em>The crew lead marked "Roof Repair Complete" from their phone before they even left the Bailey property.</em></p>
<blockquote>
<p><strong>Learn more:</strong> <a href="quick-add-progress-tasks.md">Quick Add Progress Tasks</a></p>
</blockquote>
<hr />
<h2>5. Quick Add Explained</h2>
<p>Quick Add is designed for busy people in the field. You don\'t need to fill out a long form—just the essentials.</p>
<p><strong>How it works:</strong></p>
<ol>
<li>Click <strong>"+ Add Event"</strong> from any case</li>
<li>Select the <strong>task type</strong> (ASSESS, SCOPE, START, COMPLETE, PROGRESS)</li>
<li>Enter the <strong>date</strong> and any <strong>notes</strong></li>
<li>Upload <strong>photos or documents</strong> (optional)</li>
<li>Click <strong>Save</strong></li>
</ol>
<p><em>The assessor visited the Bailey home, took photos, and logged the assessment in under two minutes using Quick Add.</em></p>
<p><strong>What happens after you save:</strong></p>
<ul>
<li>The entry goes to the <strong>Unverified</strong> queue</li>
<li>A <strong>Task Rabbit</strong> reviews and approves it</li>
<li>Once approved, it counts toward metrics</li>
<li>All changes are permanent in the ledger</li>
</ul>
<hr />
<h2>6. What Happens After I Submit Something</h2>
<table>
<thead>
<tr>
<th>Step</th>
<th>What Happens</th>
<th>Who Does It</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>1. Quick Add</strong></td>
<td>User logs an event</td>
<td>Any user</td>
</tr>
<tr>
<td><strong>2. Unverified Queue</strong></td>
<td>Entry waits for review</td>
<td>System</td>
</tr>
<tr>
<td><strong>3. Task Rabbit Review</strong></td>
<td>Entry is standardized</td>
<td>Task Rabbit</td>
</tr>
<tr>
<td><strong>4. Approval</strong></td>
<td>Entry becomes official</td>
<td>Task Rabbit</td>
</tr>
<tr>
<td><strong>5. Metrics Update</strong></td>
<td>Counts are updated</td>
<td>System</td>
</tr>
<tr>
<td><strong>6. Ledger Entry</strong></td>
<td>Change is permanent</td>
<td>System</td>
</tr>
</tbody>
</table>
<p><em>Eileen\'s application went through this exact process. When she submitted it, it entered the queue. A caseworker reviewed it, confirmed eligibility, and moved it forward. Every step was recorded in the ledger.</em></p>
<blockquote>
<p><strong>Learn more:</strong> <a href="help.php?doc=system-anatomy">Anatomy of a Home Repair Platform</a> | <a href="help.php?doc=schema-mapping">Schema Mapping and Database</a></p>
</blockquote>
<hr />
<h2>7. Where to Go Next</h2>
<h3>For Applicants / Requestors</h3>
<ul>
<li><a href="help.php?doc=intake-privacy">What Information Do I Need to Provide in an Intake?</a> - Privacy, data protection, what we ask for and why</li>
<li><a href="help.php?doc=eligibility">Who Qualifies? Eligibility Determination</a> - Understanding if you qualify</li>
</ul>
<h3>For Volunteers</h3>
<ul>
<li><a href="help.php?doc=making-an-account">How Do I Make an Account?</a> - Getting started as a volunteer</li>
<li><a href="volunteer-guide.md">Volunteer Experience: Quests, Hours &amp; Reputation</a> - How volunteering works</li>
</ul>
<h3>For Staff &amp; Partners</h3>
<ul>
<li><a href="help.php?doc=system-anatomy">Anatomy of a Home Repair Platform</a> - How it all works under the hood</li>
<li><a href="tasks-logs-events.md">Tasks, Logs &amp; Events</a> - The logging system</li>
<li><a href="document-storage.md">Document Storage &amp; Generation</a> - Managing case files</li>
</ul>
<h3>For Developers &amp; Technical Leads</h3>
<ul>
<li><a href="help.php?doc=platforms-code">Current Platforms and The Great Code Migration</a> - Migration from SaaS to custom code</li>
<li><a href="help.php?doc=schema-mapping">Schema Mapping and Database</a> - The database structure</li>
<li><a href="help.php?doc=open-source-home-repair">This Project is Open-Source</a> - How to deploy in your region</li>
</ul>
<hr />
<p><em>Eileen\'s home was repaired. The tree was removed. The living room was restored. And Eileen\'s family could finally return home. That\'s what this system makes possible—and now it can help people everywhere.</em></p>
<hr />
<h2>Quick Reference: Eileen\'s Journey Timeline</h2>
<table>
<thead>
<tr>
<th>Date</th>
<th>Event</th>
</tr>
</thead>
<tbody>
<tr>
<td>September 27, 2024</td>
<td>Hurricane Helene hits</td>
</tr>
<tr>
<td>October 3, 2024</td>
<td>Eileen submits intake application at library</td>
</tr>
<tr>
<td>October 5, 2024</td>
<td>Case created, assessor assigned</td>
</tr>
<tr>
<td>October 12, 2024</td>
<td>Assessor visits Bailey home</td>
</tr>
<tr>
<td>October 18, 2024</td>
<td>Scope of work and budget approved</td>
</tr>
<tr>
<td>October 22, 2024</td>
<td>Contract signed</td>
</tr>
<tr>
<td>October 25, 2024</td>
<td>Work begins at Bailey home</td>
</tr>
<tr>
<td>November 15, 2024</td>
<td>Work completed; completion certificate signed</td>
</tr>
<tr>
<td>November 20, 2024</td>
<td>Costs reconciled; case closed</td>
</tr>
</tbody>
</table>',
);
