<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'archr-developer-roadmap-july-20-sept-21',
  'title' => 'ARCHR_DEVELOPMENT_ROADMAP_Q3_2026',
  'category' => 'platform-anatomy',
  'category_name' => 'Platform Anatomy',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'ARCHR_DEVELOPMENT_ROADMAP_Q3_2026',
    'document_type' => 'Project Roadmap',
    'version' => '1.0',
    'last_updated' => '2026-07-18',
    'author' => 'ARCHR Development Team',
    'audience' => 'Leadership, Development Team, Stakeholders',
    'status' => 'For Review',
    'timeline' => 'July - September 2026',
  ),
  'source' => 'platform-anatomy\\ARCHR Developer Roadmap July 20-Sept 21.md',
  'html' => '<h2>Executive Summary</h2>
<p>The ARCHR platform requires significant foundational work to transition from a prototype to a reliable, production-ready system. Over the next two months, we need to focus on five core areas:</p>
<table>
<thead>
<tr>
<th>Priority</th>
<th>Area</th>
<th>Status</th>
<th>Focus</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Critical</strong></td>
<td>Intake Form &amp; Submission</td>
<td>❌ Broken</td>
<td>Fix submission errors, add save/offline capability</td>
</tr>
<tr>
<td><strong>Critical</strong></td>
<td>Database Consolidation</td>
<td>⚠️ Split</td>
<td>Unify Airtable + PostgreSQL with dual-write</td>
</tr>
<tr>
<td><strong>Critical</strong></td>
<td>Requestor Account Creation</td>
<td>⚠️ Partial</td>
<td>Complete account generation, credentials, notifications</td>
</tr>
<tr>
<td><strong>High</strong></td>
<td>Role Consolidation</td>
<td>⚠️ Fragmented</td>
<td>Reduce to 4 permission levels, ensure fluidity</td>
</tr>
<tr>
<td><strong>High</strong></td>
<td>Eligibility Engine</td>
<td>⚠️ Static</td>
<td>Make dynamic, configurable by admins</td>
</tr>
<tr>
<td><strong>Medium</strong></td>
<td>Document Bucket</td>
<td>❌ Not Started</td>
<td>Create case directories via API or local server</td>
</tr>
<tr>
<td><strong>Medium</strong></td>
<td>Component Library</td>
<td>⚠️ Broken</td>
<td>Fix paths, organize components</td>
</tr>
<tr>
<td><strong>Medium</strong></td>
<td>Onboarding Portal</td>
<td>❌ Not Started</td>
<td>Self-service Super-Admin and org setup</td>
</tr>
<tr>
<td><strong>Ongoing</strong></td>
<td>Metrics &amp; Reporting</td>
<td>⚠️ In Progress</td>
<td>Refine accuracy, automate funder reports</td>
</tr>
<tr>
<td><strong>Ongoing</strong></td>
<td>Task Engine &amp; Progress Tracker</td>
<td>⚠️ Semi-functional</td>
<td>Complete audit trail, immutable ledger</td>
</tr>
</tbody>
</table>
<hr />
<h2>Phase 1: Critical Fixes (Weeks 1-3)</h2>
<h3>1.1 Intake Form Overhaul</h3>
<table>
<thead>
<tr>
<th>Task</th>
<th>Description</th>
<th>Owner</th>
<th>Urgency</th>
</tr>
</thead>
<tbody>
<tr>
<td>Fix submission error</td>
<td>Resolve "Submission Processing Failed" bug</td>
<td>Dev</td>
<td>🔴 Critical</td>
</tr>
<tr>
<td>Add save progress</td>
<td>Enable partial form saves, resume later</td>
<td>Dev</td>
<td>🔴 Critical</td>
</tr>
<tr>
<td>Offline capability</td>
<td>Allow form loading and data entry without internet</td>
<td>Dev</td>
<td>🟡 High</td>
</tr>
<tr>
<td>Comma support</td>
<td>Accept numbers with commas (e.g., 50,000)</td>
<td>Dev</td>
<td>🟡 High</td>
</tr>
<tr>
<td>Priority labels</td>
<td>Replace numeric scale with descriptive options</td>
<td>UX</td>
<td>🟡 High</td>
</tr>
<tr>
<td>Improve question wording</td>
<td>Review awkward/confusing questions</td>
<td>UX</td>
<td>🟢 Medium</td>
</tr>
</tbody>
</table>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>
<p>Submission error rate: 0%</p>
</li>
<li>
<p>Form progress saved automatically every 30 seconds</p>
</li>
<li>
<p>Offline mode: form loads and caches entries</p>
</li>
<li>
<p>User testing: 100% of test users complete without confusion</p>
</li>
</ul>
<hr />
<h3>1.2 Submission Triggers &amp; Events</h3>
<p>When an application submits successfully, the following events must trigger:</p>
<table>
<thead>
<tr>
<th>Event</th>
<th>Description</th>
<th>Status</th>
<th>Owner</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Database Write</strong></td>
<td>Submit to BOTH Airtable AND PostgreSQL</td>
<td>⚠️ Partial</td>
<td>Dev</td>
</tr>
<tr>
<td><strong>Requestor Account</strong></td>
<td>Create low-permission account, show credentials</td>
<td>⚠️ Partial</td>
<td>Dev</td>
</tr>
<tr>
<td><strong>Confirmation Email</strong></td>
<td>Send to requestor with login link, form copy</td>
<td>❌ Not Started</td>
<td>Dev</td>
</tr>
<tr>
<td><strong>Admin Alert</strong></td>
<td>Email + platform notification to admins</td>
<td>❌ Not Started</td>
<td>Dev</td>
</tr>
<tr>
<td><strong>Alert Opt-Out</strong></td>
<td>Profile setting: "Do not send alerts"</td>
<td>❌ Not Started</td>
<td>Dev</td>
</tr>
<tr>
<td><strong>Recent Queue</strong></td>
<td>Add submission to queue for admin review</td>
<td>⚠️ Partial</td>
<td>Dev</td>
</tr>
<tr>
<td><strong>Eligibility Check</strong></td>
<td>Run automatic eligibility checks</td>
<td>⚠️ Partial</td>
<td>Dev</td>
</tr>
<tr>
<td><strong>Case Directory</strong></td>
<td>Create folder in Document Bucket</td>
<td>❌ Not Started</td>
<td>Dev</td>
</tr>
</tbody>
</table>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>
<p>All 8 events trigger on every submission</p>
</li>
<li>
<p>Dual-database writes succeed with rollback on failure</p>
</li>
<li>
<p>Email delivery rate: &gt;95%</p>
</li>
</ul>
<hr />
<h2>Phase 2: Database &amp; Account Consolidation (Weeks 3-5)</h2>
<h3>2.1 Dual-Database Architecture</h3>
<p><img src="help-content/assets/pasted-image-20260718095110-9b8b5a51.png" alt="Pasted image 20260718095110" /></p>
<p><strong>Requirements:</strong></p>
<table>
<thead>
<tr>
<th>Requirement</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Dual-Write</strong></td>
<td>Every submission writes to both databases</td>
</tr>
<tr>
<td><strong>Toggle Method</strong></td>
<td>Easy switch between Airtable and PostgreSQL</td>
</tr>
<tr>
<td><strong>Developer Friendly</strong></td>
<td>Clean abstraction, easily removable if consolidated</td>
</tr>
<tr>
<td><strong>Error Handling</strong></td>
<td>If one fails, log error but continue with the other</td>
</tr>
<tr>
<td><strong>Migration Path</strong></td>
<td>Clear path to deprecate one database when ready</td>
</tr>
</tbody>
</table>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>100% of submissions write to both databases</li>
<li>Toggle switches between databases without code changes</li>
<li>Abstraction layer: &lt; 100 lines of PHP</li>
</ul>
<h3>2.2 Role Consolidation (4 Permission Levels)</h3>
<table>
<thead>
<tr>
<th>Level</th>
<th>Name</th>
<th>Roles Included</th>
<th>Access Level</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>1</strong></td>
<td><strong>Field Worker</strong></td>
<td>Volunteer, Requestor, Crew Member</td>
<td>View own data, log hours, complete tasks</td>
</tr>
<tr>
<td><strong>2</strong></td>
<td><strong>Office Worker</strong></td>
<td>Caseworker, Assessor, Subcontractor</td>
<td>Create/edit data, log all actions, no destructive changes</td>
</tr>
<tr>
<td><strong>3</strong></td>
<td><strong>Organization Admin</strong></td>
<td>Admin, Project Manager, Bursar, Crew Lead</td>
<td>Full org control, manage staff, all non-destructive</td>
</tr>
<tr>
<td><strong>4</strong></td>
<td><strong>Super-Admin</strong></td>
<td>System Administrator</td>
<td>Full system access, sandbox mode, all features</td>
</tr>
</tbody>
</table>
<p><strong>Key Changes:</strong></p>
<ul>
<li>Email digest option for Level 1 (don\'t need to log in)</li>
<li>All Level 2+ actions logged in immutable progress tracker</li>
<li>Level 3 can modify permissions for Level 1-2 users</li>
<li>Level 4 has sandbox mode for safe testing</li>
</ul>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>All roles mapped to one of 4 levels</li>
<li>Permission system refactored to support levels</li>
<li>All Level 2+ actions logged</li>
<li>Email digest working for Level 1</li>
</ul>
<hr />
<h2>Phase 3: Core Systems (Weeks 5-7)</h2>
<h3>3.1 Eligibility Engine</h3>
<p><strong>Current State:</strong> Static rules, manually coded<br />
<strong>Target State:</strong> Dynamic, configurable by Organization Admins and Super-Admins</p>
<table>
<thead>
<tr>
<th>Feature</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Income Threshold</strong></td>
<td>Configurable AMI percentage (e.g., 80%, 100%, 120%)</td>
</tr>
<tr>
<td><strong>Geographic Area</strong></td>
<td>ZIP code lists, county selection</td>
</tr>
<tr>
<td><strong>Demographics</strong></td>
<td>Toggle specific population groups</td>
</tr>
<tr>
<td><strong>Damage Type</strong></td>
<td>Helene-related vs. other vs. both</td>
</tr>
<tr>
<td><strong>Funding Source</strong></td>
<td>Link eligibility rules to specific grants</td>
</tr>
<tr>
<td><strong>Default Settings</strong></td>
<td>"Assume eligibility until proven otherwise"</td>
</tr>
</tbody>
</table>
<p><strong>Admin Configuration UI:</strong></p>
<ul>
<li>Profile Settings → Eligibility Rules</li>
<li>Toggle on/off for each criterion</li>
<li>Set custom values (income %, service area)</li>
<li>Preview how many applicants would qualify</li>
</ul>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>Admins can modify rules without code changes</li>
<li>Rules apply to new applications in real-time</li>
<li>Ineligible applications logged with reason codes</li>
</ul>
<hr />
<h3>3.2 Document Bucket (Case Directory Creation)</h3>
<p><strong>Current State:</strong> Document spaces exist, but no platform-specific bucket<br />
<strong>Target State:</strong> API-connected or local server for document storage</p>
<p><strong>Options:</strong></p>
<table>
<thead>
<tr>
<th>Option</th>
<th>Pros</th>
<th>Cons</th>
<th>Recommendation</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Dropbox API</strong></td>
<td>Reliable, managed, easy integration</td>
<td>Monthly cost, dependency</td>
<td>✅ Primary option</td>
</tr>
<tr>
<td><strong>Local Server</strong></td>
<td>Free, full control</td>
<td>Maintenance, security risk, no backup</td>
<td>❌ Not recommended</td>
</tr>
<tr>
<td><strong>AWS S3</strong></td>
<td>Enterprise-grade, scalable</td>
<td>Cost, setup complexity</td>
<td>⚠️ Future option</td>
</tr>
</tbody>
</table>
<p><strong>Folder Structure (from document-storage.md):</strong></p>
<pre><code>/organizations/
└── /{org_id}/
    └── /cases/
        └── /{case_number}/
            ├── /application/
            ├── /property/
            ├── /income/
            ├── /assessments/
            ├── /contracts/
            ├── /work_orders/
            ├── /financial/
            ├── /completion/
            └── /communications/</code></pre>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>Case directory created on application submission</li>
<li>Standardized folder structure in place</li>
<li>File naming convention implemented</li>
<li>Basic CRUD operations via API<h3>3.3 Component Library Fix</h3>
</li>
</ul>
<p><strong>Current State:</strong> <code>component-library.php</code> is broken, components not loading<br />
<strong>Target State:</strong> Working component registry with path constants</p>
<p><strong>Implementation Plan:</strong></p>
<p>php</p>
<pre><code>&lt;?php
// config/paths.php
define(\'COMPONENTS_PATH\', __DIR__ . \'/../elemental-integration/components/\');
// component-library.php
function load_component($component_name) {
    $path = COMPONENTS_PATH . $component_name . \'.json\';
    if (file_exists($path)) {
        return json_decode(file_get_contents($path), true);
    }
    return null;
}
</code></pre>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>All components load correctly</li>
<li>Path constant set and documented</li>
<li>Component listing page works</li>
</ul>
<hr />
<h2>Phase 4: Onboarding &amp; Support (Weeks 7-8)</h2>
<h3>4.1 Onboarding Portal</h3>
<p><strong>Purpose:</strong> Self-service setup for new ARCHR instances</p>
<p><strong>Workflow:</strong>
<img src="help-content/assets/pasted-image-20260718094827-1ded0aa3.png" alt="Pasted image 20260718094827" /></p>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>Installation script runs successfully</li>
<li>Super-Admin created without manual database edits</li>
<li>Organizations can be added via UI</li>
<li>2-way sync with Airtable + PostgreSQL</li>
</ul>
<hr />
<h3>4.2 Super-Admin Dashboard</h3>
<p><strong>Components:</strong></p>
<ul>
<li>System health monitor (uptime, errors, response time)</li>
<li>Organization overview (all orgs with key metrics)</li>
<li>User management (add, deactivate, impersonate)</li>
<li>Onboarding queue (pending orgs, setups)</li>
<li>Audit log (system-wide changes)</li>
<li>Sandbox mode toggle</li>
</ul>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>Dashboard fully functional</li>
<li>Sandbox mode prevents production data changes</li>
<li>Audit log captures all Super-Admin actions</li>
</ul>
<h2>Phase 5: Ongoing Work (Parallel)</h2>
<h3>5.1 Metrics &amp; Reporting</h3>
<table>
<thead>
<tr>
<th>Metric Group</th>
<th>Status</th>
<th>Focus</th>
</tr>
</thead>
<tbody>
<tr>
<td>Past Week Metrics</td>
<td>⚠️ Partial</td>
<td>Ensure accuracy, automate calculations</td>
</tr>
<tr>
<td>All Time Metrics</td>
<td>⚠️ Partial</td>
<td>Complete all 16 metrics</td>
</tr>
<tr>
<td>Organization Specific</td>
<td>⚠️ Partial</td>
<td>Per-org metrics</td>
</tr>
<tr>
<td>Funder Reports</td>
<td>❌ Not Started</td>
<td>Monthly report generation</td>
</tr>
</tbody>
</table>
<p><strong>Priority Metrics:</strong></p>
<ol>
<li>Total Applications (weekly/all-time)</li>
<li>Average Triage Score</li>
<li>Total Jobs / In Progress / Completed</li>
<li>Average Job Cost</li>
<li>Funding by Source</li>
<li>Income Breakdown</li>
<li>County Breakdown</li>
</ol>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>All metrics displayed on dashboards</li>
<li>Monthly funder reports generated automatically</li>
<li>3-level confidence interval tracked<h3>5.2 Task Engine &amp; Progress Tracker</h3>
</li>
</ul>
<table>
<thead>
<tr>
<th>Component</th>
<th>Status</th>
<th>Focus</th>
</tr>
</thead>
<tbody>
<tr>
<td>Quick Add Form</td>
<td>⚠️ In Progress</td>
<td>Complete MVP</td>
</tr>
<tr>
<td>Immutable Ledger</td>
<td>⚠️ In Progress</td>
<td>All actions logged</td>
</tr>
<tr>
<td>Task Definitions</td>
<td>⚠️ Partial</td>
<td>Complete all 74 tasks</td>
</tr>
<tr>
<td>Workflow Phases</td>
<td>✅ Complete</td>
<td>6 phases mapped</td>
</tr>
<tr>
<td>Notifications</td>
<td>❌ Not Started</td>
<td>Email + platform alerts</td>
</tr>
</tbody>
</table>
<p><strong>Success Criteria:</strong></p>
<ul>
<li>All 6 phases have complete task lists</li>
<li>Progress tracker logs every action</li>
<li>Quick Add works from any dashboard</li>
<li>Notifications working for all major events</li>
</ul>
<p>Week 1-2:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  Intake Form Fix + Submission Events
Week 3-4:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  Database Consolidation + Roles
Week 5-6:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  Eligibility Engine + Doc Bucket
Week 7-8:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  Onboarding + Super-Admin
━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Critical Fixes  │  Core Systems  │  Onboarding  │  Ongoing Metrics</p>
<h2>Task Priority Matrix</h2>
<table>
<thead>
<tr>
<th>Task</th>
<th>Urgency</th>
<th>Complexity</th>
<th>Impact</th>
<th>Priority</th>
</tr>
</thead>
<tbody>
<tr>
<td>Fix submission error</td>
<td>🔴 Critical</td>
<td>🟡 Medium</td>
<td>🔴 High</td>
<td><strong>P0</strong></td>
</tr>
<tr>
<td>Add save progress</td>
<td>🔴 Critical</td>
<td>🟢 Low</td>
<td>🔴 High</td>
<td><strong>P0</strong></td>
</tr>
<tr>
<td>Dual-database writes</td>
<td>🔴 Critical</td>
<td>🟡 Medium</td>
<td>🔴 High</td>
<td><strong>P0</strong></td>
</tr>
<tr>
<td>Requestor account creation</td>
<td>🔴 Critical</td>
<td>🟢 Low</td>
<td>🔴 High</td>
<td><strong>P0</strong></td>
</tr>
<tr>
<td>Role consolidation</td>
<td>🟡 High</td>
<td>🟡 Medium</td>
<td>🟡 Medium</td>
<td><strong>P1</strong></td>
</tr>
<tr>
<td>Eligibility engine (dynamic)</td>
<td>🟡 High</td>
<td>🔴 High</td>
<td>🟡 Medium</td>
<td><strong>P1</strong></td>
</tr>
<tr>
<td>Document Bucket</td>
<td>🟡 High</td>
<td>🔴 High</td>
<td>🟡 Medium</td>
<td><strong>P1</strong></td>
</tr>
<tr>
<td>Offline capability</td>
<td>🟡 High</td>
<td>🔴 High</td>
<td>🟢 Low</td>
<td><strong>P2</strong></td>
</tr>
<tr>
<td>Component library fix</td>
<td>🟢 Medium</td>
<td>🟢 Low</td>
<td>🟢 Low</td>
<td><strong>P2</strong></td>
</tr>
<tr>
<td>Onboarding portal</td>
<td>🟢 Medium</td>
<td>🔴 High</td>
<td>🟢 Low</td>
<td><strong>P2</strong></td>
</tr>
<tr>
<td>Comma support in intake</td>
<td>🟢 Low</td>
<td>🟢 Low</td>
<td>🟢 Low</td>
<td><strong>P3</strong></td>
</tr>
<tr>
<td>Priority labels</td>
<td>🟢 Low</td>
<td>🟢 Low</td>
<td>🟢 Low</td>
<td><strong>P3</strong></td>
</tr>
</tbody>
</table>
<h2>Success Metrics</h2>
<h3>By End of Q3 2026</h3>
<ul>
<li>Intake submission success rate: 99.9%</li>
<li>Dual-database writes: 100% success</li>
<li>Requestor accounts: 100% of applicants have option</li>
<li>Admin alerts: All sent within 60 seconds</li>
<li>Eligibility rules: 100% configurable via UI</li>
<li>Document Bucket: Case folders created automatically</li>
<li>Components: All loading correctly</li>
<li>Super-Admin: Dashboard functional</li>
<li>Metrics: All tracked accurately<h3>Quality Indicators</h3>
</li>
</ul>
<table>
<thead>
<tr>
<th>Metric</th>
<th>Target</th>
</tr>
</thead>
<tbody>
<tr>
<td>User error reports</td>
<td>&lt; 5 per week</td>
</tr>
<tr>
<td>Submission failure rate</td>
<td>&lt; 0.1%</td>
</tr>
<tr>
<td>Email delivery rate</td>
<td>&gt; 99%</td>
</tr>
<tr>
<td>Admin satisfaction</td>
<td>&gt; 4/5</td>
</tr>
</tbody>
</table>
<h2>Next Steps</h2>
<ol>
<li><strong>Review this roadmap</strong> with your boss</li>
<li><strong>Confirm priorities</strong> - adjust P0/P1/P2 based on business needs</li>
<li><strong>Assign owners</strong> to each workstream</li>
<li><strong>Create detailed tasks</strong> in project management tool</li>
<li><strong>Schedule weekly check-ins</strong> to track progress</li>
</ol>
<p><img src="help-content/assets/pasted-image-20260718094516-6bb6e292.png" alt="Pasted image 20260718094516" /></p>',
);
