<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'baseid-airtable-guide',
  'title' => 'Airtable Base IDs Quick Reference',
  'category' => 'platform-anatomy',
  'category_name' => 'Platform Anatomy',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Airtable Base IDs Quick Reference',
    'document_type' => 'Technical Reference',
    'version' => '1.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'Developers, Admins',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '2',
    'tags' => 
    array (
      0 => 'airtable',
      1 => 'base-id',
      2 => 'reference',
    ),
  ),
  'source' => 'platform-anatomy\\baseID-airtable-guide.md',
  'html' => '<p>These are the core bases in Airtable and the BaseIDs. </p>
<ul>
<li>The format of these are \'app\' and then 14 random characters.</li>
<li>TableIDs are \'tbl\' and then 14 random characters.</li>
<li>Records are \'rec\' and then 14 random chracters.</li>
<li>Field IDs are \'fld\' and 14 random characters.</li>
</ul>
<p>This is the basic structure on how to format an API call. You can get to <em>any</em> record from appID/tableID/recordID through airtable.com/</p>
<p>🟦[D] ARCHR Project Documents    appjB8RyRb8VryrTd
🟦<a href="v1-2">D</a> ANCHOR Records   appWAmMNCsnsAgyTW
🟦[D] (v2) ARCHR Directory   appfCMatXfknvXNkc
🟦[D] ARCHR Multi Axis Task Library  appfhuefuekoCvL3J
🟦(📗) Fillout Results    appdJHg317xbe3Sd4
🟦[P] ARCHR Eligibility  appIFBi7Rln8yFhCs
🟦[P] ARCHR Progress Tracker appjHNCJFj14C30X3
🟦ARCHR Partner Programs appAmaLnsO0BTkKAk
🟦[D] ARCHR Repair Requests  appBq2Z1a9dssVVbL</p>
<p>Example URL: <a href="https://airtable.com/appjB8RyRb8VryrTd/tblqsqy5c8nOSKWCV/viwn7LNBcHbGBJ7Wa/fldVrqd4lf1ZHeLIV">https://airtable.com/appjB8RyRb8VryrTd/tblqsqy5c8nOSKWCV/viwn7LNBcHbGBJ7Wa/fldVrqd4lf1ZHeLIV</a>
Dissected: <a href="https://airtable.com/{baseID}/{tableID}/{viewID}/{fieldID/recordID">https://airtable.com/{baseID}/{tableID}/{viewID}/{fieldID/recordID</a>}</p>
<p>Big Four Tables on Airtable:</p>
<ul>
<li>ANCHOR</li>
<li>Progress Track Ledger</li>
<li>Fillout Result</li>
<li>ARCHR Eligibility</li>
</ul>',
);
