<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'branding-guide',
  'title' => 'ARCHR Brand & Interface Guide',
  'category' => 'platform-anatomy',
  'category_name' => 'Platform Anatomy',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'ARCHR Brand & Interface Guide',
    'document_type' => 'Style Guide',
    'version' => '1.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'All Platform Users, Developers',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '10',
    'tags' => 
    array (
      0 => 'branding',
      1 => 'design',
      2 => 'style-guide',
      3 => 'visual-identity',
    ),
  ),
  'source' => 'platform-anatomy\\branding-guide.md',
  'html' => '<h1>ARCHR Brand &amp; Interface Guide</h1>
<p><em>System Standards and Visual Logic for Disaster Recovery</em></p>
<blockquote>
<p><strong>About this guide.</strong> This document is the single source of truth for ARCHR\'s visual identity and front-end conventions. Every color, size, spacing value, and component pattern described here is implemented as a CSS custom property in <code>css/style.css</code> (the <code>:root</code> block). When the guide and the code disagree, fix one to match the other — don\'t let them drift. New pages should consume these tokens rather than hard-coding values.</p>
</blockquote>
<hr />
<h2>1. Our Purpose</h2>
<ul>
<li><strong>The Mission:</strong> Providing urgent, free, or low-cost home repairs for residents in Buncombe and Madison counties affected by Hurricane Helene.</li>
<li><strong>The Problem:</strong> Streamlining repairs for low-income, uninsured, or underinsured homeowners.</li>
<li><strong>The Solution:</strong> A centralized online database (the "Marketplace") and a joint application process.</li>
<li><strong>The Branding Goal:</strong> Ensure visual consistency across the digital "Marketplace" so subcontractors and volunteers can navigate the system efficiently.</li>
</ul>
<hr />
<h2>2. Logo Specifications</h2>
<ul>
<li><strong>The Rotation Rule:</strong> The primary arrow is set to exactly <strong>31.38°</strong>. This angle must be preserved across all digital and print recreations to maintain the "upward recovery" trajectory.</li>
<li><strong>Primary Background:</strong> Always prioritize placing the logo on <strong>Canvas Cream <code>#FFFAE7</code></strong> (exposed as <code>--color-canvas-cream</code> and used as the light-theme page background, so the logo always sits on its intended canvas).</li>
<li><strong>Usage rules:</strong><ul>
<li><em>Full Banner</em> — Mandatory for public intake forms and external documents.</li>
<li><em>Icon-Only</em> — Reserved for internal Marketplace dashboards where space is at a premium.</li>
</ul>
</li>
</ul>
<blockquote>
<p><strong>Planned work:</strong> A code-based (SVG / CSS) recreation of the logotype is being explored so the lockup can be themed (light/dark) and resolution-independent without shipping a raster.</p>
</blockquote>
<h2>3. Color System</h2>
<h3>3a. Brand Colors</h3>
<table>
<thead>
<tr>
<th>Token</th>
<th>Value</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>--color-primary</code></td>
<td><code>#E04E39</code></td>
<td>Primary actions, logo lockup color, KPI accents, active-tab marker</td>
</tr>
<tr>
<td><code>--color-primary-dark</code></td>
<td><code>#C23A26</code></td>
<td>Hover state for primary buttons</td>
</tr>
<tr>
<td><code>--color-secondary</code></td>
<td><code>#2A5C82</code></td>
<td>Section accents, secondary actions, info callouts, dashboard hero</td>
</tr>
<tr>
<td><code>--color-canvas-cream</code></td>
<td><code>#FFFAE7</code></td>
<td>Light-theme page background (<code>--bg-page</code>) and the canvas behind the logo</td>
</tr>
</tbody>
</table>
<h3>3b. Role Identity System</h3>
<p>The ARCHR system uses color to create unique "Visual Workspaces." Each role is defined by a primary <strong>Action Color</strong> (and, in roadmapped UI, a corresponding Soft Background Tint) to improve navigation and task focus.</p>
<p>The ARCHR ecosystem uses a tiered access model categorized into roles grouped as:</p>
<ul>
<li><strong>Administrative &amp; Oversight</strong> — Admin, Envoy, Project Manager, Bursar</li>
<li><strong>Field &amp; Technical Operations</strong> — Assessor, Crew Lead, Crew Member, Subcontractor</li>
<li><strong>Client &amp; Support Services</strong> — Requestor, Caseworker, Volunteer</li>
<li><strong>System Entry</strong> — the neutral "Select Role" gateway</li>
</ul>
<table>
<thead>
<tr>
<th>Role</th>
<th>Hex</th>
<th>CSS Token</th>
</tr>
</thead>
<tbody>
<tr>
<td>Requestor</td>
<td><code>#FF7979</code></td>
<td><code>--role-requestor</code></td>
</tr>
<tr>
<td>Caseworker</td>
<td><code>#FF7979</code></td>
<td><code>--role-caseworker</code></td>
</tr>
<tr>
<td>Assessor</td>
<td><code>#219BA4</code></td>
<td><code>--role-assessor</code></td>
</tr>
<tr>
<td>Subcontractor</td>
<td><code>#AA6709</code></td>
<td><code>--role-subcontractor</code></td>
</tr>
<tr>
<td>Envoy</td>
<td><code>#FFCC00</code></td>
<td><code>--role-envoy</code></td>
</tr>
<tr>
<td>Project Manager</td>
<td><code>#3366CC</code></td>
<td><code>--role-project-manager</code></td>
</tr>
<tr>
<td>Crew Lead</td>
<td><code>#FF6600</code></td>
<td><code>--role-crew-lead</code></td>
</tr>
<tr>
<td>Crew Member</td>
<td><code>#FF9900</code></td>
<td><code>--role-crew-member</code></td>
</tr>
<tr>
<td>Bursar</td>
<td><code>#00CC00</code></td>
<td><code>--role-bursar</code></td>
</tr>
<tr>
<td>Volunteer</td>
<td><code>#A3C2FF</code></td>
<td><code>--role-volunteer</code></td>
</tr>
<tr>
<td>Admin</td>
<td><code>#5415B1</code></td>
<td><code>--role-admin</code></td>
</tr>
</tbody>
</table>
<p><strong>The Action Color System.</strong> Each role is assigned a unique primary color for interactive elements like headers, buttons, and iconography. This provides an immediate visual cue of the user\'s current permissions, allowing multi-role users to identify their active workstation at a glance.</p>
<p><strong>Role bg/text token pairs.</strong> For chips, badges, and role-tinted surfaces, use the <code>--role-&lt;name&gt;-bg</code> / <code>--role-&lt;name&gt;-text</code> pairs rather than the raw <code>--role-&lt;name&gt;</code> accent. In light mode the bg is the saturated action color above with white or black text chosen for AA contrast; in dark mode the bg flips to a soft pastel tint with black text so role chips remain legible against dark surfaces.</p>
<table>
<thead>
<tr>
<th>Role</th>
<th>Light bg / text</th>
<th>Dark bg / text</th>
</tr>
</thead>
<tbody>
<tr>
<td>Requestor</td>
<td><code>#FF7979</code> / <code>#ffffff</code></td>
<td><code>#fbd0da</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Caseworker</td>
<td><code>#FF7979</code> / <code>#ffffff</code></td>
<td><code>#fbd0da</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Assessor</td>
<td><code>#219BA4</code> / <code>#ffffff</code></td>
<td><code>#d9f0f2</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Subcontractor</td>
<td><code>#AA6709</code> / <code>#ffffff</code></td>
<td><code>#fbe9d0</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Envoy</td>
<td><code>#FFCC00</code> / <code>#000000</code></td>
<td><code>#fff1b8</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Project Manager</td>
<td><code>#3366CC</code> / <code>#ffffff</code></td>
<td><code>#d0defb</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Crew Lead</td>
<td><code>#FF6600</code> / <code>#ffffff</code></td>
<td><code>#fbe2d0</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Crew Member</td>
<td><code>#FF9900</code> / <code>#000000</code></td>
<td><code>#fbe8d0</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Bursar</td>
<td><code>#00CC00</code> / <code>#000000</code></td>
<td><code>#d9f2d9</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Volunteer</td>
<td><code>#A3C2FF</code> / <code>#000000</code></td>
<td><code>#d0f9fb</code> / <code>#000000</code></td>
</tr>
<tr>
<td>Admin</td>
<td><code>#5415B1</code> / <code>#ffffff</code></td>
<td><code>#e3d9f2</code> / <code>#000000</code></td>
</tr>
</tbody>
</table>
<h3>3c. Project Lifecycle &amp; Phase Pills</h3>
<p>The repair process is divided into six distinct stages. Each stage is represented by a standardized Phase Pill that provides immediate visual status for homeowners, contractors, and administrators.</p>
<table>
<thead>
<tr>
<th>Phase</th>
<th>Name</th>
<th>Hex</th>
<th>CSS Token</th>
</tr>
</thead>
<tbody>
<tr>
<td>0</td>
<td>Select Project</td>
<td><code>#0E232E</code></td>
<td><code>--phase-0-select</code></td>
</tr>
<tr>
<td>1</td>
<td>Intake</td>
<td><code>#5C6D70</code></td>
<td><code>--phase-1-intake</code></td>
</tr>
<tr>
<td>2</td>
<td>Review</td>
<td><code>#A1683A</code></td>
<td><code>--phase-2-review</code></td>
</tr>
<tr>
<td>3</td>
<td>Assign</td>
<td><code>#D4A373</code></td>
<td><code>--phase-3-assign</code></td>
</tr>
<tr>
<td>4</td>
<td>Site Work</td>
<td><code>#1B1B1B</code></td>
<td><code>--phase-4-site-work</code></td>
</tr>
<tr>
<td>5</td>
<td>Complete</td>
<td><code>#00CC66</code></td>
<td><code>--phase-5-complete</code></td>
</tr>
</tbody>
</table>
<h3>3d. Semantic Colors</h3>
<table>
<thead>
<tr>
<th>Token</th>
<th>Value</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>--color-success</code></td>
<td><code>#2f9e69</code></td>
<td>Positive deltas, completion states, KPI "completed"</td>
</tr>
<tr>
<td><code>--color-warning</code></td>
<td><code>#d99518</code></td>
<td>Warnings, attention pills, in-progress KPIs</td>
</tr>
<tr>
<td><code>--color-danger</code></td>
<td><code>#c23a26</code></td>
<td>Errors, overdue, critical safety flags</td>
</tr>
<tr>
<td><code>--color-info</code></td>
<td><code>#1d4665</code></td>
<td>Informational callouts, neutral data emphasis</td>
</tr>
</tbody>
</table>
<h3>3e. Light &amp; Dark Theme Tokens</h3>
<p>The site supports a <strong>manual light/dark toggle</strong> that respects <code>prefers-color-scheme</code> on first visit and stores the user\'s choice in <code>localStorage</code>. The tokens below swap between themes; brand, role, phase, and semantic colors stay constant.</p>
<table>
<thead>
<tr>
<th>Token</th>
<th>Light</th>
<th>Dark</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>--bg-page</code></td>
<td><code>#FFFAE7</code> (canvas cream)</td>
<td><code>#1f1b1c</code></td>
</tr>
<tr>
<td><code>--bg-surface</code></td>
<td><code>#ffffff</code></td>
<td><code>#2a2526</code></td>
</tr>
<tr>
<td><code>--bg-surface-alt</code></td>
<td><code>#F8F9FA</code></td>
<td><code>#332d2e</code></td>
</tr>
<tr>
<td><code>--color-text</code></td>
<td><code>#333333</code></td>
<td><code>#fafafa</code></td>
</tr>
<tr>
<td><code>--color-text-muted</code></td>
<td><code>#6C757D</code></td>
<td><code>#b6acad</code></td>
</tr>
<tr>
<td><code>--color-border-strong</code></td>
<td><code>#DEE2E6</code></td>
<td><code>#4a4243</code></td>
</tr>
<tr>
<td><code>--color-header-bg</code></td>
<td><code>#ffffff</code></td>
<td><code>#3b3637</code></td>
</tr>
<tr>
<td><code>--color-header-text</code></td>
<td><code>#333333</code></td>
<td><code>#fafafa</code></td>
</tr>
<tr>
<td><code>--color-footer-bg</code></td>
<td><code>#333333</code></td>
<td><code>#1a1718</code></td>
</tr>
<tr>
<td><code>--color-footer-text</code></td>
<td><code>#ffffff</code></td>
<td><code>#fafafa</code></td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Legacy aliases.</strong> <code>--color-light</code>, <code>--color-dark</code>, <code>--color-gray</code>, and <code>--color-border</code> are kept as aliases of the semantic tokens above so existing rules theme automatically. New code should prefer the semantic names.</p>
</blockquote>
<hr />
<h2>4. Typography</h2>
<table>
<thead>
<tr>
<th>Token</th>
<th>Value</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>--font-display</code></td>
<td><code>\'Poppins\', system-ui, …</code></td>
<td>Headings (h1–h4), KPI values, large numerics</td>
</tr>
<tr>
<td><code>--font-sans</code></td>
<td><code>\'Open Sans\', system-ui, …</code></td>
<td>Body text</td>
</tr>
</tbody>
</table>
<p><strong>Type scale</strong> — use the variables, don\'t hard-code px or rem:</p>
<table>
<thead>
<tr>
<th>Token</th>
<th>Size</th>
<th>Suggested use</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>--fs-xs</code></td>
<td>0.75rem</td>
<td>Pill labels, micro-badges</td>
</tr>
<tr>
<td><code>--fs-sm</code></td>
<td>0.875rem</td>
<td>Meta text, footer notes, KPI sub-labels</td>
</tr>
<tr>
<td><code>--fs-base</code></td>
<td>1rem</td>
<td>Body</td>
</tr>
<tr>
<td><code>--fs-md</code></td>
<td>1.125rem</td>
<td>Sub-headings, chart-card <code>&lt;h4&gt;</code></td>
</tr>
<tr>
<td><code>--fs-lg</code></td>
<td>1.25rem</td>
<td>Lead paragraph</td>
</tr>
<tr>
<td><code>--fs-xl</code></td>
<td>1.5rem</td>
<td>Dashboard section titles</td>
</tr>
<tr>
<td><code>--fs-2xl</code></td>
<td>2rem</td>
<td>KPI values, dashboard <code>&lt;h2&gt;</code></td>
</tr>
<tr>
<td><code>--fs-3xl</code></td>
<td>2.5rem</td>
<td>Hero <code>&lt;h2&gt;</code></td>
</tr>
</tbody>
</table>
<p><strong>Line-heights</strong> — <code>--lh-tight</code> (<code>1.3</code>) for headings, <code>--lh-base</code> (<code>1.6</code>) for body.</p>
<hr />
<h2>5. Spacing Scale</h2>
<p>A 4px-based scale. Prefer these tokens for any new layout work; avoid arbitrary px values:</p>
<table>
<thead>
<tr>
<th>Token</th>
<th>px</th>
<th>Common use</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>--space-1</code></td>
<td>4px</td>
<td>Hairline gaps</td>
</tr>
<tr>
<td><code>--space-2</code></td>
<td>8px</td>
<td>Inline gaps (icon ↔ label)</td>
</tr>
<tr>
<td><code>--space-3</code></td>
<td>12px</td>
<td>Tight padding</td>
</tr>
<tr>
<td><code>--space-4</code></td>
<td>16px</td>
<td>Default padding/margin</td>
</tr>
<tr>
<td><code>--space-5</code></td>
<td>20px</td>
<td>Container gutter</td>
</tr>
<tr>
<td><code>--space-6</code></td>
<td>24px</td>
<td>Card padding, section gaps</td>
</tr>
<tr>
<td><code>--space-8</code></td>
<td>32px</td>
<td>Large vertical rhythm</td>
</tr>
<tr>
<td><code>--space-10</code></td>
<td>40px</td>
<td>Hero padding</td>
</tr>
<tr>
<td><code>--space-12</code></td>
<td>48px</td>
<td>Section breaks</td>
</tr>
</tbody>
</table>
<hr />
<h2>6. Geometry</h2>
<h3>6a. Border Radii — the 0.6rem Rule</h3>
<p>A uniform <code>0.6rem</code> corner radius is applied to every button, card, KPI tile, callout, phase pill, and interactive container. <strong>No sharp 90° corners are permitted on interactive components.</strong></p>
<table>
<thead>
<tr>
<th>Token</th>
<th>Value</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>--radius-sm</code></td>
<td>0.3rem</td>
<td>Inputs, small chips</td>
</tr>
<tr>
<td><code>--radius-md</code></td>
<td>0.6rem</td>
<td><strong>Default</strong> — buttons, cards, KPIs, callouts</td>
</tr>
<tr>
<td><code>--radius-lg</code></td>
<td>1rem</td>
<td>Hero, panel banners</td>
</tr>
<tr>
<td><code>--radius-pill</code></td>
<td>999px</td>
<td>Pills, badges, theme toggle, org badges</td>
</tr>
<tr>
<td><code>--border-radius</code></td>
<td>alias of <code>--radius-md</code></td>
<td>Legacy reference, do not remove</td>
</tr>
</tbody>
</table>
<h3>6b. The 4.0rem Tap-Target Rule</h3>
<p>Primary action tiles and navigational icons are strictly <strong><code>4rem × 4rem</code></strong> (<code>--tap-target</code>) to ensure tap-friendly hits during on-site mobile use. Icons inside use <code>line-height: 0</code> to prevent vertical drift during browser rendering.</p>
<h3>6c. Typography in Components</h3>
<p>Labels within Phase Pills, Role Tiles, and KPI tiles use <strong>bold</strong> weight to maintain legibility against saturated or surface-colored backgrounds.</p>
<hr />
<h2>7. Component Library</h2>
<p>All components below live in <code>css/style.css</code> and consume the tokens above.</p>
<h3>7a. Buttons (<code>.btn</code>)</h3>
<ul>
<li><code>.btn.btn-primary</code> — Filled <code>--color-primary</code>, white text. The primary call-to-action.</li>
<li><code>.btn.btn-secondary</code> — Surface fill with <code>--color-primary</code> border + text. Secondary actions on light surfaces.</li>
<li><code>.btn.btn-outline</code> — Transparent with <code>--color-secondary</code> border + text. Use on dark/colored sections or for neutral actions like Log Out.</li>
<li><code>.btn.btn-large</code> — Modifier: increased padding/font size for hero CTAs.</li>
</ul>
<h3>7b. Cards (<code>.card</code>)</h3>
<p>Surface-colored container with a top border-stroke in <code>--color-primary</code>. Used for marketing/info tiles on the home page. Hover lifts 5px.</p>
<h3>7c. KPI Tiles (<code>.kpi</code>)</h3>
<p>Surface-colored tile with a left border-stroke in a status color. Modifiers: <code>.kpi-blue</code>, <code>.kpi-green</code>, <code>.kpi-amber</code>, <code>.kpi-gray</code>. Internal structure: <code>.kpi-label</code> (uppercase meta), <code>.kpi-value</code> (large display number), <code>.kpi-sub</code> (footnote).</p>
<h3>7d. Chart Cards (<code>.chart-card</code>)</h3>
<p>Surface-colored panel for embedded <code>&lt;canvas&gt;</code> charts. Lay out with <code>.chart-grid</code> (auto-fit min 320px) or <code>.chart-grid.cols-2</code> (min 420px).</p>
<h3>7e. Pills / Status Badges (<code>.pill</code>)</h3>
<p>Pill-shaped inline status chip. Modifiers: <code>.pill-green</code>, <code>.pill-amber</code>, <code>.pill-red</code>, <code>.pill-blue</code>. Phase Pills (for project lifecycle) should additionally use the <code>--phase-&lt;n&gt;</code> colors per §3c.</p>
<h3>7f. Site Header &amp; Footer</h3>
<p><code>.site-header</code> is sticky, themed via <code>--color-header-bg</code> / <code>--color-header-text</code>. <code>.site-footer</code> lives at the bottom of every page with contact info and a small note, themed via <code>--color-footer-bg</code> / <code>--color-footer-text</code>.</p>
<h3>7g. Theme Toggle (<code>.theme-toggle</code>)</h3>
<p>Circular icon button in the nav bar with a sun/moon swap. Behaviour is implemented in <code>js/script.js</code>. Every page <strong>must</strong> include the inline pre-paint script in <code>&lt;head&gt;</code> to avoid a flash of the wrong theme:</p>
<pre><code class="language-html">&lt;script&gt;(function(){try{var t=localStorage.getItem(\'archr-theme\');if(t!==\'light\'&amp;&amp;t!==\'dark\'){t=window.matchMedia&amp;&amp;window.matchMedia(\'(prefers-color-scheme: dark)\').matches?\'dark\':\'light\';}document.documentElement.setAttribute(\'data-theme\',t);}catch(e){}})();&lt;/script&gt;</code></pre>
<p>And include <code>&lt;script src="js/script.js"&gt;&lt;/script&gt;</code> before <code>&lt;/body&gt;</code>.</p>
<hr />
<h2>8. Layout &amp; Container</h2>
<ul>
<li><code>.container</code> — <code>max-width: var(--container-max)</code> (1200px), horizontal padding <code>var(--container-gutter)</code> (20px), centered with <code>margin: 0 auto</code>. Every top-level <code>&lt;main&gt;</code>, <code>&lt;header&gt;</code>, and <code>&lt;footer&gt;</code> section uses it.</li>
<li>Stick to CSS Grid (<code>auto-fit, minmax(...)</code>) for tile/card layouts so they reflow without explicit breakpoints.</li>
</ul>
<hr />
<h2>9. Responsive Breakpoints</h2>
<table>
<thead>
<tr>
<th>Breakpoint</th>
<th>Media query</th>
<th>Used for</th>
</tr>
</thead>
<tbody>
<tr>
<td>≤ 992px</td>
<td><code>@media (max-width: 992px)</code></td>
<td>Hero stacks vertically, content flow adjusts</td>
</tr>
<tr>
<td>≤ 768px</td>
<td><code>@media (max-width: 768px)</code></td>
<td>Mobile nav re-stack, button full-width, hero h2 shrinks</td>
</tr>
<tr>
<td>≤ 700px</td>
<td><code>@media (max-width: 700px)</code></td>
<td>Dashboard hero/KPI shrink</td>
</tr>
</tbody>
</table>
<hr />
<h2>10. Accessibility</h2>
<ul>
<li>Use <code>&lt;button&gt;</code> for actions, <code>&lt;a&gt;</code> for navigation. Always provide visible text or <code>aria-label</code>.</li>
<li>The theme toggle uses <code>aria-pressed</code> to convey state.</li>
<li>Tap targets ≥ 44px; primary action tiles use 4rem (64px) per §6b.</li>
<li>Preserve <code>:focus-visible</code> outlines on every interactive element. The theme toggle uses a colored border on focus.</li>
<li>Aim for <strong>WCAG AA</strong> text contrast (≥ 4.5:1). White text on <code>--color-primary</code> and <code>--color-secondary</code> both pass; verify any new role-color backgrounds against intended text color.</li>
<li>Honor <code>prefers-color-scheme</code> on first load; never override a stored user choice automatically.</li>
</ul>
<hr />
<h2>11. Automated Triage &amp; Priority Logic</h2>
<p>To ensure the most vulnerable homeowners are prioritized, the ARCHR system utilizes an automated triage engine that scans intake data for critical risk factors.</p>
<p><strong>The Triage Mechanism</strong></p>
<ul>
<li>As applications enter Phase 1 (Intake), the AI scans text fields for qualitative "Red Flags" (e.g., "roof collapse," "exposed wiring," or "no running water").</li>
<li>The system automatically applies Priority Tags to these records, moving them to the top of the Marketplace dashboard.</li>
</ul>
<p><strong>Visual Priority Tags</strong></p>
<ul>
<li><strong>Safety (Critical)</strong> — Applied to structural, electrical, or habitability hazards. (Pair with <code>.pill.pill-red</code> / <code>--color-danger</code>.)</li>
<li><strong>Energy Saving</strong> — Applied to weatherization needs like insulation or window seals. (Pair with <code>.pill.pill-amber</code> / <code>--color-warning</code>.)</li>
<li><strong>Vulnerable Group</strong> — Flags applications from elderly, disabled, or extremely low-income residents. (Pair with <code>.pill.pill-blue</code> / <code>--color-info</code>.)</li>
</ul>
<p><strong>The Goal</strong></p>
<ul>
<li>The "Robot" reduces administrative friction by pre-sorting the workload.</li>
<li>This allows Subcontractors to see high-priority "Site Work" immediately and ensures funding is allocated to those in the greatest danger first.</li>
</ul>
<hr />
<h2>12. Standardization Status</h2>
<p>The following pages <strong>already</strong> consume <code>css/style.css</code> and follow this guide:</p>
<ul>
<li><code>index.html</code> (Home / Do I Qualify? / Our Partners / Volunteer tabs)</li>
<li><code>dashboard.html</code> (public Impact Dashboard)</li>
<li><code>dashboard-admin.html</code></li>
<li><code>partner-portal.html</code> (sidebar app shell — replaces the former <code>dashboard-partner.html</code> and <code>softr-rework.html</code>)</li>
</ul>
<p>The following pages <strong>do not yet conform</strong> to this system and are scheduled for future alignment. When working on them, prefer extracting their CSS to a partner stylesheet that imports the same <code>:root</code> tokens rather than maintaining a parallel design language.</p>
<table>
<thead>
<tr>
<th>Page</th>
<th>Current state</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>discovery_form/discovery-form.html</code></td>
<td>Own in-page <code>&lt;style&gt;</code>, green-gradient theme, <code>system-ui</code> font</td>
<td>Public intake form</td>
</tr>
<tr>
<td><code>view-submissions.php</code></td>
<td>Small in-page <code>&lt;style&gt;</code> block</td>
<td>Internal admin login + table view</td>
</tr>
<tr>
<td><code>documentation/anchor.html</code></td>
<td>Own in-page <code>&lt;style&gt;</code>, Inter, soft green/cream</td>
<td>Internal SOP doc</td>
</tr>
<tr>
<td><code>documentation/glossary.html</code></td>
<td>No styles attached</td>
<td>Likely needs the main stylesheet linked</td>
</tr>
<tr>
<td><code>intake_code/intake.html</code></td>
<td>Own <code>intake_code/style.css</code> (self-contained)</td>
<td>Treated as a sub-project; leave for now</td>
</tr>
</tbody>
</table>
<hr />
<h2>13. Reference: Live Site (archr.live)</h2>
<blockquote>
<p><em>Reference values observed on the public live site at <strong>archr.live</strong>. These are not the prototype\'s tokens — they\'re recorded here so the prototype\'s design system can be reconciled against what\'s already shipped, and so this section can be expanded as more of the live site is audited.</em></p>
</blockquote>
<p><strong>Actual colors on website:</strong></p>
<ul>
<li>Header/Footer Background: <code>#3b3637</code></li>
<li>Header Text: <code>#fafafa</code></li>
<li>Form Input Box: <code>#e5e5e5</code></li>
<li>Submit Button Hover: <code>#625e5f</code></li>
</ul>
<p><em>(Section to be expanded with typography, spacing, and component observations from the live site.)</em></p>
<hr />
<h2>14. Contact</h2>
<p>For UI/UX design clarifications, brand asset requests, or final interface approvals before deployment, please reach out directly.</p>
<p><strong>Contact:</strong> Ben Wyatt — bwyatt@ashevillehabitat.org</p>
<hr />
<h2>Appendix: Quick CSS Token Index</h2>
<p>The authoritative list lives in <code>:root</code> at the top of <code>css/style.css</code>. Categories:</p>
<ul>
<li><strong>Brand</strong> — <code>--color-primary</code>, <code>--color-primary-dark</code>, <code>--color-secondary</code>, <code>--color-canvas-cream</code></li>
<li><strong>Roles (11)</strong> — <code>--role-requestor</code> … <code>--role-admin</code>, plus per-role <code>--role-&lt;name&gt;-bg</code> / <code>--role-&lt;name&gt;-text</code> pairs that swap on dark mode (see §3b)</li>
<li><strong>Phases (6)</strong> — <code>--phase-0-select</code> … <code>--phase-5-complete</code> (see §3c)</li>
<li><strong>Semantic</strong> — <code>--color-success</code>, <code>--color-warning</code>, <code>--color-danger</code>, <code>--color-info</code></li>
<li><strong>Theme (light/dark swap)</strong> — <code>--bg-page</code>, <code>--bg-surface</code>, <code>--bg-surface-alt</code>, <code>--color-text</code>, <code>--color-text-muted</code>, <code>--color-text-inverse</code>, <code>--color-border-strong</code>, <code>--color-header-bg</code>, <code>--color-header-text</code>, <code>--color-footer-bg</code>, <code>--color-footer-text</code></li>
<li><strong>Legacy aliases</strong> — <code>--color-light</code>, <code>--color-dark</code>, <code>--color-gray</code>, <code>--color-border</code></li>
<li><strong>Typography</strong> — <code>--font-display</code>, <code>--font-sans</code>, <code>--fs-xs</code> … <code>--fs-3xl</code>, <code>--lh-tight</code>, <code>--lh-base</code></li>
<li><strong>Spacing</strong> — <code>--space-1</code> … <code>--space-12</code></li>
<li><strong>Radii</strong> — <code>--radius-sm</code>, <code>--radius-md</code>, <code>--radius-lg</code>, <code>--radius-pill</code>, <code>--border-radius</code></li>
<li><strong>Geometry</strong> — <code>--tap-target</code> (4rem)</li>
<li><strong>Layout</strong> — <code>--container-max</code>, <code>--container-gutter</code></li>
<li><strong>Effects</strong> — <code>--shadow-sm</code>, <code>--shadow</code>, <code>--shadow-lg</code>, <code>--transition</code></li>
<li><strong>Z-index</strong> — <code>--z-sticky</code>, <code>--z-dropdown</code>, <code>--z-modal</code></li>
</ul>',
);
