<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'component-documentation-status',
  'title' => 'Component Documentation Status Tracker',
  'category' => 'start-here',
  'category_name' => 'Start Here',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Component Documentation Status Tracker',
    'document_type' => 'Status Report',
    'version' => '1.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'Developers, Admins',
    'complexity_level' => 'Intermediate',
    'estimated_reading_minutes' => '5',
    'tags' => 
    array (
      0 => 'components',
      1 => 'documentation',
      2 => 'status',
      3 => 'tracking',
    ),
    'visibility' => 
    array (
      0 => 'admin',
      1 => 'super-admin',
    ),
  ),
  'source' => 'COMPONENT_DOCUMENTATION_STATUS.md',
  'html' => '<h1>Component Documentation Status</h1>
<h2>Overview</h2>
<p>This document tracks the status of component documentation across all roles. Each role should have component JSON files that match the pattern established in the best-documented roles.</p>
<hr />
<h2>✅ Completed API Endpoint Documentation</h2>
<p>All roles now have comprehensive API endpoint documentation in <code>interface/api-endpoints/</code>:</p>
<ul>
<li>✅ <strong>Assessor</strong> (<code>assessor-api-endpoints.md</code>) - 75 endpoints documented</li>
<li>✅ <strong>Project Manager</strong> (<code>pm-api-endpoints.md</code>) - 115 endpoints documented</li>
<li>✅ <strong>Crew Lead &amp; Member</strong> (<code>crew-api-endpoints.md</code>) - 113 endpoints documented</li>
<li>✅ <strong>Bursar</strong> (<code>bursar-api-endpoints.md</code>) - 73 endpoints documented</li>
<li>✅ <strong>Volunteer</strong> (<code>volunteer-api-endpoints.md</code>) - 60 endpoints documented</li>
<li>✅ <strong>Envoy</strong> (<code>envoy-api-endpoints.md</code>) - 53 endpoints documented</li>
<li>✅ <strong>Org Admin</strong> (<code>org-admin-api-endpoints.md</code>) - 86 endpoints documented</li>
<li>✅ <strong>Requestor</strong> (<code>requestor-api-endpoints.md</code>) - 48 endpoints documented</li>
<li>✅ <strong>Subcontractor</strong> (<code>api-endpoints-subcontractor.md</code>) - Already existed</li>
</ul>
<p><strong>Total: ~600+ API endpoints documented</strong></p>
<hr />
<h2>Component JSON Documentation Status</h2>
<h3>✅ Well-Documented (Has component_context)</h3>
<p><strong>Assessor</strong> (<code>components/components-assessor/</code>)</p>
<ul>
<li>24 component JSON files</li>
<li>All have proper structure</li>
<li>Good use of <code>component_context</code> in button components</li>
<li>Examples: <code>assess-button.json</code>, <code>doc-verification.json</code>, <code>verify-income-button.json</code></li>
</ul>
<p><strong>Subcontractor</strong> (<code>components/components-subcontractor/</code>)</p>
<ul>
<li>20 component JSON files</li>
<li>Consistent <code>component_context</code> pattern</li>
<li>Button components well-defined</li>
<li>Examples: <code>claim-task-button.json</code>, <code>submit-invoice-button.json</code></li>
</ul>
<p><strong>Crew</strong> (<code>components/components-crew/</code>)</p>
<ul>
<li>10 component JSON files</li>
<li>Good mobile-first documentation</li>
<li>Examples: <code>safety-talk.json</code>, <code>upload-photos.json</code>, <code>volunteer-management.json</code></li>
</ul>
<h3>⏳ Partially Documented (Needs Enhancement)</h3>
<p><strong>Bursar</strong> (<code>interface/bursar/</code>)</p>
<ul>
<li>Has <code>bursar-components.json</code> (comprehensive role documentation)</li>
<li>Has 2 component files in <code>interface/bursar/components/</code></li>
<li><strong>TODO</strong>: Create individual button components with <code>component_context</code> in <code>components/components-bursar/</code></li>
</ul>
<h3>❌ Not Yet Documented</h3>
<p><strong>Project Manager</strong> (<code>components/components-project-manager/</code>)</p>
<ul>
<li><strong>TODO</strong>: Create directory and component files</li>
<li>Key components needed:<ul>
<li>Claim job button</li>
<li>Approve estimate button</li>
<li>Assign crew button</li>
<li>Escalation buttons</li>
<li>Project status components</li>
<li>Budget tracking components</li>
</ul>
</li>
</ul>
<p><strong>Crew Lead</strong> (<code>components/components-crew-lead/</code>)</p>
<ul>
<li><strong>TODO</strong>: Create directory and component files</li>
<li>Key components needed:<ul>
<li>Set current job button</li>
<li>Update task status button</li>
<li>Change order request button</li>
<li>Daily log component</li>
<li>Safety talk component</li>
<li>Completion sign-off button</li>
</ul>
</li>
</ul>
<p><strong>Volunteer</strong> (<code>components/components-volunteer/</code>)</p>
<ul>
<li><strong>TODO</strong>: Create directory and component files</li>
<li>Key components needed:<ul>
<li>Claim slot button</li>
<li>Sign in/out buttons</li>
<li>Available opportunities list</li>
<li>Assignment cards</li>
<li>Experience/gamification components</li>
</ul>
</li>
</ul>
<p><strong>Envoy</strong> (<code>components/components-envoy/</code>)</p>
<ul>
<li><strong>TODO</strong>: Create directory and component files</li>
<li>Key components needed:<ul>
<li>New applications list</li>
<li>Assign application button</li>
<li>Contact applicant button</li>
<li>Outreach event components</li>
<li>Follow-up task components</li>
</ul>
</li>
</ul>
<p><strong>Org Admin</strong> (<code>components/components-org-admin/</code>)</p>
<ul>
<li><strong>TODO</strong>: Create directory and component files</li>
<li>Key components needed:<ul>
<li>User management buttons</li>
<li>Settings components</li>
<li>Organization management</li>
<li>System configuration components</li>
</ul>
</li>
</ul>
<p><strong>Requestor</strong> (<code>components/components-requestor/</code>)</p>
<ul>
<li><strong>TODO</strong>: Create directory and component files</li>
<li>Key components needed:<ul>
<li>Application status component</li>
<li>Document upload button</li>
<li>Message caseworker button</li>
<li>Timeline component</li>
<li>Eligibility results display</li>
</ul>
</li>
</ul>
<hr />
<h2>Component Standards</h2>
<h3>Button Component Template with <code>component_context</code></h3>
<pre><code class="language-json">{
  "component_name": "Button Name",
  "component_role": "role_name",
  "component_id": "btn_unique_id",
  "component_class": ".btn.btn-primary",
  "component_context": {
    "taskId": "rec[taskIdentifier]",
    "target": "data.field",
    "target_key": "{variable}.{field}",
    "action": "ACTION.TYPE",
    "buttonText": "Button Label",
    "webhookSlug": "[webhookIdentifier]",
    "confirm": "Confirmation message?",
    "successMessage": "Success message!",
    "reversible": "yes/no"
  }
}</code></pre>
<h3>List Component Template</h3>
<pre><code class="language-json">{
  "component_name": "List Name",
  "component_id": "cmp_list_id",
  "component_type": "list",
  "data_sources": {
    "items": "table_name where condition"
  },
  "list_item_actions": [
    {
      "label": "Action Label",
      "action": "navigate/phone/email/etc",
      "target": "/path/{param}"
    }
  ],
  "sort_order": "field ASC/DESC",
  "mobile_layout": "cards/list/table"
}</code></pre>
<hr />
<h2>Next Steps</h2>
<ol>
<li><strong>Create component directories</strong> for missing roles</li>
<li><strong>Document button components</strong> with <code>component_context</code> following assessor/subcontractor patterns</li>
<li><strong>Document list/display components</strong> for each role\'s main views</li>
<li><strong>Standardize existing components</strong> to match best practices</li>
<li><strong>Cross-reference with API endpoints</strong> to ensure consistency</li>
</ol>
<hr />
<h2>Reference Files</h2>
<p><strong>Best Examples:</strong></p>
<ul>
<li><code>components/components-assessor/doc-verification.json</code> - Button with full context</li>
<li><code>components/components-subcontractor/claim-task-button.json</code> - Clean button pattern</li>
<li><code>components/components-assessor/todays-assessments.json</code> - List component</li>
<li><code>interface/bursar/bursar-components.json</code> - Comprehensive role documentation</li>
</ul>
<p><strong>Templates:</strong></p>
<ul>
<li><code>components/template.json</code> - Basic template</li>
<li><code>components/example.json</code> - Component type reference</li>
</ul>
<hr />
<h2>Component Types Available</h2>
<p><code>BUTTON</code>, <code>LIST</code>, <code>LIST_ITEM</code>, <code>DETAILS</code>, <code>TABLE</code>, <code>ALERT</code>, <code>TOOL_TIP</code>, <code>INBOX</code>, <code>INBOX_MESSAGE</code>, <code>FORM</code>, <code>CONFIRM_PROMPT</code>, <code>METRIC_NUM</code>, <code>METRIC_LINE</code>, <code>METRIC_PIE</code>, <code>PROGRESS_BAR</code>, <code>PROGRESS_TASKS</code>, <code>PROJECT_TASKS</code>, <code>VERIFICATION_TASKS</code>, <code>GRID</code>, <code>GRID_ITEM</code>, <code>PROJECT_SUMMARY</code>, <code>DOCUMENT_DISPLAY</code>, <code>CALENDAR</code>, <code>CALENDAR_EVENT</code>, <code>ORGANIZATION</code>, <code>PARTNER_PROGRAM</code>, <code>PERSON</code>, <code>REPORT</code>, <code>ROLE</code>, <code>HEADS_UP_DISPLAY</code></p>',
);
