<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'conducting-home-assessment',
  'title' => 'Conducting a Home Assessment SOP',
  'category' => 'sops',
  'category_name' => 'Standard Operating Procedures',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Conducting a Home Assessment SOP',
    'document_type' => 'Standard Operating Procedure',
    'version' => '1.0',
    'last_updated' => '2026-09-07',
    'author' => 'ARCHR Development Team',
    'audience' => 'Assessors, Caseworkers',
    'complexity_level' => 'Intermediate',
    'estimated_reading_minutes' => '8',
    'tags' => 
    array (
      0 => 'assessment',
      1 => 'field-work',
      2 => 'photos',
      3 => 'estimates',
      4 => 'SOP',
    ),
    'visibility' => 'authenticated',
  ),
  'source' => 'sops\\conducting-home-assessment.md',
  'html' => '<h1>Conducting a Home Assessment</h1>
<blockquote>
<p><strong>Who this is for:</strong> Assessors who visit properties to evaluate repair needs and create estimates. Also useful for Caseworkers who coordinate assessments.</p>
</blockquote>
<h2>Why This Matters</h2>
<p>Quality assessments determine accurate estimates and successful repairs. A good assessment means the right crew shows up with the right materials. A bad assessment means they show up, realize the problem is twice as big as expected, and leave — and the applicant waits longer.</p>
<p><strong>Your assessment is the blueprint for everything that follows.</strong> Get it right and the whole project flows. Get it wrong and everyone pays for it — in time, money, and frustration.</p>
<hr />
<h2>Before You Go: Preparation Checklist</h2>
<ul>
<li>[ ] <strong>Review the application</strong> — what repair needs did the applicant report?</li>
<li>[ ] <strong>Check eligibility flags</strong> — any red or yellow flags you should know about?</li>
<li>[ ] <strong>Confirm the address</strong> — placecode and property address should match</li>
<li>[ ] <strong>Contact the applicant</strong> — schedule a time that works for them</li>
<li>[ ] <strong>Charge your phone/tablet</strong> — you\'ll be taking photos and filling out the assessment form</li>
<li>[ ] <strong>Bring measuring tools</strong> — tape measure, level, moisture meter if available</li>
<li>[ ] <strong>Bring safety gear</strong> — hard hat, flashlight, gloves if entering damaged areas</li>
</ul>
<blockquote>
<p><strong>Pro tip:</strong> Ask the applicant to gather any insurance documents, FEMA correspondence, or contractor estimates they may have. This saves a follow-up trip.</p>
</blockquote>
<hr />
<h2>On-Site: Step-by-Step Assessment</h2>
<h3>1. Start with the Exterior</h3>
<p>Walk the property perimeter first. Look for:</p>
<ul>
<li>Roof damage (missing shingles, sagging, visible holes)</li>
<li>Siding damage (missing panels, water stains, warping)</li>
<li>Foundation issues (cracks, settling, water intrusion)</li>
<li>Gutter and drainage problems</li>
<li>Tree damage affecting the structure</li>
</ul>
<h3>2. Assess Each Room Systematically</h3>
<p>For each room, check:</p>
<ul>
<li><strong>Walls</strong> — water damage, mold, structural cracks</li>
<li><strong>Floors</strong> — warping, soft spots, water damage</li>
<li><strong>Ceiling</strong> — stains, sagging, active leaks</li>
<li><strong>Windows/doors</strong> — operable, sealed, damaged</li>
<li><strong>Electrical</strong> — outlets working, visible wiring damage</li>
<li><strong>Plumbing</strong> — water pressure, visible leaks, water heater condition</li>
</ul>
<h3>3. Document with Photos</h3>
<p><strong>The photo rule:</strong> Every repair need gets at least two photos — one wide shot showing context, one close-up showing the specific issue.</p>
<p><strong>Photo best practices:</strong></p>
<ul>
<li>Turn on location services — photos with GPS data are far more useful</li>
<li>Include a reference object (ruler, hand, coin) for scale</li>
<li>Take "before" photos from the same angle you\'ll use for "after"</li>
<li>Label photos in the system with room + issue (e.g., "Kitchen - ceiling water damage")</li>
</ul>
<blockquote>
<p><strong>Important:</strong> Photos aren\'t just documentation. They\'re evidence for grant reporting, insurance claims, and proving the work was done. A case without photos is a case that can\'t be closed properly.</p>
</blockquote>
<h3>4. Fill Out the Assessment Form</h3>
<p>In the platform (mobile app or desktop):</p>
<ol>
<li><strong>Open the assigned case</strong></li>
<li><strong>Navigate to the Assessment section</strong></li>
<li><strong>Select each repair category</strong> that applies (roof, plumbing, electrical, etc.)</li>
<li><strong>Describe the damage</strong> — be specific. "Roof leaking" is not as useful as "3\' × 4\' section of missing shingles on east-facing slope, active water intrusion into attic"</li>
<li><strong>Estimate severity</strong> — minor, moderate, severe, or urgent</li>
<li><strong>Note any safety hazards</strong> — structural instability, exposed wiring, mold</li>
</ol>
<h3>5. Create a Preliminary Estimate</h3>
<p>For each repair need, note:</p>
<ul>
<li><strong>What trade(s) are required</strong> — roofing, plumbing, electrical, carpentry, etc.</li>
<li><strong>Rough scope</strong> — how much work? (e.g., "Replace 40 sq ft of subfloor in bathroom")</li>
<li><strong>Materials needed</strong> — approximate types and quantities</li>
<li><strong>Estimated labor hours</strong> — your best guess based on experience</li>
</ul>
<blockquote>
<p><strong>You don\'t need exact numbers here.</strong> A rough estimate is fine — the contractor or crew lead will refine it. But "I don\'t know" doesn\'t help anyone. Use your professional judgment.</p>
</blockquote>
<hr />
<h2>What If the Applicant Disagrees?</h2>
<p>Sometimes an applicant thinks their repair need is bigger (or smaller) than your assessment says. This is normal.</p>
<p><strong>How to handle it:</strong></p>
<ol>
<li><strong>Listen</strong> — the applicant knows their home better than you do</li>
<li><strong>Explain your findings</strong> — walk them through what you observed</li>
<li><strong>Document the disagreement</strong> — note it in the assessment. "Applicant reports additional leaking in basement not visible during assessment — recommend follow-up inspection"</li>
<li><strong>Don\'t argue</strong> — if there\'s uncertainty, flag it for the caseworker or PM to investigate</li>
</ol>
<p><strong>Remember:</strong> The applicant has been through a disaster. They\'re stressed. Patience goes a long way.</p>
<hr />
<h2>After the Assessment</h2>
<ol>
<li><strong>Submit the assessment</strong> in the platform</li>
<li><strong>Log a progress event</strong> — "Assessment completed by [Your Name]"</li>
<li><strong>Notify the caseworker</strong> — they should follow up with the applicant to discuss findings</li>
<li><strong>Upload any additional photos</strong> you didn\'t capture in the assessment form</li>
</ol>
<hr />
<h2>Quick Reference: Assessment Categories</h2>
<table>
<thead>
<tr>
<th>Category</th>
<th>What to Look For</th>
<th>Typical Trades Needed</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Roof</strong></td>
<td>Missing shingles, leaks, structural damage</td>
<td>Roofer</td>
</tr>
<tr>
<td><strong>Plumbing</strong></td>
<td>Leaks, no water, damaged pipes</td>
<td>Plumber</td>
</tr>
<tr>
<td><strong>Electrical</strong></td>
<td>Exposed wiring, non-functional outlets, panel damage</td>
<td>Electrician</td>
</tr>
<tr>
<td><strong>HVAC</strong></td>
<td>No heat/AC, damaged ductwork</td>
<td>HVAC technician</td>
</tr>
<tr>
<td><strong>Structural</strong></td>
<td>Foundation cracks, wall bowing, floor sagging</td>
<td>General contractor</td>
</tr>
<tr>
<td><strong>Interior</strong></td>
<td>Water damage, mold, damaged drywall</td>
<td>Carpenter, painter</td>
</tr>
<tr>
<td><strong>Accessibility</strong></td>
<td>Ramps, door widths, bathroom modifications</td>
<td>General contractor</td>
</tr>
<tr>
<td><strong>Safety</strong></td>
<td>Exposed hazards, entry security</td>
<td>Various</td>
</tr>
</tbody>
</table>
<hr />
<p><strong>Remember:</strong> Your assessment is the foundation of the repair plan. The better you document, the smoother the project goes.</p>',
);
