<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'document-management',
  'title' => 'Document Management — Uploading, Organizing & Finding Files',
  'category' => 'sops',
  'category_name' => 'Standard Operating Procedures',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Document Management — Uploading, Organizing & Finding Files',
    'document_type' => 'Standard Operating Procedure',
    'version' => '1.0',
    'last_updated' => '2026-09-07',
    'author' => 'ARCHR Development Team',
    'audience' => 'All Platform Users',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '6',
    'tags' => 
    array (
      0 => 'documents',
      1 => 'uploads',
      2 => 'file-management',
      3 => 'photos',
      4 => 'SOP',
    ),
    'visibility' => 'authenticated',
  ),
  'source' => 'sops\\document-management.md',
  'html' => '<h1>Document Management: Uploading, Organizing &amp; Finding Files</h1>
<blockquote>
<p><strong>Who this is for:</strong> Everyone who uploads, views, or manages documents in the platform — which is every role.</p>
</blockquote>
<h2>Why This Is Needed</h2>
<p>The document system is powerful but complex. Photos prove the work was done. Income docs prove eligibility. Contracts prove agreement. <strong>Every document in a case is evidence</strong> — for the applicant, the organization, and the funder.</p>
<p>A case with no documents is a case that can\'t be closed properly. A case with disorganized documents is a case that fails an audit.</p>
<hr />
<h2>What Kinds of Documents Exist</h2>
<table>
<thead>
<tr>
<th>Document Type</th>
<th>Who Uploads</th>
<th>When</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Income verification</strong></td>
<td>Applicant, Envoy</td>
<td>During intake</td>
<td>Proves eligibility</td>
</tr>
<tr>
<td><strong>Photo ID</strong></td>
<td>Applicant, Envoy</td>
<td>During intake</td>
<td>Confirms identity</td>
</tr>
<tr>
<td><strong>Before photos</strong></td>
<td>Assessor, Crew</td>
<td>At assessment</td>
<td>Documents damage</td>
</tr>
<tr>
<td><strong>During photos</strong></td>
<td>Crew, Volunteer</td>
<td>During repair</td>
<td>Shows progress</td>
</tr>
<tr>
<td><strong>After photos</strong></td>
<td>Crew, PM</td>
<td>At completion</td>
<td>Proves work done</td>
</tr>
<tr>
<td><strong>Contracts</strong></td>
<td>PM, Admin</td>
<td>Before work starts</td>
<td>Legal agreement</td>
</tr>
<tr>
<td><strong>Invoices</strong></td>
<td>Subcontractor, Bursar</td>
<td>After work completed</td>
<td>Payment request</td>
</tr>
<tr>
<td><strong>Assessments</strong></td>
<td>Assessor</td>
<td>After site visit</td>
<td>Repair scope</td>
</tr>
<tr>
<td><strong>Communication logs</strong></td>
<td>Anyone</td>
<td>After any contact</td>
<td>Record of interaction</td>
</tr>
<tr>
<td><strong>Progress notes</strong></td>
<td>Anyone</td>
<td>As work happens</td>
<td>Timeline evidence</td>
</tr>
</tbody>
</table>
<hr />
<h2>Uploading Documents</h2>
<h3>Step-by-Step</h3>
<ol>
<li><strong>Open the case</strong> you\'re uploading to</li>
<li><strong>Navigate to the Documents section</strong></li>
<li><strong>Click "Upload Document"</strong></li>
<li><strong>Select the document type</strong> from the dropdown (income verification, before photo, etc.)</li>
<li><strong>Choose the file</strong> from your device<ul>
<li>Accepted formats: PDF, JPG, PNG</li>
<li>Max file size: 25MB per file</li>
</ul>
</li>
<li><strong>Add a description</strong> (optional but helpful) — "Before - Roof, east section"</li>
<li><strong>Upload</strong></li>
</ol>
<blockquote>
<p><strong>Tip:</strong> Name your files before uploading. "before_roof_east.jpg" is infinitely more useful than "IMG_4721.jpg."</p>
</blockquote>
<h3>Uploading Multiple Files at Once</h3>
<p>The platform supports multi-file upload. Select all the files you want to upload at once, and the system will process them as a batch.</p>
<p><strong>Best practice:</strong> Upload files of the same type together. Don\'t mix before photos with invoices — upload them as separate batches with appropriate document types.</p>
<hr />
<h2>Photo Best Practices</h2>
<h3>Before Photos</h3>
<ul>
<li><strong>Wide shot</strong> showing the full repair area</li>
<li><strong>Close-up</strong> showing the specific damage</li>
<li><strong>Include a reference</strong> for scale (hand, ruler, coin)</li>
<li><strong>Same angles</strong> you\'ll use for after photos</li>
<li><strong>Label with room/area</strong> — "Kitchen ceiling, northwest corner"</li>
</ul>
<h3>After Photos</h3>
<ul>
<li><strong>Same angles</strong> as before photos (side-by-side comparison is powerful)</li>
<li><strong>Well-lit</strong> — turn on lights, open blinds, use flash</li>
<li><strong>Clean workspace</strong> — no tools, debris, or ladders in the shot</li>
<li><strong>Label clearly</strong> — "After - Roof repair, east section, 9/15/2026"</li>
</ul>
<h3>During Photos</h3>
<ul>
<li><strong>Progress milestones</strong> — demo complete, rough-in installed, drywall hung</li>
<li><strong>Hidden work</strong> — things that will be covered up (wiring behind walls, subfloor under finish floor)</li>
<li><strong>Unexpected findings</strong> — "Opened wall, found mold on insulation"</li>
</ul>
<blockquote>
<p><strong>Grant reporting gold:</strong> Before/after side-by-side comparisons are the single most compelling evidence for funders. Take the time to get them right.</p>
</blockquote>
<hr />
<h2>Finding Documents</h2>
<h3>In a Case</h3>
<p>Open the case and go to the Documents tab. You can:</p>
<ul>
<li><strong>Filter by type</strong> — show only photos, only invoices, etc.</li>
<li><strong>Sort by date</strong> — newest first, or oldest first</li>
<li><strong>Search by description</strong> — if someone labeled files well</li>
</ul>
<h3>Across Cases</h3>
<p>Use Case Search with document filters to find:</p>
<ul>
<li>All cases with missing after photos</li>
<li>All cases with uploaded contracts</li>
<li>All cases from a specific date range with documents</li>
</ul>
<hr />
<h2>Document Security</h2>
<h3>Who Can See What</h3>
<table>
<thead>
<tr>
<th>Document Type</th>
<th>Visible To</th>
</tr>
</thead>
<tbody>
<tr>
<td>Income verification</td>
<td>Assigned caseworker, Admin, Bursar</td>
</tr>
<tr>
<td>Photo ID</td>
<td>Assigned caseworker, Admin</td>
</tr>
<tr>
<td>Photos (before/during/after)</td>
<td>All assigned staff, applicant</td>
</tr>
<tr>
<td>Contracts</td>
<td>PM, Admin, applicant</td>
</tr>
<tr>
<td>Invoices</td>
<td>Bursar, PM, Admin</td>
</tr>
<tr>
<td>Assessments</td>
<td>All assigned staff</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Sensitive documents</strong> (income verification, ID) have restricted access. Only people who need them for eligibility determination can view them.</p>
</blockquote>
<h3>What Applicants Can See</h3>
<p>Applicants can see:</p>
<ul>
<li>Photos of their own property</li>
<li>Contracts they\'ve signed</li>
<li>Communication logs addressed to them</li>
</ul>
<p>Applicants <strong>cannot</strong> see:</p>
<ul>
<li>Other applicants\' documents</li>
<li>Internal staff notes</li>
<li>Financial records (invoices, payment records)</li>
</ul>
<hr />
<h2>Common Problems &amp; Solutions</h2>
<h3>"My Upload Keeps Failing"</h3>
<ul>
<li><strong>Check file size</strong> — is it over 25MB? Compress it or split it</li>
<li><strong>Check file type</strong> — is it a PDF, JPG, or PNG? Other formats aren\'t accepted</li>
<li><strong>Check your connection</strong> — a slow internet connection can timeout large uploads</li>
<li><strong>Try a different browser</strong> — some browsers handle large uploads better</li>
</ul>
<h3>"A Photo Disappeared"</h3>
<ul>
<li>Check the <strong>trash/version history</strong> — deleted files may be recoverable</li>
<li>Check if someone <strong>re-categorized</strong> it — it may be under a different document type</li>
<li>Check the <strong>activity log</strong> — who uploaded it, and was it later deleted?</li>
</ul>
<h3>"I Can\'t See a Document I Know Exists"</h3>
<ul>
<li>Check your <strong>permissions</strong> — some documents are restricted to certain roles</li>
<li>Check the <strong>case</strong> — are you looking at the right case?</li>
<li>Ask the <strong>caseworker</strong> — they can see what documents are attached and who can view them</li>
</ul>
<hr />
<h2>Document Retention</h2>
<p>Different document types have different retention requirements:</p>
<table>
<thead>
<tr>
<th>Document Type</th>
<th>Retention Period</th>
</tr>
</thead>
<tbody>
<tr>
<td>Financial records (invoices, receipts)</td>
<td>7 years</td>
</tr>
<tr>
<td>Contracts</td>
<td>10 years</td>
</tr>
<tr>
<td>Photos</td>
<td>Permanent</td>
</tr>
<tr>
<td>Income verification</td>
<td>7 years</td>
</tr>
<tr>
<td>Photo ID</td>
<td>3 years</td>
</tr>
<tr>
<td>Assessments</td>
<td>5 years</td>
</tr>
</tbody>
</table>
<p><strong>The platform retains documents according to these schedules.</strong> Don\'t manually delete documents — the system handles retention automatically.</p>
<hr />
<h2>Quick Reference</h2>
<table>
<thead>
<tr>
<th>Action</th>
<th>Where</th>
<th>Who</th>
</tr>
</thead>
<tbody>
<tr>
<td>Upload document</td>
<td>Case detail → Documents → "Upload"</td>
<td>Everyone</td>
</tr>
<tr>
<td>View documents</td>
<td>Case detail → Documents tab</td>
<td>Role-dependent</td>
</tr>
<tr>
<td>Filter by type</td>
<td>Documents tab → Filter dropdown</td>
<td>Everyone</td>
</tr>
<tr>
<td>Download document</td>
<td>Document detail → "Download"</td>
<td>Role-dependent</td>
</tr>
<tr>
<td>Delete document</td>
<td>Document detail → "Delete" (restricted)</td>
<td>Admin only</td>
</tr>
<tr>
<td>View activity log</td>
<td>Case detail → Activity Log</td>
<td>Everyone</td>
</tr>
</tbody>
</table>
<hr />
<p><strong>Remember:</strong> A document in the system is evidence. A document on someone\'s phone is a memory. Put it in the system.</p>',
);
