<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'editing-applicant-contact-info',
  'title' => 'Editing Applicant Contact Info',
  'category' => 'sops',
  'category_name' => 'Standard Operating Procedures',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'title' => 'Editing Applicant Contact Info (Name, Phone, Email)',
    'visibility' => 'authenticated',
  ),
  'source' => 'sops\\editing-applicant-contact-info.md',
  'html' => '<h1>Editing Applicant Contact Info</h1>
<h2>When this comes up</h2>
<p>The contact details on a case sometimes belong to the wrong person — most
often a <strong>referrer or neighbor</strong> who filled out the intake form on behalf of
the person actually needing help. You usually find out through a
communication log (e.g. a caseworker called the number and reached the
referrer, not the applicant).</p>
<h2>The rule: never edit the raw submission</h2>
<p>Submissions (<code>intake_submissions</code>) are the <strong>preserved, as-received</strong> form
data. Corrections belong on the <strong>application</strong> — the editable working copy
created from the submission for intake and eligibility work. Cases hang off
the application, so a correction on the application is reflected on every
case for that household.</p>
<pre><code>submission (raw, never edited)  -&gt;  application (edit here)  -&gt;  case(s) -&gt; project(s)</code></pre>
<h2>How to make the correction</h2>
<ol>
<li>Open the case from the <strong>Case List</strong> (filterable by organization) and
click through to <strong>Case Review</strong>.</li>
<li>Under <strong>Applicant</strong>, click <strong>Edit contact info</strong>.</li>
<li>Update first name, last name, email, and/or phone, then <strong>Save</strong>.</li>
</ol>
<p>What happens behind the scenes (implemented in the Vue demo and mirrored in
<code>app/</code>):</p>
<ul>
<li>If an <strong>application</strong> already exists for the submission, only its
<code>applicant_first_name</code> / <code>applicant_last_name</code> / <code>applicant_email</code> /
<code>applicant_phone</code> fields are updated.</li>
<li>If none exists yet, one is <strong>created as a copy of the submission</strong> first
(same behavior as <code>deduplicate_submissions</code> in
<code>sql/application-lifecycle.sql</code>), then your edit is applied.</li>
<li>The raw submission row is left untouched either way.</li>
<li>The Case Review shows an <strong>edited</strong> flag once an application backs the
contact fields, so staff can tell corrected data from raw intake data.</li>
</ul>
<h2>Follow-ups</h2>
<ul>
<li>If the phone number on file belongs to a referrer, add a communication
log entry noting whose number it was and how the correct one was obtained.</li>
<li>If the <em>address</em> is wrong (not just contact info), that\'s a bigger change —
the placecode and deduplication are keyed off the address; escalate to an
org admin rather than editing in place.</li>
</ul>',
);
