<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'eligibility',
  'title' => 'Who Qualifies? Eligibility Determination & Assuming Eligibility',
  'category' => 'archr101',
  'category_name' => 'ARCHR 101',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Who Qualifies? Eligibility Determination & Assuming Eligibility',
    'document_type' => 'Policy Guide',
    'version' => '1.0',
    'last_updated' => '2026-07-10',
    'author' => 'ARCHR Development Team',
    'audience' => 'Requestors, Caseworkers, Admin',
    'complexity_level' => 'Intermediate',
    'estimated_reading_minutes' => '4-6 minutes',
    'tags' => 
    array (
      0 => 'eligibility',
      1 => 'income',
      2 => 'geography',
      3 => 'homeowners',
      4 => 'qualifying',
    ),
  ),
  'source' => 'archr101\\eligibility.md',
  'html' => '<p><strong>Our Philosophy: Assume Eligibility</strong></p>
<ul>
<li>We assume every applicant is eligible until we find disqualifying information</li>
<li>This prevents eligible people from being turned away due to technicalities</li>
<li>Eligibility checks are a process, not a gatekeeping moment</li>
</ul>
<p><strong>2. What Makes Someone Eligible?</strong></p>
<table>
<thead>
<tr>
<th>Category</th>
<th>Requirements</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Geography</strong></td>
<td>Property must be in service area (Buncombe, Madison, Henderson, Haywood counties)</td>
</tr>
<tr>
<td><strong>Home Ownership</strong></td>
<td>Applicant must own the home (or have legal authority to authorize repairs)</td>
</tr>
<tr>
<td><strong>Primary Residence</strong></td>
<td>Must be primary residence, not rental or vacation property</td>
</tr>
<tr>
<td><strong>Income</strong></td>
<td>No lower limit. Upper limit varies by organization (typically 80% AMI)</td>
</tr>
<tr>
<td><strong>Cause of Damage</strong></td>
<td>Damage must be related to Hurricane Helene (September 2024)</td>
</tr>
<tr>
<td><strong>Household Size</strong></td>
<td>Counts residents 50%+ of the time</td>
</tr>
<tr>
<td><strong>Demographics</strong></td>
<td>No discrimination; special programs for veterans, elderly, disabled</td>
</tr>
</tbody>
</table>
<p><strong>3. The Eligibility Review Process</strong></p>
<ul>
<li>
<p><strong>Automated Check</strong>: System runs initial eligibility on submission</p>
</li>
<li>
<p><strong>Manual Review</strong>: Caseworker verifies documentation</p>
</li>
<li>
<p><strong>Organization Match</strong>: System finds best-fit organization (income, location, repair type)</p>
</li>
<li>
<p><strong>Final Determination</strong>: Assigned organization confirms eligibility</p>
</li>
</ul>
<p><strong>4. What Makes Someone Ineligible (Disqualifiers)</strong></p>
<ul>
<li>
<p>Property outside service area</p>
</li>
<li>
<p>Not a homeowner</p>
</li>
<li>
<p>Not primary residence</p>
</li>
<li>
<p>Previous assistance received for same repair</p>
</li>
<li>
<p>Income exceeds all partner maximums</p>
</li>
<li>
<p>Mobile home without lot ownership</p>
</li>
<li>
<p>Under 18 without guardian consent</p>
</li>
</ul>
<p><strong>5. What If I\'m Denied?</strong></p>
<ul>
<li>
<p>You will receive a clear explanation</p>
</li>
<li>
<p>You can appeal with additional documentation</p>
</li>
<li>
<p>You may be referred to other resources</p>
</li>
</ul>',
);
