<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'excel-gateway',
  'title' => 'Excel Gateway Exploration',
  'category' => 'feedback-meeting',
  'category_name' => 'Coalition Feedback & Insights',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Excel Gateway Exploration',
    'document_type' => 'Speculative Text Document',
    'version' => '1.0',
    'last_updated' => '2026-08-06',
    'author' => 'April Chips',
    'audience' => 'Staff involved with ARCHR Platform',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '3',
    'tags' => 
    array (
      0 => 'tasks',
      1 => 'logs',
      2 => 'events',
      3 => 'documentation',
      4 => 'SOP',
    ),
  ),
  'source' => 'feedback-meeting\\excel-gateway.md',
  'html' => '<p>This text document is to raise a question about throwing Excel workflow users a bone. Can we set up a method of letting people work in Excel while still feeding data into the system, and retrieving current data into templates?</p>
<p>Some of our team members are much more comfortable with the aesthetic of working in Excel. </p>
<p>The problem is that, Excel does not support the relational database needs of a home repair coalition spanning multiple organizations.</p>
<p>But for select tasks, we can create Smart Templates in Excel. These can link up and feed information to our database, and also pull immutable data into excel sheets to work with temporarily.</p>
<p>This would be for one person, working on one document at a given time. </p>
<p>It\'s possible, worthwhile, and realistic. This is something fairly common in other organizations. </p>
<p>Excel is a tool. It is not a database. It cannot handle complicated relational needs. </p>
<p>[[It should just behave more like Excel..]]</p>
<p>There are some caveats.</p>
<h3>Path 1: Excel as a Data Entry Interface</h3>
<p><strong>What it is:</strong> People fill out Excel templates. The system imports the data.</p>
<p>Excel Template → CSV Export → System Import → Data in Database</p>
<p>CSV, or Comma Separated Values, is one way to intermediate data. </p>
<p><strong>How it works:</strong></p>
<table>
<thead>
<tr>
<th>Step</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>Create an Excel template with specific columns</td>
</tr>
<tr>
<td>2</td>
<td>User fills it out in Excel (their happy place)</td>
</tr>
<tr>
<td>3</td>
<td>User saves and uploads to the system</td>
</tr>
<tr>
<td>4</td>
<td>System validates and imports the data</td>
</tr>
<tr>
<td>5</td>
<td>Data now lives in the system, ready for everyone else</td>
</tr>
</tbody>
</table>
<p><strong>Pros:</strong></p>
<ul>
<li>Familiar interface</li>
<li>No learning curve</li>
<li>Works offline</li>
<li>Anyone with Excel can do it</li>
</ul>
<p><strong>Cons:</strong></p>
<ul>
<li>Requires manual upload</li>
<li>No real-time validation</li>
<li>Potential for formatting errors</li>
<li>Creates a "batch" workflow instead of real-time</li>
</ul>
<p><strong>Is it realistic?</strong> Yes. Many systems do this.</p>
<p><strong>Is it worthwhile?</strong> For a subset of users, absolutely.</p>
<hr />
<h3>Path 2: Excel as a View Interface</h3>
<p><strong>What it is:</strong> The system generates Excel-like reports that users can work with.</p>
<p>text</p>
<p>System Data → Excel Export → User Works in Excel → Excel Upload → System Updated</p>
<p><strong>How it works:</strong></p>
<table>
<thead>
<tr>
<th>Step</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>User requests data from the system</td>
</tr>
<tr>
<td>2</td>
<td>System exports a formatted Excel file</td>
</tr>
<tr>
<td>3</td>
<td>User works in Excel (filtering, sorting, notes)</td>
</tr>
<tr>
<td>4</td>
<td>User exports changes as CSV</td>
</tr>
<tr>
<td>5</td>
<td>System imports updates</td>
</tr>
</tbody>
</table>
<p><strong>Pros:</strong></p>
<ul>
<li>
<p>Users get the data they need in their preferred format</p>
</li>
<li>
<p>They can do their own analysis</p>
</li>
<li>
<p>They feel in control</p>
</li>
</ul>
<p><strong>Cons:</strong></p>
<ul>
<li>
<p>Still requires an upload step</p>
</li>
<li>
<p>Sync issues if multiple people work on the same file</p>
</li>
<li>
<p>Security and version control concerns</p>
</li>
</ul>
<p><strong>Is it realistic?</strong> Yes. Also common.</p>
<p><strong>Is it worthwhile?</strong> For reporting and analysis, yes. For daily workflow, less so.</p>
<hr />
<h2>The "Happy Place" Compromise</h2>
<h3>Option A: Smart Templates</h3>
<p>Create Excel templates with:</p>
<ol>
<li>
<p><strong>Protected columns</strong> (can\'t edit, auto-filled)</p>
</li>
<li>
<p><strong>Drop-down validation</strong> (consistent data entry)</p>
</li>
<li>
<p><strong>Formula-driven fields</strong> (auto-calculations)</p>
</li>
<li>
<p><strong>Hidden metadata</strong> (case numbers, statuses, etc.)</p>
</li>
<li>
<p><strong>One-click upload</strong> (via macro or web integration)</p>
</li>
</ol>
<p><strong>Example: Call Log Template</strong></p>
<table>
<thead>
<tr>
<th>Case ID</th>
<th>Date</th>
<th>Time</th>
<th>Contact Name</th>
<th>Notes</th>
<th>Follow-Up Required</th>
<th>Follow-Up Date</th>
</tr>
</thead>
<tbody>
<tr>
<td>(drop-down)</td>
<td>(auto)</td>
<td>(auto)</td>
<td>(text)</td>
<td>(text)</td>
<td>(dropdown)</td>
<td>(date)</td>
</tr>
</tbody>
</table>
<p>When they save, the system knows: "This row belongs to case X, at this date/time, with these notes."</p>
<hr />
<h3>Option B: The "Excel Button"</h3>
<p>In the web interface, add a button:</p>
<blockquote>
<p><em>"Export to Excel"</em></p>
</blockquote>
<p>When clicked:</p>
<ol>
<li>The system exports the current view as an Excel file</li>
<li>The user works in Excel</li>
<li>The user clicks a button in Excel: "Upload Changes"</li>
<li>The system validates and updates</li>
</ol>
<p><strong>This is the "Excel as a front-end" approach.</strong></p>
<hr />
<h3>Option C: The "Excel Import" Feature</h3>
<p>A dedicated page in the system where users can:</p>
<ol>
<li>
<p>Download a template</p>
</li>
<li>
<p>Fill it out in Excel</p>
</li>
<li>
<p>Upload it back</p>
</li>
</ol>
<p>With clear error handling:</p>
<blockquote>
<p><em>"You have 3 errors: Row 4 is missing a Case ID. Row 7 has an invalid date format."</em></p>
</blockquote>
<hr />
<h2>What This Looks Like in Practice</h2>
<h3>For the Person Who Wants Excel</h3>
<table>
<thead>
<tr>
<th>Their Excel File</th>
<th>What Happens Behind the Scenes</th>
</tr>
</thead>
<tbody>
<tr>
<td>They fill out a row with a case ID and notes</td>
<td>System looks up the case, attaches the notes</td>
</tr>
<tr>
<td>They add a new row with contact info</td>
<td>System creates a new contact record</td>
</tr>
<tr>
<td>They mark a row as "Complete"</td>
<td>System updates the case status</td>
</tr>
<tr>
<td>They use a dropdown to select "Funding Approved"</td>
<td>System validates that the amount is within budget</td>
</tr>
</tbody>
</table>
<p><strong>They feel like they\'re just using Excel. The system handles the rest.</strong></p>
<hr />
<h2>What This Requires</h2>
<table>
<thead>
<tr>
<th>Requirement</th>
<th>Technical</th>
</tr>
</thead>
<tbody>
<tr>
<td>Template design</td>
<td>Define the columns, validation rules</td>
</tr>
<tr>
<td>Import engine</td>
<td>Parse, validate, and import Excel/CSV</td>
</tr>
<tr>
<td>User mapping</td>
<td>Connect Excel rows to system records</td>
</tr>
<tr>
<td>Error handling</td>
<td>Tell users what went wrong</td>
</tr>
<tr>
<td>Version control</td>
<td>Prevent overwriting data</td>
</tr>
</tbody>
</table>
<hr />
<h2>The Catch</h2>
<p><strong>Excel is not a database. It\'s not designed for concurrent use.</strong></p>
<table>
<thead>
<tr>
<th>What Excel Is For</th>
<th>What Excel Is Not For</th>
</tr>
</thead>
<tbody>
<tr>
<td>Personal analysis</td>
<td>Shared data management</td>
</tr>
<tr>
<td>Ad-hoc reporting</td>
<td>Real-time collaboration</td>
</tr>
<tr>
<td>One-off calculations</td>
<td>Multi-user workflows</td>
</tr>
<tr>
<td>Data exploration</td>
<td>Audit trails</td>
</tr>
<tr>
<td>Quick exports</td>
<td>Data integrity enforcement</td>
</tr>
</tbody>
</table>
<p><strong>If you build the Excel gateway, you must be clear about its limits.</strong></p>
<hr />
<h2>The "Throw Them a Bone" Proposal</h2>
<h3>Level 1: Export Only (Easiest)</h3>
<ul>
<li>
<p>Users can export data to Excel</p>
</li>
<li>
<p>They can do their analysis</p>
</li>
<li>
<p>They cannot push changes back</p>
</li>
</ul>
<p><strong>What they get:</strong> Familiar format for analysis<br />
<strong>What you get:</strong> No sync headaches</p>
<h3>Level 2: Template Import (Medium)</h3>
<ul>
<li>
<p>Users fill out a template</p>
</li>
<li>
<p>They upload it</p>
</li>
<li>
<p>System validates and imports</p>
</li>
</ul>
<p><strong>What they get:</strong> Familiar Excel-based data entry<br />
<strong>What you get:</strong> Structured, validated data</p>
<h3>Level 3: Two-Way Sync (Hardest)</h3>
<ul>
<li>
<p>Users export, edit, and upload</p>
</li>
<li>
<p>System merges changes intelligently</p>
</li>
</ul>
<p><strong>What they get:</strong> Full control in Excel<br />
<strong>What you get:</strong> Potential chaos if not handled carefully</p>
<hr />
<h2>My Recommendation</h2>
<p>Start with <strong>Level 2: Template Import</strong> for the highest-value, most-structured workflows (like communication logging or contract tracking). This meets Excel users where they are while keeping the system in control.</p>
<p><strong>Do not</strong> build two-way sync until you have clear use cases and strong validation rules.</p>
<hr />
<h2>The "Malicious Compliance" Risk (Addressed)</h2>
<p>You mentioned wanting to "set up a mock Excel system for this person to eat their words." I understand the impulse.</p>
<p><strong>Don\'t do it.</strong></p>
<p>Instead, offer Excel templates as a <em>legitimate</em> accommodation, not a trap. If someone insists on Excel, give them a well-designed template that feeds into the system. Let them see that the system is handling the complexity—so they don\'t have to.</p>
<p><strong>That\'s not malicious compliance. That\'s empathy with boundaries.</strong></p>
<hr />
<h2>Summary: Is It Worthwhile?</h2>
<table>
<thead>
<tr>
<th>Consideration</th>
<th>Assessment</th>
</tr>
</thead>
<tbody>
<tr>
<td>Is it possible?</td>
<td>Yes</td>
</tr>
<tr>
<td>Is it realistic?</td>
<td>Yes, with clear boundaries</td>
</tr>
<tr>
<td>Is it worthwhile?</td>
<td>For the right users, absolutely</td>
</tr>
<tr>
<td>Will it solve everything?</td>
<td>No. But it will reduce friction.</td>
</tr>
</tbody>
</table>
<hr />
<h2>The Soft Pitch</h2>
<p>When someone says "I want it to be more like Excel," you can say:</p>
<blockquote>
<p><em>"I hear you. Excel is familiar and comfortable. Here\'s what we can do: We\'ll build a template that you can fill out in Excel, and the system will import it automatically. You get to work in Excel, and the data ends up in the system where everyone can access it. Best of both worlds."</em></p>
</blockquote>
<p><strong>You\'re not forcing them to change. You\'re building a bridge.</strong></p>
<hr />
<h2>Final Thought</h2>
<blockquote>
<p><em>"I don\'t want to set up a mock Excel system for this person to eat their words. But emotionally I would like to."</em></p>
</blockquote>
<p><strong>That\'s a very human feeling. The professional response is to offer them a legitimate bridge—not to trap them, but to meet them where they are.</strong></p>
<p><strong>If they reject that, it\'s not your problem.</strong></p>',
);
