<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'feedback-meeting',
  'title' => 'Feedback Response Index',
  'category' => 'feedback-meeting',
  'category_name' => 'Coalition Feedback & Insights',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Feedback Response Index',
    'document_type' => 'Personal Reflection',
    'version' => '1.0',
    'last_updated' => '2026-08-06',
    'author' => 'April Chips',
    'audience' => 'Staff involved with ARCHR Platform',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '3',
    'tags' => 
    array (
      0 => 'tasks',
      1 => 'logs',
      2 => 'events',
      3 => 'documentation',
      4 => 'SOP',
    ),
  ),
  'source' => 'feedback-meeting\\index.md',
  'html' => '<p>For those I haven\'t met yet, my name is April. You can call me \'Chips\'.</p>
<p>I\'ve been working with the <abbr title="Asheville Regional Coalition for Home Repair">ARCHR</abbr> platform and alongside Ben Wyatt for about three months, primarily on the Airtable system and the long-term overhaul of how we manage home repair cases.</p>
<p>This is a very complex role working with a great team of people who care a bunch about making things better in the world. The people on this team and coalition have varying experiences with technology, computers, and digital workflows. </p>
<p>Everyone has different needs for their job, technical comfort, and fulfillment of home repairs for the families we are helping.</p>
<p>If this is done right, and things are made simple and easy, no one will notice the complexity. It\'s when things go wrong that they do. </p>
<p>Most people who drive want to have a car that turns on and goes vroom when you hit the gas pedal. They don\'t want to understand how to fix a transmission. We pay people to engage with complexity, so we don\'t have to.</p>
<p>The difference is that none of us fully know what the end result will look like. There is not a blueprint or manual for how a Disaster Home Repair Coalition looks like. We are creating that together, each day. </p>
<p>Here is an index of short text documents that I put together for anyone who is interested in the development of our shared digital platform. I don\'t expect anyone to read these. But they are here if you do. </p>
<p>Written for humans, not for robots.</p>
<h3>Getting Started</h3>
<ul>
<li><a href="state-of-the-union.md">State of the Union</a></li>
<li><a href="first-100-days.md">My First Hundred Days</a></li>
<li><a href="good-feedback.md">Collecting Good Feedback</a></li>
</ul>
<h3>Responding to Pain Points</h3>
<ul>
<li><a href="help.php?doc=meeting-notes">August ARCHR Coalition Feedback Meeting Notes</a></li>
<li><a href="pain-point-responses.md">Pain Point Responses</a></li>
<li><a href="airtable-trainings.md">Airtable Training Proposal</a></li>
<li><a href="project-timeline.md">Project Timeline</a></li>
</ul>
<h3>Building the Front-End Interface</h3>
<ul>
<li>
</li>
<li>
</li>
<li>
</li>
</ul>
<h3>In the Pipeline Right Now</h3>
<ul>
<li><a href="doc-library.md">Building a Documentation and Support Library</a> - This is where you are viewing right now. </li>
<li><a href="airtable-v-postgres.md">Airtable Vs PostgreSQL</a></li>
<li><a href="open-source-home-repairs.md">Open Source Home Repair Coalition Software</a></li>
<li>
</li>
</ul>
<h3>Personal Responses</h3>
<ul>
<li><a href="help.php?doc=database-not-problem-explained">Airtable isn\'t the actual issue, the Front-End on Softr is.</a></li>
<li><a href="excel-behaviors.md">"It should just behave more like Excel"</a></li>
<li><a href="help.php?doc=frontend-failure">The Front-End on Softr is our Failed Space.</a></li>
<li><a href="help.php?doc=money-trail">The Money Trail -- How Do We Track Financial Metrics for Quarterly Reporting and Case Management?</a></li>
</ul>
<h3>Helpful things to Self-Educate On</h3>
<ul>
<li><a href="frontend-v-backend.md">What does Front-End and Back-End mean?</a></li>
<li>
</li>
</ul>
<h3>Call for Follow-Up Interviews</h3>
<p>Participation and engagement make this work possible. Whether that is home repairs, or building a front-end for everyone. If you or someone on your team wants to meet about involvement in the design and development process, please get in contact with me.</p>
<p>This role isn\'t just about front end development. It\'s about stewarding trust. My job is to listen, reflect, and guide. Coding is secondary. With understanding, comes action. This is the beginning of a process that we are all part of.</p>
<h2>Next Steps</h2>
<ol>
<li><strong>Monthly Development Meetings</strong> — We hold monthly platform development meetings for anyone who wants to be more involved.</li>
<li><strong>Communication</strong> — I\'ll send regular updates on progress, changes, and training opportunities.</li>
<li><strong>Feedback Channels</strong> — You can always reach me at april@aachips.co with questions or concerns.</li>
</ol>
<p>Thank you for your time and for the important work you do.
April Chips</p>',
);
