<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'form-submission-journey',
  'title' => 'Form Submission Journey — Security & Data Flow',
  'category' => 'platform-anatomy',
  'category_name' => 'Platform Anatomy',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Form Submission Journey — Security & Data Flow',
    'document_type' => 'Technical Reference',
    'version' => '1.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'Developers, Admins',
    'complexity_level' => 'Advanced',
    'estimated_reading_minutes' => '20',
    'tags' => 
    array (
      0 => 'security',
      1 => 'intake',
      2 => 'data-flow',
      3 => 'submission',
    ),
    'visibility' => 
    array (
      0 => 'admin',
      1 => 'super-admin',
    ),
  ),
  'source' => 'platform-anatomy\\form-submission-journey.md',
  'html' => '<p>┌─────────────────────────────────────────────────────────────────────────────┐
│                    APPLICATION SUBMISSION SECURITY FLOW                      │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│  USER SUBMITS FORM                                                          │
│       │                                                                     │
│       ▼                                                                     │
│  ┌─────────────────────────────────────────────────────────────────────┐   │
│  │  LAYER 1: TRANSPORT SECURITY (TLS 1.3)                              │   │
│  │  • All data encrypted between browser and server                    │   │
│  │  • HSTS enforced for all requests                                   │   │
│  │  • Perfect Forward Secrecy enabled                                  │   │
│  └─────────────────────────────────────────────────────────────────────┘   │
│       │                                                                     │
│       ▼                                                                     │
│  ┌─────────────────────────────────────────────────────────────────────┐   │
│  │  LAYER 2: INPUT VALIDATION &amp; SANITIZATION                           │   │
│  │  • All form fields validated against schema                         │   │
│  │  • HTML/script tags stripped from text inputs                       │   │
│  │  • Email addresses normalized                                        │   │
│  │  • Phone numbers standardized to E.164 format                       │   │
│  │  • File uploads scanned for malware                                 │   │
│  └─────────────────────────────────────────────────────────────────────┘   │
│       │                                                                     │
│       ▼                                                                     │
│  ┌─────────────────────────────────────────────────────────────────────┐   │
│  │  LAYER 3: DATABASE ENCRYPTION (AES-256)                             │   │
│  │  • PII fields encrypted at rest (name, address, DOB, SSN if any)    │   │
│  │  • Encryption keys stored in separate KMS (AWS KMS / HashiCorp)     │   │
│  │  • Database connections use TLS                                     │   │
│  │  • Automated backups also encrypted                                 │   │
│  └─────────────────────────────────────────────────────────────────────┘   │
│       │                                                                     │
│       ▼                                                                     │
│  ┌─────────────────────────────────────────────────────────────────────┐   │
│  │  LAYER 4: ACCESS CONTROLS                                           │   │
│  │  • Row-level security: users see only their organization\'s data     │   │
│  │  • Column-level security: sensitive fields redacted by default      │   │
│  │  • Audit logging: every access is recorded                          │   │
│  │  • Session timeout: 30 minutes of inactivity                        │   │
│  └─────────────────────────────────────────────────────────────────────┘   │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘</p>
<h3>Data Classification &amp; Protection Levels</h3>
<table>
<thead>
<tr>
<th>Data Category</th>
<th>Examples</th>
<th>Encryption</th>
<th>Access Restriction</th>
<th>Retention</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>PII (Personally Identifiable)</strong></td>
<td>Name, address, phone, email, DOB</td>
<td>AES-256 at rest</td>
<td>Caseworker + assigned org only</td>
<td>7 years post-case</td>
</tr>
<tr>
<td><strong>Financial</strong></td>
<td>Income, bank statements, tax docs</td>
<td>AES-256 + column-level</td>
<td>Caseworker + Bursar + assigned org</td>
<td>7 years</td>
</tr>
<tr>
<td><strong>Medical/Disability</strong></td>
<td>Health conditions, accessibility needs</td>
<td>AES-256 + restricted</td>
<td>Caseworker only (with consent)</td>
<td>3 years post-case</td>
</tr>
<tr>
<td><strong>Property</strong></td>
<td>Photos, assessments, repair estimates</td>
<td>AES-256</td>
<td>All assigned staff</td>
<td>Permanent</td>
</tr>
<tr>
<td><strong>Communications</strong></td>
<td>Messages, call logs, emails</td>
<td>AES-256</td>
<td>All assigned staff + requestor</td>
<td>3 years</td>
</tr>
<tr>
<td><strong>Authentication</strong></td>
<td>Passwords, tokens</td>
<td>bcrypt (salt rounds=12)</td>
<td>System only</td>
<td>Until account deletion</td>
</tr>
</tbody>
</table>
<h3>Who Sees What Information?</h3>
<p>text</p>
<p>┌─────────────────────────────────────────────────────────────────────────────┐
│                    INFORMATION ACCESS MATRIX                                 │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│  INFORMATION TYPE          │  REQUESTOR  │  CASEWORKER  │  ADMIN(ORG)      │
│────────────────────────────┼─────────────┼──────────────┼──────────────────│
│  Their own application     │    ✓ Full   │    ✓ Full    │    ✓ Full        │
│  Other applications        │    ✗        │    ✗         │    ✓ (org only)  │
│  PII of other applicants   │    ✗        │    ✗         │    ✓ (org only)  │
│  Financial verification    │    ✓        │    ✓         │    ✓             │
│  Internal notes            │    ✗        │    ✓         │    ✓             │
│  Cross-org communications  │    ✗        │    ✗         │    ✗             │
│  System audit logs         │    ✗        │    ✗         │    ✗ (superadmin)│
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘</p>
<h3>Data Hygiene Checklist (Post-Submission)</h3>
<p>markdown</p>
<h2>Immediate (0-5 minutes after submission)</h2>
<ul>
<li>[ ] PII fields encrypted before writing to database</li>
<li>[ ] IP address logged for audit trail (not stored with PII)</li>
<li>[ ] File attachments scanned for malware</li>
<li>[ ] Email notification sent to requestor (no PII in email body)</li>
<li>[ ] Application added to review queue (encrypted reference only)<h2>Within 24 Hours</h2>
</li>
<li>[ ] Automated eligibility check completed</li>
<li>[ ] No disqualifying factors found (or flagged)</li>
<li>[ ] Assigned to appropriate organization (based on match score)</li>
<li>[ ] Caseworker notified via secure dashboard (not email with PII)<h2>Within 7 Days</h2>
</li>
<li>[ ] Initial review completed by assigned caseworker</li>
<li>[ ] Any missing documentation flagged</li>
<li>[ ] Requestor notified of next steps</li>
<li>[ ] Internal notes added (staff-only, encrypted)<h2>Data Retention &amp; Deletion</h2>
</li>
<li>[ ] Case closed: data retained for 7 years per grant requirements</li>
<li>[ ] Requestor deletion request: anonymize PII, retain metrics</li>
<li>[ ] 7-year mark: automated archival to cold storage</li>
<li>[ ] 10-year mark: permanent deletion (unless legal hold)</li>
</ul>
<h3>Security Incident Response Protocol</h3>
<p>markdown</p>
<h2>If You Suspect a Data Exposure</h2>
<ol>
<li><strong>DO NOT</strong> delete logs or modify the data</li>
<li><strong>DO NOT</strong> discuss in public channels</li>
<li><strong>IMMEDIATELY</strong> contact: security@archr.org</li>
<li><strong>DOCUMENT</strong> what you saw, when, and how<h2>What Happens Next</h2>
</li>
</ol>
<ul>
<li>Security team investigates within 1 hour</li>
<li>Affected data identified and isolated</li>
<li>Access logs reviewed</li>
<li>If breach confirmed: affected parties notified within 72 hours</li>
<li>Root cause analysis and remediation plan<h2>Reportable Incidents Include</h2>
</li>
<li>Unauthorized login to dashboard</li>
<li>Email sent to wrong recipient with PII</li>
<li>Lost or stolen device with access</li>
<li>Suspicious database queries</li>
<li>Unknown user added to organization</li>
</ul>
<hr />
<h2>Part 2: Organization Administrator Dashboard Guide</h2>
<h3>Role Definition</h3>
<p><strong>Organization Administrator</strong> manages a specific partner organization within the ARCHR coalition (e.g., Habitat for Humanity - Buncombe County). This is <strong>not</strong> a platform super administrator.</p>
<p><strong>Primary Responsibilities:</strong></p>
<ul>
<li>
<p>Oversee applications assigned to their organization</p>
</li>
<li>
<p>Manage caseworker assignments and workload</p>
</li>
<li>
<p>Review and approve eligibility determinations</p>
</li>
<li>
<p>Coordinate with subcontractors and volunteers</p>
</li>
<li>
<p>Ensure timely processing of repairs</p>
</li>
</ul>
<h3>Dashboard Overview</h3>
<p>text</p>
<p>┌─────────────────────────────────────────────────────────────────────────────┐
│                    ORGANIZATION ADMIN DASHBOARD                              │
│                                                                             │
│  ┌─────────────────────────────────────────────────────────────────────┐   │
│  │  ORG HEADER                                                          │   │
│  │  Habitat for Humanity - Buncombe County │ 12 active applications    │   │
│  └─────────────────────────────────────────────────────────────────────┘   │
│                                                                             │
│  ┌──────────────┐ ┌──────────────┐ ┌──────────────┐ ┌──────────────┐       │
│  │ PROCESSING   │ │VERIFICATION  │ │COMMUNICATION │ │ SCHEDULING   │       │
│  │      8       │ │      4       │ │     12       │ │      3       │       │
│  │  [Process]   │ │  [Verify]    │ │   [Comms]    │ │  [Schedule]  │       │
│  └──────────────┘ └──────────────┘ └──────────────┘ └──────────────┘       │
│                                                                             │
│  ┌─────────────────────────────────────────────────────────────────────┐   │
│  │  RECENT APPLICATIONS                                                 │   │
│  │  ┌─────────────────────────────────────────────────────────────┐    │   │
│  │  │ ARCHR-2024-001234 │ John Henderson │ Next: Upload income    │    │   │
│  │  │ ARCHR-2024-001189 │ Sarah Williams │ Next: Schedule assess  │    │   │
│  │  │ ARCHR-2024-001103 │ James Thornton │ Next: Contract review  │    │   │
│  │  └─────────────────────────────────────────────────────────────┘    │   │
│  └─────────────────────────────────────────────────────────────────────┘   │
│                                                                             │
│  ┌──────────────────────────────┐  ┌──────────────────────────────────┐   │
│  │  LATEST EVENTS               │  │  LATEST MESSAGES                 │   │
│  │  • Income docs uploaded      │  │  • John: "I uploaded docs"       │   │
│  │  • Eligibility confirmed     │  │  • Sarah: "Reschedule?"          │   │
│  │  • Assessment scheduled      │  │  • System: "New subcontractor"   │   │
│  └──────────────────────────────┘  └──────────────────────────────────┘   │
│                                                                             │
│  ┌─────────────────────────────────────────────────────────────────────┐   │
│  │  ACTION BUTTONS                                                     │   │
│  │  [Continue] [Process] [Verify] [Comms] [Schedule] [Alerts] [Msg]   │   │
│  └─────────────────────────────────────────────────────────────────────┘   │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘</p>
<h3>Administrator Task Reference</h3>
<h4>Task Metric Cards</h4>
<table>
<thead>
<tr>
<th>Metric Card</th>
<th>What It Counts</th>
<th>Clicking Opens</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Processing Tasks</strong></td>
<td>Applications in review, eligibility pending, assessment scheduled</td>
<td><code>/processList</code> - queue of applications needing action</td>
</tr>
<tr>
<td><strong>Verification Tasks</strong></td>
<td>Documents awaiting review, income verification, contractor quotes</td>
<td><code>/verifyList</code> - documents pending authentication</td>
</tr>
<tr>
<td><strong>Communication Tasks</strong></td>
<td>Unread messages, pending responses, client follow-ups</td>
<td><code>/commsDashboard</code> - all organization communications</td>
</tr>
<tr>
<td><strong>Scheduling Tasks</strong></td>
<td>Assessment appointments, contractor visits, volunteer shifts</td>
<td><code>/schedulingDashboard</code> - calendar and scheduling</td>
</tr>
</tbody>
</table>
<h4>Seven Action Buttons</h4>
<table>
<thead>
<tr>
<th>Button</th>
<th>Destination</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Continue</strong></td>
<td><code>/appDetails</code></td>
<td>Resume working on most recent application</td>
</tr>
<tr>
<td><strong>Process</strong></td>
<td><code>/processList</code></td>
<td>Review and process queued applications</td>
</tr>
<tr>
<td><strong>Verify</strong></td>
<td><code>/verifyList</code></td>
<td>Authenticate submitted documents</td>
</tr>
<tr>
<td><strong>Comms</strong></td>
<td><code>/commsDashboard</code></td>
<td>Manage all communications</td>
</tr>
<tr>
<td><strong>Schedule</strong></td>
<td><code>/schedulingDashboard</code></td>
<td>Calendar and appointment management</td>
</tr>
<tr>
<td><strong>Alerts</strong></td>
<td><code>/appAlerts</code></td>
<td>View system notifications and flags</td>
</tr>
<tr>
<td><strong>Message Details</strong></td>
<td><code>/messageDetails</code></td>
<td>Deep dive into specific conversation</td>
</tr>
</tbody>
</table>
<hr />
<h3>Admin Task Context Groups</h3>
<h4>Group 1: Requestors</h4>
<p>text</p>
<p>┌─────────────────────────────────────────────────────────────────────────────┐
│  REQUESTORS TASK GROUP                                                       │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│  APPLICATION REVIEW              │  REQUESTOR ACTIONS                       │
│  ┌─────────────────────────────┐ │  ┌─────────────────────────────────────┐ │
│  │ • Review &amp; confirm          │ │  │ • View Communication                │ │
│  │   eligibility               │ │  │ • Schedule Assessment               │ │
│  │ • Set Request Triage        │ │  │                                     │ │
│  │ • Update Information        │ │  │                                     │ │
│  │ • Take Notes                │ │  │                                     │ │
│  └─────────────────────────────┘ │  └─────────────────────────────────────┘ │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘</p>
<table>
<thead>
<tr>
<th>Task</th>
<th>Description</th>
<th>Typical Duration</th>
<th>Permissions Required</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Review &amp; confirm eligibility</strong></td>
<td>Verify applicant meets program criteria (income, location, homeownership)</td>
<td>5-10 min</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td><strong>Set Request Triage</strong></td>
<td>Assign priority level based on urgency (1=emergency, 5=routine)</td>
<td>2-5 min</td>
<td>Admin</td>
</tr>
<tr>
<td><strong>Update Information</strong></td>
<td>Correct or supplement applicant data</td>
<td>3-8 min</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td><strong>Take Notes</strong></td>
<td>Add internal notes visible only to organization staff</td>
<td>2-5 min</td>
<td>All org staff</td>
</tr>
<tr>
<td><strong>View Communication</strong></td>
<td>Read message history between requestor and staff</td>
<td>Varies</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td><strong>Schedule Assessment</strong></td>
<td>Set date/time for property inspection</td>
<td>5-10 min</td>
<td>Admin, Assessor</td>
</tr>
</tbody>
</table>
<h4>Group 2: Organization</h4>
<p>text</p>
<p>┌─────────────────────────────────────────────────────────────────────────────┐
│  ORGANIZATION TASK GROUP                                                     │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│  COALITION &amp; INTERNAL                    │                                  │
│  ┌─────────────────────────────────────┐ │                                  │
│  │ • View Communication                │ │                                  │
│  │ • Schedule Coalition Events         │ │                                  │
│  └─────────────────────────────────────┘ │                                  │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘</p>
<table>
<thead>
<tr>
<th>Task</th>
<th>Description</th>
<th>Typical Duration</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>View Communication</strong></td>
<td>Internal organization messages, coalition announcements</td>
<td>Varies</td>
</tr>
<tr>
<td><strong>Schedule Coalition Events</strong></td>
<td>Cross-org meetings, trainings, reporting deadlines</td>
<td>10-20 min</td>
</tr>
</tbody>
</table>
<h4>Group 3: Subcontractors</h4>
<p>text</p>
<p>┌─────────────────────────────────────────────────────────────────────────────┐
│  SUBCONTRACTORS TASK GROUP                                                   │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│  SUBCONTRACTOR MANAGEMENT                                                   │
│  ┌─────────────────────────────────────────────────────────────────────┐   │
│  │ • Review New Subcontractor    │ Review applications from trades    │   │
│  │ • View Communication          │ Message history with subcontractor  │   │
│  │ • Schedule Subcontractor Quote│ Arrange for bid on specific repair  │   │
│  │ • Attach Quotes &amp; Invoices    │ Upload and categorize documents    │   │
│  └─────────────────────────────────────────────────────────────────────┘   │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘</p>
<table>
<thead>
<tr>
<th>Task</th>
<th>Description</th>
<th>Typical Duration</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Review New Subcontractor</strong></td>
<td>Vet new trade specialist applications (licensing, insurance, background)</td>
<td>15-30 min</td>
</tr>
<tr>
<td><strong>View Communication</strong></td>
<td>Review message thread with subcontractor</td>
<td>Varies</td>
</tr>
<tr>
<td><strong>Schedule Subcontractor Quote</strong></td>
<td>Coordinate site visit for estimate</td>
<td>10-15 min</td>
</tr>
<tr>
<td><strong>Attach Quotes &amp; Invoices</strong></td>
<td>Upload bid documents or payment requests</td>
<td>5-10 min</td>
</tr>
</tbody>
</table>
<h4>Group 4: Volunteers</h4>
<p>text</p>
<p>┌─────────────────────────────────────────────────────────────────────────────┐
│  VOLUNTEERS TASK GROUP                                                       │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│  VOLUNTEER COORDINATION                                                     │
│  ┌─────────────────────────────────────────────────────────────────────┐   │
│  │ • Manage Volunteer Communication    │ Messages, announcements       │   │
│  │ • Schedule Volunteers               │ Shift assignments, task lists │   │
│  └─────────────────────────────────────────────────────────────────────┘   │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘</p>
<table>
<thead>
<tr>
<th>Task</th>
<th>Description</th>
<th>Typical Duration</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Manage Volunteer Communication</strong></td>
<td>Send updates, respond to questions, broadcast needs</td>
<td>10-20 min daily</td>
</tr>
<tr>
<td><strong>Schedule Volunteers</strong></td>
<td>Assign shifts, track availability, send reminders</td>
<td>15-30 min</td>
</tr>
</tbody>
</table>
<hr />
<h3>Application Status Definitions (for Admin Use)</h3>
<table>
<thead>
<tr>
<th>Status</th>
<th>Meaning</th>
<th>Admin Actions Available</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Pending Review</strong></td>
<td>New submission, not yet assigned</td>
<td>Review eligibility, assign to caseworker</td>
</tr>
<tr>
<td><strong>Eligibility Review</strong></td>
<td>Being checked against criteria</td>
<td>Confirm/deny eligibility, request more info</td>
</tr>
<tr>
<td><strong>Assessment Scheduled</strong></td>
<td>Home visit appointment set</td>
<td>Reschedule, assign assessor, add notes</td>
</tr>
<tr>
<td><strong>Assessment Complete</strong></td>
<td>Estimate created</td>
<td>Review estimate, approve budget</td>
</tr>
<tr>
<td><strong>Contract Pending</strong></td>
<td>Waiting for applicant signature</td>
<td>Resend contract, contact applicant</td>
</tr>
<tr>
<td><strong>Work In Progress</strong></td>
<td>Repair work underway</td>
<td>Monitor progress, approve change orders</td>
</tr>
<tr>
<td><strong>Quality Check</strong></td>
<td>Final inspection needed</td>
<td>Schedule inspection, assign crew lead</td>
</tr>
<tr>
<td><strong>Completed</strong></td>
<td>All work finished, signed off</td>
<td>Close case, archive documents</td>
</tr>
<tr>
<td><strong>Denied</strong></td>
<td>Applicant ineligible</td>
<td>Record reason, notify applicant</td>
</tr>
<tr>
<td><strong>On Hold</strong></td>
<td>Temporary pause</td>
<td>Document reason, set review date</td>
</tr>
</tbody>
</table>
<hr />
<h3>Quick Reference: Admin Dashboard Elements</h3>
<p>markdown</p>
<h2>Dashboard Components at a Glance</h2>
<table>
<thead>
<tr>
<th>Element</th>
<th>What It Shows</th>
<th>When to Use</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Org Header</strong></td>
<td>Organization name + active count</td>
<td>Always visible</td>
</tr>
<tr>
<td><strong>Task Metrics</strong></td>
<td>4 category counts (Process/Verify/Comms/Schedule)</td>
<td>Morning standup</td>
</tr>
<tr>
<td><strong>Recent Applications</strong></td>
<td>Last 5-10 apps with nextStep + holdingOn</td>
<td>Throughout day</td>
</tr>
<tr>
<td><strong>Latest Events</strong></td>
<td>Recent timeline entries</td>
<td>Track progress</td>
</tr>
<tr>
<td><strong>Latest Messages</strong></td>
<td>Recent communications</td>
<td>Respond promptly</td>
</tr>
<tr>
<td><strong>7 Action Buttons</strong></td>
<td>Quick navigation to task lists</td>
<td>Daily workflow</td>
</tr>
<tr>
<td><strong>Task Groups</strong></td>
<td>Collapsible context menus</td>
<td>When specific task arises</td>
</tr>
</tbody>
</table>
<hr />
<h3>Common Administrator Workflows</h3>
<h4>Workflow 1: New Application Arrives</h4>
<h4>Workflow 2: Document Verification</h4>
<h4>Workflow 3: Weekly Oversight</h4>
<p>markdown</p>
<p><strong>Monday Morning Checklist</strong></p>
<ol>
<li>Review Task Metrics<ul>
<li>[ ] Processing tasks: any stuck &gt;5 days?</li>
<li>[ ] Verification tasks: oldest pending?</li>
<li>[ ] Communication tasks: any urgent?</li>
<li>[ ] Scheduling tasks: upcoming appointments?</li>
</ul>
</li>
<li>Scan Recent Applications<ul>
<li>[ ] Any with expiring nextStep dates?</li>
<li>[ ] Any holdingOn messages needing attention?</li>
</ul>
</li>
<li>Check Latest Events<ul>
<li>[ ] Any completed assessments ready for review?</li>
<li>[ ] Any contracts signed?</li>
</ul>
</li>
<li>Review Messages<ul>
<li>[ ] Respond to any &gt;24 hours old</li>
<li>[ ] Flag any requiring escalation</li>
</ul>
</li>
<li>Task Groups<ul>
<li>[ ] Any new subcontractor applications?</li>
<li>[ ] Volunteer scheduling needs?</li>
</ul>
</li>
</ol>
<hr />
<h3>Security Reminders for Admins</h3>
<p>markdown</p>
<h2>DO</h2>
<ul>
<li>Log out when leaving your workstation</li>
<li>Use organization-provided devices when possible</li>
<li>Report suspicious activity immediately</li>
<li>Lock screen when away from desk</li>
<li>Use strong, unique password (password manager encouraged)<h2>DON\'T</h2>
</li>
<li>Share login credentials with anyone</li>
<li>Discuss case details in public spaces</li>
<li>Email PII to external addresses</li>
<li>Download sensitive data to personal devices</li>
<li>Leave paperwork with client information visible</li>
</ul>
<hr />
<h2>Part 3: Process Documentation Index</h2>
<h3>Related SOP Documents</h3>
<table>
<thead>
<tr>
<th>Document</th>
<th>Description</th>
<th>Location</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>REQUESTOR_PORTAL_SOP_v1</code></td>
<td>Applicant dashboard, communication protocol</td>
<td><code>/docs/sops/</code></td>
</tr>
<tr>
<td><code>VOLUNTEER_EXPERIENCE_SOP_v1</code></td>
<td>Quest system, gamification, hour tracking</td>
<td><code>/docs/sops/</code></td>
</tr>
<tr>
<td><code>APPLICATION_SUBMISSION_WORKFLOW_v1</code></td>
<td>Intake, eligibility, anchor registration</td>
<td><code>/docs/technical/</code></td>
</tr>
<tr>
<td><code>DATA_RETENTION_POLICY_v1</code></td>
<td>7-year retention schedule, deletion protocols</td>
<td><code>/docs/compliance/</code></td>
</tr>
<tr>
<td><code>INCIDENT_RESPONSE_PLAN_v1</code></td>
<td>Security breach response</td>
<td><code>/docs/security/</code></td>
</tr>
</tbody>
</table>
<hr />
<h3>Document Metadata Template for New SOPs</h3>
<p>yaml</p>
<hr />
<h2>document_name: DOCUMENT_NAME_HERE
document_type: Standard Operating Procedure | Technical Specification | Policy
version: 1.0
last_updated: YYYY-MM-DD
author: Name
contributors: Name1, Name2
status: Draft | Review | Approved | Archived
review_date: YYYY-MM-DD
audience: Requestors | Caseworkers | Admins | All Staff
complexity_level: Beginner | Intermediate | Advanced
estimated_reading_minutes: XX
tags: [tag1, tag2, tag3]</h2>
<hr />
<p>This documentation should be maintained alongside the code. When features change, update these documents first - they\'re the source of truth for the whole team.</p>',
);
