<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'frontend-failure',
  'title' => 'Frontend vs Backend — What\'s Really Broken',
  'category' => 'feedback-meeting',
  'category_name' => 'Coalition Feedback & Insights',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Frontend vs Backend — What\'s Really Broken',
    'document_type' => 'Explanatory Guide',
    'version' => '1.0',
    'last_updated' => '2026-08-06',
    'author' => 'ARCHR Development Team',
    'audience' => 'All Platform Users, Non-Technical Readers',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '6',
    'tags' => 
    array (
      0 => 'frontend',
      1 => 'backend',
      2 => 'airtable',
      3 => 'explanation',
    ),
  ),
  'source' => 'feedback-meeting\\frontend-failure.md',
  'html' => '<p>You might hear the terms Front End and Back End, and may not know the distinction between the two fully. This is a primer and framework for explaining what is wrong. </p>
<p>Many of the issues raised with the current platform were directed at Airtable, but those issues were issues with the front-end. </p>
<p>Airtable is our database. Databases are organized for efficiency, to be read by machines, and for retrieval processes.</p>
<p>If you go to a store, and you have to, as a customer, go to the stock room in the back to find what you are looking for.that\'s not a problem with the stock room. That\'s a problem with the store layout. The stock room is organized for efficiency, not for shopping. Customers shouldn\'t be in the back room.</p>
<p>The Stock Room is the Database in this metaphor. A stock room is organized for staff, while a database is organized for machines. Those staff are often trained in how to navigate the stock room so it is not confusing or time consuming to do tasks. Customers don\'t go to the stock room. Databases store information. They have confusing coded labels. If you are not trained to interpret that information, it will be incredibly confusing.</p>
<p>The failure on part of the Airtable, or our database, is that we haven\'t offered a training in how to use it. But if we had a working front-end to retrieve and display that information as we need it, than nobody would have to go on Airtable to find what they need to do their jobs. </p>
<p>Everyone is shopping in the back room.</p>
<h3>Survivorship Bias and WWII Fighter Planes</h3>
<p>"We are in the year 1943 and American Bombers are suffering lots of losses by the German counter-air defense. The military needed to minimize the losses and they ask for the help of the SRG at Columbia University, where works a Jewish Austrian-Hungarian refugee.</p>
<p>His name is Abraham Wald and the task of finding a solution on the armoring of the planes is his duty. He is given a lot of data on the aircraft damage, including the location of the damage suffered by the planes that were hit by the Nazis.</p>
<p>Press enter or click to view image in full size</p>
<p><img src="https://miro.medium.com/v2/resize:fit:700/1*FD_DTgmZQpscjhzmNWmJ2Q.png" alt="" /></p>
<p>Location of the hits in the aircraft. <a href="https://commons.wikimedia.org/wiki/File:Survivorship-bias.png">McGeddon</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>, via Wikimedia Commons</p>
<p>The military expected Wald to give them some suggestions on how to reinforce the spots of the planes that received the most hits by the German defenses.</p>
<p>“Wait,” said Wald, “What you should do is reinforce the area around the motors and the cockpit. You should remember that the worst-hit planes never come back. All the data we have come from planes that make it to the bases. You don’t see that the spots with no damage are the worst places to be hit because these planes never come back.”</p>
<p>This intuition is absolutely true, and it is called survivorship bias. The planes that were hit in the area of the motor, of the ones that lost their pilots never came back and were not part of the data. This is why the military had to concentrate on reinforcing exactly those areas.""</p>
<p><a href="https://www.cantorsparadise.com/survivorship-bias-and-the-mathematician-who-helped-win-wwii-356b174defa6">https://www.cantorsparadise.com/survivorship-bias-and-the-mathematician-who-helped-win-wwii-356b174defa6</a></p>
<p>Engineers looked at damaged planes from war. They saw where all the artillery holes were and thought, "these are the weak spots." But the planes that didn\'t return were hit elsewhere. The real weak spots were misidentified and not visible to the conventional analysis. </p>
<p>Users look at confusing database fields, they think that the database is the problem. the confusing fields are supposed to be confusing. The real issue is and has been for some time the front end, which isn\'t a visible target for scrutiny because it doesn\'t exist.</p>
<p>The database is not the problem. The lack of a proper interface is.</p>
<h2>Why This Matters</h2>
<h3>What Users Think Is Wrong</h3>
<blockquote>
<p><em>"The database is confusing."</em><br />
<em>"There are too many coded fields."</em><br />
<em>"I can\'t find what I need."</em></p>
</blockquote>
<h3>What Is Actually Wrong</h3>
<blockquote>
<p><em>"There is no front-end interface that translates database fields into meaningful labels."</em><br />
<em>"Users are being asked to navigate the database directly."</em><br />
<em>"Softr is not providing enough abstraction."</em></p>
</blockquote>
<hr />
<h2>The Softr Problem</h2>
<p>Softr is a front-end builder, but it\'s limited. It\'s great for simple views, but it doesn\'t provide the kind of abstraction that a proper application would.</p>
<table>
<thead>
<tr>
<th>What Softr Can Do</th>
<th>What It Can\'t Do</th>
</tr>
</thead>
<tbody>
<tr>
<td>Display records</td>
<td>Create complex workflows</td>
</tr>
<tr>
<td>Simple filters</td>
<td>Abstract database complexity</td>
</tr>
<tr>
<td>Basic forms</td>
<td>Guide users through processes</td>
</tr>
<tr>
<td>Read data</td>
<td>Hide database structure</td>
</tr>
</tbody>
</table>
<p><strong>Users are seeing the database layer because Softr isn\'t abstracting it away.</strong></p>
<hr />
<h2>The Front-End Layer You\'re Building</h2>
<p>The app prototype you\'re building addresses exactly this:</p>
<table>
<thead>
<tr>
<th>Database Layer (Airtable)</th>
<th>Front-End Layer (Your App)</th>
</tr>
</thead>
<tbody>
<tr>
<td>"case_id"</td>
<td>"Case Number"</td>
</tr>
<tr>
<td>"app_first_name"</td>
<td>"First Name"</td>
</tr>
<tr>
<td>"app_last_name"</td>
<td>"Last Name"</td>
</tr>
<tr>
<td>"funding_approved"</td>
<td>"Approved Funding"</td>
</tr>
<tr>
<td>"funding_remaining"</td>
<td>"Remaining Budget"</td>
</tr>
<tr>
<td>The user sees codes</td>
<td>The user sees labels</td>
</tr>
<tr>
<td>The user navigates tables</td>
<td>The user navigates workflows</td>
</tr>
<tr>
<td>The user needs training</td>
<td>The user learns intuitively</td>
</tr>
</tbody>
</table>
<p><strong>Your app is building the store so people don\'t have to shop in the back room.</strong></p>
<hr />
<h2>How To Explain This To Frustrated People</h2>
<h3>The Short Version</h3>
<blockquote>
<p><em>"A lot of what\'s confusing about the current system isn\'t Airtable\'s fault. It\'s the front-end\'s fault. You\'re being asked to navigate a database directly, instead of through a guided interface. That\'s like making you shop in the stock room instead of the store."</em></p>
</blockquote>
<h3>The Analogy Version</h3>
<blockquote>
<p><em>"Imagine going to a grocery store where they don\'t have aisles or signs. You have to go into the back room and look through boxes labeled \'SKU-4892-B\' to find your groceries. That\'s not a problem with the boxes—it\'s a problem with the store design.</em></p>
<p><em>The database is the back room. It\'s organized for efficiency, not for shopping. The front-end is the store. Right now, we\'ve been asking everyone to shop in the back room, and that\'s where the frustration comes from."</em></p>
</blockquote>
<h3>The Technical Version</h3>
<blockquote>
<p>_"Airtable is the data layer. Softr is the front-end layer. Softr isn\'t abstracting the database structure well enough, so users are seeing fields like \'app_first<em>name\' instead of \'First Name.\' The app we\'re building adds a proper front-end layer so users interact with labels and workflows, not tables and codes."</em></p>
</blockquote>
<hr />
<h2>The Kicker: "I Don\'t Know How to Explain This to People in Pain"</h2>
<p>You\'re right—frustrated people aren\'t looking for a systems architecture lesson. They\'re looking for relief. So don\'t explain it. <strong>Show it.</strong></p>
<h3>The Demonstration</h3>
<blockquote>
<p>_"Here\'s what I\'m building. See how it says \'Case Number\' instead of \'case<em>id\'? See how you can click \'View Funding\' and see the approved amount, spent amount, and remaining balance in one place? That\'s what we\'re moving toward. The database is still the database—but you won\'t see it. You\'ll see a system designed for you."</em></p>
</blockquote>
<h3>The Promise</h3>
<blockquote>
<p><em>"When we\'re done, you won\'t interact with Airtable directly. You\'ll interact with a front-end designed for your role, and the front-end will talk to the database behind the scenes. We\'re building the store so you don\'t have to go into the back room."</em></p>
</blockquote>
<hr />
<hr />
<h2>The Baked Thought, Assessed</h2>
<table>
<thead>
<tr>
<th>Your Thought</th>
<th>Assessment</th>
</tr>
</thead>
<tbody>
<tr>
<td>"Many issues aren\'t with Airtable—they\'re with Softr"</td>
<td>✅ Correct</td>
</tr>
<tr>
<td>"Users shouldn\'t interact directly with the database"</td>
<td>✅ Correct</td>
</tr>
<tr>
<td>"The database is organized for efficiency, not for end users"</td>
<td>✅ Correct</td>
</tr>
<tr>
<td>"The front-end should abstract the database layer"</td>
<td>✅ Correct</td>
</tr>
<tr>
<td>"Explaining this to frustrated people is hard"</td>
<td>✅ Also correct</td>
</tr>
</tbody>
</table>
<p><strong>You\'re right on all counts. The challenge is framing it in a way that lands.</strong></p>
<hr />
<h2>Final Thought</h2>
<blockquote>
<p><em>"The fact that there are many confusing, coded fields in the data tables is not a failure of the database. It is a failure of the front-end."</em></p>
</blockquote>
<p><strong>This is the line.</strong> It\'s clear. It\'s true. It shifts the conversation from "the database is bad" to "the interface is inadequate."</p>
<p>The database is doing its job. The front-end hasn\'t been doing its job. You\'re building the front-end that should have existed all along.</p>
<p><strong>That\'s not defensive. That\'s a diagnosis.</strong></p>',
);
