<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'how-to-claim-case',
  'title' => 'How to Claim a Case — Step-by-Step Guide',
  'category' => 'sops',
  'category_name' => 'Standard Operating Procedures',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'How to Claim a Case — Step-by-Step Guide',
    'document_type' => 'Standard Operating Procedure',
    'version' => '1.0',
    'last_updated' => '2026-09-07',
    'author' => 'ARCHR Development Team',
    'audience' => 'Admins, Caseworkers, Organizational Administrators',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '5',
    'tags' => 
    array (
      0 => 'claiming',
      1 => 'cases',
      2 => 'workflow',
      3 => 'getting-started',
      4 => 'SOP',
    ),
    'visibility' => 'authenticated',
  ),
  'source' => 'sops\\how-to-claim-case.md',
  'html' => '<h1>How to Claim a Case</h1>
<blockquote>
<p><strong>Who this is for:</strong> Anyone with permission to claim repair needs from the application queue — Admins, Caseworkers, and Organizational Administrators.</p>
</blockquote>
<h2>Why This Matters</h2>
<p>Claiming a case is how your organization says "we\'ll handle this." It\'s the moment an application becomes your responsibility. Get it right and the applicant gets help. Get it wrong and the case sits in limbo while the applicant wonders what happened.</p>
<hr />
<h2>What "Claiming" Actually Does</h2>
<p>When you claim repair need(s) from an application:</p>
<ol>
<li><strong>A Case is created</strong> — linked to the original Application</li>
<li><strong>Your organization is assigned</strong> — the case belongs to your org now</li>
<li><strong>The 90-day clock starts</strong> — you have 90 days to show progress</li>
<li><strong>Other orgs see it\'s claimed</strong> — they can\'t claim the same repair needs</li>
<li><strong>The applicant\'s status updates</strong> — they now have an organization working on their case</li>
</ol>
<blockquote>
<p><strong>Important:</strong> You\'re claiming specific repair needs, not the entire application. If an application has roof damage AND plumbing damage, your org can claim the roof while another org claims the plumbing. Two cases, one application.</p>
</blockquote>
<hr />
<h2>Step-by-Step: Claiming a Case</h2>
<h3>1. Find the Application</h3>
<ul>
<li>Go to <strong>Case Search</strong> or your <strong>dashboard queue</strong></li>
<li>Look for unclaimed applications (they\'ll be marked as available)</li>
<li>Filter by urgency, date, or repair need if needed</li>
</ul>
<h3>2. Review the Application</h3>
<p>Before claiming, check:</p>
<ul>
<li><strong>Is this in our service area?</strong> — verify the property address</li>
<li><strong>Can we handle this repair need?</strong> — does it match your org\'s capabilities?</li>
<li><strong>Do we have capacity?</strong> — can you start work within 90 days?</li>
<li><strong>Any urgency flags?</strong> — "Unable to stay" or "No potable water" means this should be prioritized</li>
</ul>
<h3>3. Click "Claim"</h3>
<ul>
<li>Open the application detail view</li>
<li>Click the <strong>Claim</strong> button</li>
<li><strong>Select the specific repair needs</strong> your organization will handle<ul>
<li>You can claim one, some, or all unclaimed repair needs</li>
</ul>
</li>
<li><strong>Add a brief note</strong> — e.g., "Roof assessment scheduled for 9/15"</li>
<li><strong>Confirm the claim</strong></li>
</ul>
<h3>4. Set Up the Case</h3>
<p>After claiming:</p>
<ul>
<li><strong>Assign a caseworker</strong> — who\'s the primary contact for this household?</li>
<li><strong>Set the initial status</strong> — typically "New" or "Intake Review"</li>
<li><strong>Log the first progress event</strong> — the system does this automatically when you claim, but you can add a note</li>
</ul>
<h3>5. Make First Contact</h3>
<p><strong>Within 48 hours:</strong></p>
<ul>
<li>Contact the applicant to introduce yourself and your organization</li>
<li>Confirm their repair needs</li>
<li>Schedule an assessment if needed</li>
<li>Set expectations for timeline</li>
</ul>
<blockquote>
<p><strong>Why 48 hours?</strong> Applicants who submit and hear nothing get anxious. Anxious applicants call other organizations, which creates duplicate work. A quick "we\'ve got your application, here\'s what happens next" goes a long way.</p>
</blockquote>
<hr />
<h2>The 90-Day Progress Clock</h2>
<p>Once you claim, you have <strong>90 days to show progress</strong>. If no progress is made in 90 days, the claim expires and another organization can pick it up.</p>
<p><strong>What counts as progress:</strong></p>
<ul>
<li>Any task created or updated</li>
<li>Any communication logged</li>
<li>Any document uploaded</li>
<li>Any assessment completed</li>
<li>Any status change</li>
</ul>
<p><strong>The clock resets</strong> every time progress is made. So keep the case moving — even a quick "called applicant, left voicemail" log entry resets the timer.</p>
<blockquote>
<p><strong>Don\'t game the system.</strong> Logging fake progress just to keep a claim alive doesn\'t help the applicant. If you can\'t actually work the case, release it so another org can help.</p>
</blockquote>
<hr />
<h2>Releasing a Claim</h2>
<p>If your organization can\'t handle a claimed repair need:</p>
<ol>
<li><strong>Open the case</strong></li>
<li><strong>Click "Release Claim"</strong></li>
<li><strong>Add a reason</strong> — e.g., "Scope超出 our capabilities" or "No crew availability"</li>
<li><strong>Confirm</strong> — the repair need becomes available for other organizations</li>
</ol>
<blockquote>
<p><strong>Releasing a claim is not a failure.</strong> It\'s responsible coalition behavior. If you can\'t do the work, let someone who can step up.</p>
</blockquote>
<hr />
<h2>Common Scenarios</h2>
<h3>Scenario: All Repair Needs Are Already Claimed</h3>
<p>The application has roof (claimed by Habitat), plumbing (claimed by CHC), and electrical (unclaimed). You can claim the electrical. You cannot claim the roof or plumbing — those belong to other organizations.</p>
<h3>Scenario: You Claimed by Mistake</h3>
<p>Release the claim immediately with a note explaining the error. The repair need becomes available again.</p>
<h3>Scenario: The 90-Day Clock Is About to Expire</h3>
<p>Either make progress (log an event, create a task, contact the applicant) or release the claim. Don\'t let it expire — expired claims look bad for your organization in coalition reports.</p>
<hr />
<h2>Quick Reference</h2>
<table>
<thead>
<tr>
<th>Action</th>
<th>Where</th>
<th>Who</th>
</tr>
</thead>
<tbody>
<tr>
<td>View available applications</td>
<td>Case Search / Dashboard queue</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td>Review application</td>
<td>Application detail view</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td>Claim repair needs</td>
<td>Application detail → "Claim" button</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td>Assign caseworker</td>
<td>Case detail → Staff assignment</td>
<td>Admin</td>
</tr>
<tr>
<td>Log progress event</td>
<td>Any case action auto-logs</td>
<td>Everyone</td>
</tr>
<tr>
<td>Release claim</td>
<td>Case detail → "Release Claim"</td>
<td>Admin, Caseworker</td>
</tr>
<tr>
<td>View 90-day clock</td>
<td>Case detail → Claim info</td>
<td>Everyone</td>
</tr>
</tbody>
</table>
<hr />
<p><strong>Remember:</strong> Claiming a case is a promise to the applicant. Make sure you can keep it.</p>',
);
