<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'if-it-happened-log-it',
  'title' => 'TLE_STANDARD_OPERATING_PROCEDURE_v1',
  'category' => 'technical',
  'category_name' => 'Technical Guides',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'TLE_STANDARD_OPERATING_PROCEDURE_v1',
    'document_type' => 'Standard Operating Procedure',
    'version' => '1.0',
    'last_updated' => '2024-12-19',
    'author' => 'ARCHR Development Team',
    'audience' => 'All Platform Users (Requestors, Volunteers, Crew, Assessors, Subcontractors, Caseworkers, Project Managers, Bursars, Admins)',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '3',
    'tags' => 
    array (
      0 => 'tasks',
      1 => 'logs',
      2 => 'events',
      3 => 'documentation',
      4 => 'SOP',
    ),
  ),
  'source' => 'technical\\if-it-happened-log-it.md',
  'html' => '<h1>TASKS, LOGS &amp; EVENTS: STANDARD OPERATING PROCEDURE</h1>
<h2>Why We Log Everything</h2>
<p><strong>One rule:</strong> If it happened, log it.</p>
<p>Every task, every client communication, every scheduling note, every event needs to be in the system. This is how we:</p>
<ul>
<li>Track what\'s been done and what\'s left</li>
<li>Avoid duplicate work</li>
<li>Know who to contact about what</li>
<li>Show funders our impact</li>
<li>Protect ourselves with documentation</li>
</ul>
<p><strong>If you didn\'t log it, it didn\'t happen.</strong></p>
<hr />
<h2>When to Log</h2>
<table>
<thead>
<tr>
<th>If you...</th>
<th>Log it as...</th>
</tr>
</thead>
<tbody>
<tr>
<td>Need something done</td>
<td>Task</td>
</tr>
<tr>
<td>Talk to a client on phone/email/in-person</td>
<td>Communication</td>
</tr>
<tr>
<td>Schedule an assessment or site visit</td>
<td>Event</td>
</tr>
<tr>
<td>Attend or plan a community event</td>
<td>Event</td>
</tr>
<tr>
<td>Notice something that needs attention</td>
<td>Task</td>
</tr>
<tr>
<td>Complete a repair step</td>
<td>Task (with update)</td>
</tr>
<tr>
<td>Take photos of work</td>
<td>Task (attach photos)</td>
</tr>
</tbody>
</table>
<hr />
<h2>How to Log (Two Clicks)</h2>
<h3>Quick Add (Anywhere, Anytime)</h3>
<ol>
<li><strong>Look for the <code>+</code> button</strong> next to "Tasks, Logs &amp; Events" in the sidebar</li>
<li><strong>Click it</strong> → a small form opens</li>
<li><strong>Enter two things:</strong><ul>
<li>Which case/project this is for (start typing the address or case number)</li>
<li>What needs to be logged (a brief description)</li>
</ul>
</li>
<li><strong>Click Save</strong> → you\'re done</li>
</ol>
<p><strong>That\'s it.</strong> The system captures:</p>
<ul>
<li>Who you are (auto-filled)</li>
<li>When you logged it (auto-stamped)</li>
<li>What you entered (your description)</li>
</ul>
<h3>What If I Don\'t Know the Case Number?</h3>
<p>Type the client\'s name or street address. The system will suggest matching cases.</p>
<h3>What If I Have No Internet?</h3>
<p><strong>Write it down.</strong> On paper. In a notes app. On a napkin. Then paste it into a Quick Add when you\'re back online.</p>
<h3>What If I Have 12 Things to Log?</h3>
<p><strong>Log them all.</strong> Quick Add is designed for bulk entry. Log one, click "Save &amp; Add Another," repeat.</p>
<hr />
<h2>The Review Process (Peer Review)</h2>
<h3>Why Review?</h3>
<p>Quick entries are <strong>drafts</strong>. They\'re not counted in metrics or assigned to anyone until a <strong>Task Rabbit</strong> reviews them.</p>
<h3>Who Is a Task Rabbit?</h3>
<p>A Task Rabbit is someone (usually office-based) who:</p>
<ul>
<li>Has time to sit at a computer</li>
<li>Knows the data fields</li>
<li>Can add missing details</li>
<li>Approves entries so they become real tasks</li>
</ul>
<h3>What Task Rabbits Do</h3>
<ol>
<li><strong>Open the "Unverified" queue</strong> (it has a badge showing how many are waiting)</li>
<li><strong>Review each quick entry</strong></li>
<li><strong>Add required fields:</strong><ul>
<li>Priority (1-5)</li>
<li>Who should do this (role or person)</li>
<li>Due date</li>
<li>Subtasks (if needed)</li>
</ul>
</li>
<li><strong>Approve or reject</strong> the entry</li>
</ol>
<h3>What Happens After Approval</h3>
<ul>
<li>The entry becomes a <strong>real task</strong> or <strong>log entry</strong></li>
<li>It appears in the appropriate queue</li>
<li>It gets counted in metrics</li>
<li>The assigned person is notified</li>
</ul>
<hr />
<h2>Quick Log vs. Formal Entry</h2>
<table>
<thead>
<tr>
<th>Feature</th>
<th>Quick Log</th>
<th>Formal Entry (After Review)</th>
</tr>
</thead>
<tbody>
<tr>
<td>Who can do it</td>
<td>Anyone</td>
<td>Task Rabbits</td>
</tr>
<tr>
<td>Required fields</td>
<td>Case + Description</td>
<td>Priority, Assignee, Due Date, Subtasks</td>
</tr>
<tr>
<td>Counted in metrics</td>
<td>❌ No</td>
<td>✅ Yes</td>
</tr>
<tr>
<td>Shows in task lists</td>
<td>❌ Unverified queue only</td>
<td>✅ Yes</td>
</tr>
<tr>
<td>Time to complete</td>
<td>30 seconds</td>
<td>2-5 minutes</td>
</tr>
<tr>
<td>When to use</td>
<td>In the field, on the go</td>
<td>At a desk, with time</td>
</tr>
</tbody>
</table>
<hr />
<h2>Common Scenarios</h2>
<h3>Scenario 1: You\'re on Site, No Service</h3>
<p><strong>What you do:</strong> Take notes on your phone. "Roof: 3 missing shingles. Left side. Need ladder."</p>
<p><strong>When you get back:</strong> Open Quick Add, paste your notes, log it.</p>
<h3>Scenario 2: You Just Got Off the Phone</h3>
<p><strong>What you do:</strong> Open Quick Add, select the case, type: "Call with Sarah. She confirmed assessment for Dec 18 at 2pm. She will call if she needs to reschedule."</p>
<p><strong>Why:</strong> Next person who sees the case knows Sarah was contacted.</p>
<h3>Scenario 3: You\'re at a Desk and Have Time</h3>
<p><strong>What you do:</strong> Go to the "Unverified" queue. Look for entries without enough detail. Fill in the missing fields and approve them.</p>
<p><strong>Why:</strong> This keeps the system accurate and helps everyone.</p>
<h3>Scenario 4: You Have a Lot of Tasks</h3>
<p><strong>What you do:</strong> Use Quick Add for each one. Click "Save &amp; Add Another" after each.</p>
<p><strong>Why:</strong> Bulk entry is faster than writing them all down somewhere else.</p>
<hr />
<h2>Tips for Writing Good Entries</h2>
<h3>DO:</h3>
<table>
<thead>
<tr>
<th>Good</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr>
<td>"Schedule roof inspection - needs estimate for shingle replacement"</td>
<td>Clear, actionable</td>
</tr>
<tr>
<td>"Call with Maria - she will upload documents by Friday"</td>
<td>Specific, follow-up possible</td>
</tr>
<tr>
<td>"Need electrical quote - breaker panel is overloaded"</td>
<td>Identifies the issue</td>
</tr>
</tbody>
</table>
<h3>DON\'T:</h3>
<table>
<thead>
<tr>
<th>Not Helpful</th>
<th>Why Not</th>
</tr>
</thead>
<tbody>
<tr>
<td>"Fix stuff"</td>
<td>What stuff?</td>
</tr>
<tr>
<td>"Talked to client"</td>
<td>Who? About what?</td>
</tr>
<tr>
<td>"Follow up"</td>
<td>When? With whom?</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Golden Rule:</strong> Write enough detail that someone else could take over without having to ask you what you meant.</p>
</blockquote>
<hr />
<h2>Important Reminders</h2>
<table>
<thead>
<tr>
<th>Rule</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Log it immediately</strong></td>
<td>Memory fades. Don\'t wait.</td>
</tr>
<tr>
<td><strong>Include the case</strong></td>
<td>Otherwise nobody knows where it goes.</td>
</tr>
<tr>
<td><strong>Be specific</strong></td>
<td>Vague logs cause confusion.</td>
</tr>
<tr>
<td><strong>Trust the process</strong></td>
<td>Quick Add → Review → Approved → Done.</td>
</tr>
<tr>
<td><strong>Someone\'s watching</strong></td>
<td>The ledger never forgets. Every log is permanent.</td>
</tr>
</tbody>
</table>
<hr />
<h2>One Last Thing</h2>
<blockquote>
<p><strong>"Did it happen?"</strong></p>
<p>If yes, log it.</p>
<p><strong>"Does it need to happen?"</strong></p>
<p>If yes, log it as a task.</p>
<p><strong>"Can I add it later?"</strong></p>
<p>Yes, but add it now so you don\'t forget.</p>
</blockquote>
<hr />
<p><em>Your logs are the memory of the organization. Make them count.</em></p>
<hr />
<h2>Quick Reference Card (Printable)</h2>',
);
