<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'intake-privacy',
  'title' => 'What Information Do I Need to Provide in an Intake?',
  'category' => 'technical',
  'category_name' => 'Technical Guides',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'What Information Do I Need to Provide in an Intake?',
    'document_type' => 'Privacy Guide',
    'version' => '1.0',
    'last_updated' => '2026-07-10',
    'author' => 'ARCHR Development Team',
    'audience' => 'Requestors (Applicants), Volunteers Helping Applicants',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '3-4 minutes',
    'tags' => 
    array (
      0 => 'privacy',
      1 => 'intake',
      2 => 'pii',
      3 => 'data-protection',
      4 => 'consent',
    ),
  ),
  'source' => 'technical\\intake-privacy.md',
  'html' => '<h3>Outline</h3>
<p><strong>1. What We Ask For (And Why)</strong></p>
<table>
<thead>
<tr>
<th>Information</th>
<th>Why We Need It</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Contact Info</strong></td>
<td>To reach you about your application</td>
</tr>
<tr>
<td><strong>Home Address</strong></td>
<td>To verify location and serve your property</td>
</tr>
<tr>
<td><strong>Household Size</strong></td>
<td>To determine income eligibility</td>
</tr>
<tr>
<td><strong>Income</strong></td>
<td>To qualify for programs (no lower limit, upper limit varies)</td>
</tr>
<tr>
<td><strong>Home Ownership</strong></td>
<td>To confirm you can authorize repairs</td>
</tr>
<tr>
<td><strong>Demographics</strong></td>
<td>For grant reporting and program eligibility</td>
</tr>
<tr>
<td><strong>Repair Needs</strong></td>
<td>To assess scope of work</td>
</tr>
<tr>
<td><strong>Photos/Evidence</strong></td>
<td>To document damage and scope</td>
</tr>
</tbody>
</table>
<p><strong>2. What We DON\'T Ask For</strong></p>
<ul>
<li>
<p>Social Security Number</p>
</li>
<li>
<p>Bank account details</p>
</li>
<li>
<p>Immigration status</p>
</li>
<li>
<p>Criminal history</p>
</li>
<li>
<p>Medical records</p>
</li>
</ul>
<p><strong>3. Privacy Protections</strong></p>
<table>
<thead>
<tr>
<th>Protection</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Encryption</strong></td>
<td>All PII encrypted at rest and in transit</td>
</tr>
<tr>
<td><strong>Role-Based Access</strong></td>
<td>Only assigned staff can see your information</td>
</tr>
<tr>
<td><strong>Audit Trail</strong></td>
<td>Every access is logged</td>
</tr>
<tr>
<td><strong>No Sharing</strong></td>
<td>Information never shared outside ARCHR organizations</td>
</tr>
<tr>
<td><strong>No Selling</strong></td>
<td>We never sell data to advertisers or brokers</td>
</tr>
<tr>
<td><strong>Warrant Required</strong></td>
<td>We don\'t share with law enforcement without a warrant</td>
</tr>
</tbody>
</table>
<p><strong>4. What is PPI (Protected &amp; Privileged Information)?</strong></p>
<ul>
<li>
<p>All information you provide is considered private</p>
</li>
<li>
<p>Protected under Privacy Act considerations</p>
</li>
<li>
<p>Only used for your application and repair</p>
</li>
<li>
<p>Never used for any other purpose</p>
</li>
</ul>
<p><strong>5. Your Rights</strong></p>
<ul>
<li>
<p>View your data at any time</p>
</li>
<li>
<p>Request corrections</p>
</li>
<li>
<p>Request deletion (after case closure)</p>
</li>
<li>
<p>Withdraw consent at any time</p>
</li>
<li>
<p>Know who has accessed your data</p>
</li>
</ul>
<p><strong>6. The Consent Form</strong></p>
<ul>
<li>
<p>You\'ll sign a consent form during intake</p>
</li>
<li>
<p>This allows us to process your application</p>
</li>
<li>
<p>You can revoke consent at any time</p>
</li>
<li>
<p>If you revoke, we stop processing (but may still need to retain records)</p>
</li>
</ul>
<p><strong>7. What Happens When Your Case is Closed</strong></p>
<ul>
<li>
<p>Data retained for 7 years (grant requirements)</p>
</li>
<li>
<p>Then archived to cold storage</p>
</li>
<li>
<p>At 10 years, permanently deleted</p>
</li>
<li>
<p>You can request early deletion (some data may need to stay for compliance)</p>
</li>
</ul>',
);
