<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'intake-deployment-checklist',
  'title' => 'Intake Deployment Checklist',
  'category' => 'developers',
  'category_name' => 'For Developers',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Intake Deployment Checklist',
    'document_type' => 'Checklist',
    'version' => '1.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'Developers, Admins',
    'complexity_level' => 'Intermediate',
    'estimated_reading_minutes' => '5',
    'tags' => 
    array (
      0 => 'deployment',
      1 => 'checklist',
      2 => 'intake',
      3 => 'pre-flight',
    ),
    'visibility' => 
    array (
      0 => 'admin',
      1 => 'super-admin',
    ),
  ),
  'source' => 'developers\\intake-deployment-checklist.md',
  'html' => '<h2>Pre-Deployment</h2>
<ul>
<li>[ ] Create all tables (run schema creation scripts)</li>
<li>[ ] Create sequences (fifo_sequence)</li>
<li>[ ] Create helper functions (is_in_service_area, get_income_bucket, etc.)</li>
<li>[ ] Create main functions (submit_intake_application, check_eligibility)</li>
<li>[ ] Create triggers (anchor_id, timestamps)</li>
<li>[ ] Create views (staff_review_queue, role-specific views)</li>
<li>[ ] Grant appropriate permissions to application user</li>
</ul>
<h2>Post-Deployment Validation</h2>
<ul>
<li>[ ] Test submission with valid data → eligible</li>
<li>[ ] Test submission with invalid data → ineligible with reason</li>
<li>[ ] Test optional account creation</li>
<li>[ ] Verify notifications appear for staff roles</li>
<li>[ ] Verify queue maintains FIFO order</li>
<li>[ ] Verify anchor captures all applications</li>
<li>[ ] Test guest access token generation</li>
<li>[ ] Verify email queue entries created</li>
</ul>
<h2>Rollback Plan</h2>
<p>If issues occur:</p>
<ol>
<li>Set application to maintenance mode</li>
<li>Truncate test submissions (if any)</li>
<li>Rollback to previous version of functions</li>
<li>No schema rollback without data migration</li>
</ol>
<h2>Monitoring Queries</h2>
<p>-- Check recent submissions
SELECT id, applicant_first_name, applicant_last_name, submission_status, submitted_at
FROM intake_submissions 
ORDER BY submitted_at DESC LIMIT 10;</p>
<p>-- Check queue health
SELECT status, COUNT(*) FROM review_queue GROUP BY status;</p>
<p>-- Check notification delivery
SELECT status, COUNT(*) FROM email_queue GROUP BY status;</p>
<p>-- Check anchor coverage
SELECT COUNT(*) FROM intake_submissions s
LEFT JOIN application_anchor a ON s.id = a.submission_id
WHERE a.id IS NULL;</p>
<h2>Appendix: Quick Reference</h2>
<table>
<thead>
<tr>
<th>Component</th>
<th>Function/Table</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr>
<td>Submission Handler</td>
<td><code>submit_intake_application()</code></td>
<td>Main entry point</td>
</tr>
<tr>
<td>Eligibility Check</td>
<td><code>check_eligibility()</code></td>
<td>"Accept until disqualify" logic</td>
</tr>
<tr>
<td>Anchor Registry</td>
<td><code>application_anchor</code></td>
<td>Tracks EVERY application</td>
</tr>
<tr>
<td>Review Queue</td>
<td><code>review_queue</code></td>
<td>FIFO with priority</td>
</tr>
<tr>
<td>Notifications</td>
<td><code>notifications</code></td>
<td>In-app alerts</td>
</tr>
<tr>
<td>Email Queue</td>
<td><code>email_queue</code></td>
<td>Batched email delivery</td>
</tr>
<tr>
<td>Staff Views</td>
<td><code>staff_review_queue</code></td>
<td>Unified queue display</td>
</tr>
</tbody>
</table>
<hr />
<p><em>End of Technical Specification</em></p>
<p>text</p>
<p>This comprehensive implementation guide provides:</p>
<ol>
<li><strong>Complete submission handler</strong> with optional account creation</li>
<li><strong>"Accept until disqualify" eligibility checker</strong> that defaults to eligible</li>
<li><strong>Anchor registration</strong> for every application (critical for metrics)</li>
<li><strong>FIFO review queue</strong> with priority scoring</li>
<li><strong>Notification system</strong> for staff roles</li>
<li><strong>Email digest</strong> system for batched notifications</li>
<li><strong>Test cases</strong> for validation</li>
<li><strong>Deployment checklist</strong> for your PostgreSQL learning journey
The philosophy throughout is "accept until disqualifying information found" - meaning the system errs on the side of including applications, then marks them appropriately for tracking. Every application gets anchored, regardless of outcome, ensuring your metrics are complete.</li>
</ol>',
);
