<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'making-an-account',
  'title' => 'How Do I Make an Account?',
  'category' => 'technical',
  'category_name' => 'Technical Guides',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'How Do I Make an Account?',
    'document_type' => 'User Guide',
    'version' => '1.0',
    'last_updated' => '2026-07-10',
    'author' => 'ARCHR Development Team',
    'audience' => 'All Platform Users',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '2-3 minutes',
    'tags' => 
    array (
      0 => 'account',
      1 => 'registration',
      2 => 'login',
      3 => 'roles',
      4 => 'demo',
    ),
  ),
  'source' => 'technical\\making-an-account.md',
  'html' => '<h3>Outline</h3>
<p><strong>1. The Short Answer: You Don\'t</strong></p>
<ul>
<li>
<p>There is no public registration option</p>
</li>
<li>
<p>Accounts are generated based on your role</p>
</li>
</ul>
<p><strong>2. How Accounts Are Created by Role</strong></p>
<table>
<thead>
<tr>
<th>Role</th>
<th>How Account Is Created</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Requestor (Applicant)</strong></td>
<td>At the end of intake form, you create credentials (optional but recommended)</td>
</tr>
<tr>
<td><strong>Volunteer</strong></td>
<td>Fill out volunteer interest form → account generated</td>
</tr>
<tr>
<td><strong>Staff (Caseworker, PM, etc.)</strong></td>
<td>Organization admin creates your account</td>
</tr>
<tr>
<td><strong>Subcontractor</strong></td>
<td>Project manager or admin invites you</td>
</tr>
<tr>
<td><strong>Assessor</strong></td>
<td>Organization admin creates your account</td>
</tr>
<tr>
<td><strong>Bursar</strong></td>
<td>Organization admin creates your account</td>
</tr>
<tr>
<td><strong>Admin (Organization)</strong></td>
<td>Your organization designates you</td>
</tr>
<tr>
<td><strong>Envoy</strong></td>
<td>Coalition leadership creates your account</td>
</tr>
</tbody>
</table>
<p><strong>3. I\'m a Requestor - What Do I Do?</strong></p>
<ul>
<li>
<p>Complete the intake form (14 pages)</p>
</li>
<li>
<p>At the end, you\'ll see an option to create login credentials</p>
</li>
<li>
<p>This is optional but recommended (track your application status)</p>
</li>
<li>
<p>Choose a username (suggested: first initial + last name)</p>
</li>
<li>
<p>System generates a complicated password (write it down!)</p>
</li>
<li>
<p>You can change password after first login</p>
</li>
</ul>
<p><strong>4. I\'m a Volunteer - What Do I Do?</strong></p>
<ul>
<li>
<p>Fill out the volunteer interest form</p>
</li>
<li>
<p>You\'ll receive an email with your account details</p>
</li>
<li>
<p>Login to access volunteer dashboard</p>
</li>
<li>
<p>See available "quests" (tasks) matching your skills</p>
</li>
</ul>
<p><strong>5. I\'m Staff - What Do I Do?</strong></p>
<ul>
<li>
<p>Your admin will set up your account</p>
</li>
<li>
<p>You\'ll receive an email with login details</p>
</li>
<li>
<p>Login and set your password</p>
</li>
<li>
<p>Your dashboard is role-specific</p>
</li>
</ul>
<p><strong>6. Is There a Demo Account?</strong></p>
<ul>
<li>
<p>Yes! For public exploration</p>
</li>
<li>
<p>Uses placeholder data (not real cases)</p>
</li>
<li>
<p>Great for training and exploration</p>
</li>
<li>
<p>Request access through the website</p>
</li>
</ul>
<p><strong>7. I Forgot My Password</strong></p>
<ul>
<li>
<p>Use "Forgot Password" link on login page</p>
</li>
<li>
<p>Reset link sent to your email</p>
</li>
<li>
<p>You can also ask your organization admin</p>
</li>
</ul>',
);
