<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'generated_at' => '2026-09-07T02:45:45+02:00',
  'categories' => 
  array (
    'start-here' => 
    array (
      'name' => 'Start Here',
      'order' => 1,
      'docs' => 
      array (
        0 => 
        array (
          'slug' => 'component-documentation-status',
          'title' => 'Component Documentation Status Tracker',
        ),
        1 => 
        array (
          'slug' => 'start-here',
          'title' => 'Welcome to the Asheville Regional Coalition for Home Repair (ARCHR) Platform',
        ),
      ),
    ),
    'archr101' => 
    array (
      'name' => 'ARCHR 101',
      'order' => 2,
      'docs' => 
      array (
        0 => 
        array (
          'slug' => 'archr101',
          'title' => 'ARCHR 101 - From Submission to Roof Repair',
        ),
        1 => 
        array (
          'slug' => 'home-repair-gameification',
          'title' => 'Home Repair Gamification — Making Mutual Care Engaging',
        ),
        2 => 
        array (
          'slug' => 'metrics-math-money',
          'title' => 'Metrics, Math, and Money - How We Make This All Possible',
        ),
        3 => 
        array (
          'slug' => 'nonprofit-knowledge-sharing',
          'title' => 'Nonprofit Knowledge Sharing',
        ),
        4 => 
        array (
          'slug' => 'eligibility',
          'title' => 'Who Qualifies? Eligibility Determination & Assuming Eligibility',
        ),
      ),
    ),
    'setting-up' => 
    array (
      'name' => 'Setting Up',
      'order' => 3,
      'docs' => 
      array (
        0 => 
        array (
          'slug' => 'setting-up',
          'title' => 'Setting up a Regional Home Repair Coalition',
        ),
      ),
    ),
    'technical' => 
    array (
      'name' => 'Technical Guides',
      'order' => 4,
      'docs' => 
      array (
        0 => 
        array (
          'slug' => 'making-an-account',
          'title' => 'How Do I Make an Account?',
        ),
        1 => 
        array (
          'slug' => 'if-it-happened-log-it',
          'title' => 'TLE_STANDARD_OPERATING_PROCEDURE_v1',
        ),
        2 => 
        array (
          'slug' => 'open-source-home-repair',
          'title' => 'This Project is Open-Source - Start One in Your Region',
        ),
        3 => 
        array (
          'slug' => 'intake-privacy',
          'title' => 'What Information Do I Need to Provide in an Intake?',
        ),
      ),
    ),
    'sops' => 
    array (
      'name' => 'Standard Operating Procedures',
      'order' => 5,
      'docs' => 
      array (
        0 => 
        array (
          'slug' => 'application-review-case-mgmt',
          'title' => 'Application Review & Case Management SOP',
        ),
        1 => 
        array (
          'slug' => 'completing-repair-case',
          'title' => 'Completing a Case & Closing Out SOP',
        ),
        2 => 
        array (
          'slug' => 'conducting-home-assessment',
          'title' => 'Conducting a Home Assessment SOP',
        ),
        3 => 
        array (
          'slug' => 'document-management',
          'title' => 'Document Management — Uploading, Organizing & Finding Files',
        ),
        4 => 
        array (
          'slug' => 'editing-applicant-contact-info',
          'title' => 'Editing Applicant Contact Info',
        ),
        5 => 
        array (
          'slug' => 'home-repair-financial-mgmt',
          'title' => 'Financial Management — Budgets, Invoices & Payments SOP',
        ),
        6 => 
        array (
          'slug' => 'repair-screening-intake-form',
          'title' => 'Home Repair Services Screening Form — Field Reference & SOP',
        ),
        7 => 
        array (
          'slug' => 'how-to-claim-case',
          'title' => 'How to Claim a Case — Step-by-Step Guide',
        ),
        8 => 
        array (
          'slug' => 'navigate-help',
          'title' => 'How to Use This Help Library',
        ),
        9 => 
        array (
          'slug' => 'managing-repair-projects',
          'title' => 'Managing Repair Projects SOP',
        ),
        10 => 
        array (
          'slug' => 'roles-and-access-levels',
          'title' => 'Roles & Access Levels — Who Sees What in ARCHR',
        ),
        11 => 
        array (
          'slug' => 'volunteer-mgmt',
          'title' => 'Volunteer Management & Hour Tracking SOP',
        ),
      ),
    ),
    'funding' => 
    array (
      'name' => 'Funding & Costs',
      'order' => 7,
      'docs' => 
      array (
        0 => 
        array (
          'slug' => 'project-cost',
          'title' => 'The Money Trail — Funding Flow & Project Costs',
        ),
      ),
    ),
    'platform-anatomy' => 
    array (
      'name' => 'Platform Anatomy',
      'order' => 8,
      'docs' => 
      array (
        0 => 
        array (
          'slug' => 'branding-guide',
          'title' => 'ARCHR Brand & Interface Guide',
        ),
        1 => 
        array (
          'slug' => 'archr-developer-roadmap-july-20-sept-21',
          'title' => 'ARCHR_DEVELOPMENT_ROADMAP_Q3_2026',
        ),
        2 => 
        array (
          'slug' => 'baseid-airtable-guide',
          'title' => 'Airtable Base IDs Quick Reference',
        ),
        3 => 
        array (
          'slug' => 'form-submission-journey',
          'title' => 'Form Submission Journey — Security & Data Flow',
        ),
        4 => 
        array (
          'slug' => 'progress-tracker',
          'title' => 'Progress Event Tracking V2',
        ),
      ),
    ),
    'developers' => 
    array (
      'name' => 'For Developers',
      'order' => 9,
      'docs' => 
      array (
        0 => 
        array (
          'slug' => 'system-anatomy',
          'title' => 'Anatomy of a Home Repair Platform',
        ),
        1 => 
        array (
          'slug' => 'submission',
          'title' => 'Application',
        ),
        2 => 
        array (
          'slug' => 'platforms-code',
          'title' => 'Current Platforms and The Great Code Migration',
        ),
        3 => 
        array (
          'slug' => 'intake-deployment-checklist',
          'title' => 'Intake Deployment Checklist',
        ),
        4 => 
        array (
          'slug' => 'progress-task-doccode-docact-completion-map',
          'title' => 'Progress Task to DocCode × DocAct Completion Map',
        ),
        5 => 
        array (
          'slug' => 'schema-mapping',
          'title' => 'Schema Mapping and Database - The Flow of Data',
        ),
        6 => 
        array (
          'slug' => 'sync-map-data-flows',
          'title' => 'Sync Map Data Flows — Base-to-Base Diagrams',
        ),
      ),
    ),
    'feedback-meeting' => 
    array (
      'name' => 'Coalition Feedback & Insights',
      'order' => 10,
      'docs' => 
      array (
        0 => 
        array (
          'slug' => 'meeting-notes',
          'title' => 'Coalition Feedback Meeting Notes — 8/4/2026',
        ),
        1 => 
        array (
          'slug' => 'excel-gateway',
          'title' => 'Excel Gateway Exploration',
        ),
        2 => 
        array (
          'slug' => 'feedback-meeting',
          'title' => 'Feedback Response Index',
        ),
        3 => 
        array (
          'slug' => 'frontend-failure',
          'title' => 'Frontend vs Backend — What\'s Really Broken',
        ),
        4 => 
        array (
          'slug' => 'database-not-problem-explained',
          'title' => 'The Database Isn\'t the Problem — Explained Simply',
        ),
        5 => 
        array (
          'slug' => 'money-trail',
          'title' => 'The Money Trail -- How Do We Track Financial Metrics for Quarterly Reporting and Case Management?',
        ),
      ),
    ),
  ),
  'docs' => 
  array (
    'component-documentation-status' => 
    array (
      'title' => 'Component Documentation Status Tracker',
      'category' => 'start-here',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'archr101' => 
    array (
      'title' => 'ARCHR 101 - From Submission to Roof Repair',
      'category' => 'archr101',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'eligibility' => 
    array (
      'title' => 'Who Qualifies? Eligibility Determination & Assuming Eligibility',
      'category' => 'archr101',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'home-repair-gameification' => 
    array (
      'title' => 'Home Repair Gamification — Making Mutual Care Engaging',
      'category' => 'archr101',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'metrics-math-money' => 
    array (
      'title' => 'Metrics, Math, and Money - How We Make This All Possible',
      'category' => 'archr101',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'nonprofit-knowledge-sharing' => 
    array (
      'title' => 'Nonprofit Knowledge Sharing',
      'category' => 'archr101',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'intake-deployment-checklist' => 
    array (
      'title' => 'Intake Deployment Checklist',
      'category' => 'developers',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'platforms-code' => 
    array (
      'title' => 'Current Platforms and The Great Code Migration',
      'category' => 'developers',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'progress-task-doccode-docact-completion-map' => 
    array (
      'title' => 'Progress Task to DocCode × DocAct Completion Map',
      'category' => 'developers',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'schema-mapping' => 
    array (
      'title' => 'Schema Mapping and Database - The Flow of Data',
      'category' => 'developers',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'submission' => 
    array (
      'title' => 'Application',
      'category' => 'developers',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'sync-map-data-flows' => 
    array (
      'title' => 'Sync Map Data Flows — Base-to-Base Diagrams',
      'category' => 'developers',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'system-anatomy' => 
    array (
      'title' => 'Anatomy of a Home Repair Platform',
      'category' => 'developers',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'meeting-notes' => 
    array (
      'title' => 'Coalition Feedback Meeting Notes — 8/4/2026',
      'category' => 'feedback-meeting',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'database-not-problem-explained' => 
    array (
      'title' => 'The Database Isn\'t the Problem — Explained Simply',
      'category' => 'feedback-meeting',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'excel-gateway' => 
    array (
      'title' => 'Excel Gateway Exploration',
      'category' => 'feedback-meeting',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'frontend-failure' => 
    array (
      'title' => 'Frontend vs Backend — What\'s Really Broken',
      'category' => 'feedback-meeting',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'feedback-meeting' => 
    array (
      'title' => 'Feedback Response Index',
      'category' => 'feedback-meeting',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'money-trail' => 
    array (
      'title' => 'The Money Trail -- How Do We Track Financial Metrics for Quarterly Reporting and Case Management?',
      'category' => 'feedback-meeting',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'project-cost' => 
    array (
      'title' => 'The Money Trail — Funding Flow & Project Costs',
      'category' => 'funding',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'archr-developer-roadmap-july-20-sept-21' => 
    array (
      'title' => 'ARCHR_DEVELOPMENT_ROADMAP_Q3_2026',
      'category' => 'platform-anatomy',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'baseid-airtable-guide' => 
    array (
      'title' => 'Airtable Base IDs Quick Reference',
      'category' => 'platform-anatomy',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'branding-guide' => 
    array (
      'title' => 'ARCHR Brand & Interface Guide',
      'category' => 'platform-anatomy',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'form-submission-journey' => 
    array (
      'title' => 'Form Submission Journey — Security & Data Flow',
      'category' => 'platform-anatomy',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'progress-tracker' => 
    array (
      'title' => 'Progress Event Tracking V2',
      'category' => 'platform-anatomy',
      'visibility' => 'roles',
      'roles' => 
      array (
        0 => 'admin',
        1 => 'super-admin',
      ),
    ),
    'setting-up' => 
    array (
      'title' => 'Setting up a Regional Home Repair Coalition',
      'category' => 'setting-up',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'application-review-case-mgmt' => 
    array (
      'title' => 'Application Review & Case Management SOP',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'completing-repair-case' => 
    array (
      'title' => 'Completing a Case & Closing Out SOP',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'conducting-home-assessment' => 
    array (
      'title' => 'Conducting a Home Assessment SOP',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'document-management' => 
    array (
      'title' => 'Document Management — Uploading, Organizing & Finding Files',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'editing-applicant-contact-info' => 
    array (
      'title' => 'Editing Applicant Contact Info',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'home-repair-financial-mgmt' => 
    array (
      'title' => 'Financial Management — Budgets, Invoices & Payments SOP',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'how-to-claim-case' => 
    array (
      'title' => 'How to Claim a Case — Step-by-Step Guide',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'managing-repair-projects' => 
    array (
      'title' => 'Managing Repair Projects SOP',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'navigate-help' => 
    array (
      'title' => 'How to Use This Help Library',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'repair-screening-intake-form' => 
    array (
      'title' => 'Home Repair Services Screening Form — Field Reference & SOP',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'roles-and-access-levels' => 
    array (
      'title' => 'Roles & Access Levels — Who Sees What in ARCHR',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'volunteer-mgmt' => 
    array (
      'title' => 'Volunteer Management & Hour Tracking SOP',
      'category' => 'sops',
      'visibility' => 'authenticated',
      'roles' => 
      array (
      ),
    ),
    'start-here' => 
    array (
      'title' => 'Welcome to the Asheville Regional Coalition for Home Repair (ARCHR) Platform',
      'category' => 'start-here',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'if-it-happened-log-it' => 
    array (
      'title' => 'TLE_STANDARD_OPERATING_PROCEDURE_v1',
      'category' => 'technical',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'intake-privacy' => 
    array (
      'title' => 'What Information Do I Need to Provide in an Intake?',
      'category' => 'technical',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'making-an-account' => 
    array (
      'title' => 'How Do I Make an Account?',
      'category' => 'technical',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
    'open-source-home-repair' => 
    array (
      'title' => 'This Project is Open-Source - Start One in Your Region',
      'category' => 'technical',
      'visibility' => 'public',
      'roles' => 
      array (
      ),
    ),
  ),
);
