<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'meeting-notes',
  'title' => 'Coalition Feedback Meeting Notes — 8/4/2026',
  'category' => 'feedback-meeting',
  'category_name' => 'Coalition Feedback & Insights',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Coalition Feedback Meeting Notes — 8/4/2026',
    'document_type' => 'Meeting Notes',
    'version' => '1.0',
    'last_updated' => '2026-08-06',
    'author' => 'ARCHR Development Team',
    'audience' => 'Admins, Super-Admins',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '5',
    'tags' => 
    array (
      0 => 'feedback',
      1 => 'coalition',
      2 => 'usability',
      3 => 'timeline',
    ),
  ),
  'source' => 'feedback-meeting\\Meeting-notes.md',
  'html' => '<p>Coalition Feedback Meeting Notes 8/4/2026</p>
<hr />
<p>We have had partners pull out of collaborative, many reasons, one of them usability of database. Overall very important aspect. </p>
<p>They need a project timeline on when changes to the system will be visible and friendly. They need to be easily able to look up information about families and households they are working with.</p>
<p>What steps are being taken to address these issues? What are the timelines on when these issues will be addressed?</p>
<p>Two weeks ago, Kelvin was looking up a case and could not find how many people live int he home. He met with  Marisa, and viewed the case on the backend. His default view looks very different than that of Habitat. They set up to mimic the Red View, which I still don\'t have full clarity of which color means what. They were able to find the information needed. Marisa just left their role and is no longer available to help with that. Need to see what the requests are for each specific project. Reading on Airtable involves a lot of column fields with unreadable human unfriendly code. On the front end display, it doesn\'t have all of the information pertaining to the case. There is a huge need for simple information retrieval quickly in one place.</p>
<p>Being able to find information simply. Meeting with Marisa - tag for Poder Emma - Habitat Volunteers not calling those families. No way to know or easy way to find who has applied. People falling in the cracks. Who is applying for what</p>
<p>Goal to be as collaborative as possible. Amazing database that could help us be more collaborative</p>
<p>questions from fund development team - habitat - amanda - specific challenges up against - simple direct answer - first question around blank jobs that show up in tracking - worried making overall application number higher. what they are and how those can be cleaned up. those don\'t go towards countsdispleasure on not being able to filter own views, are we working towards this? every airtable user - folks able to use airtable and handling different organizations separately. Filtering is possible, but messy. no rhyme or reason to sort on airtable for new changes, work towards progressing towards a sorting system, acts more like an xcel spreadsheet</p>
<p>Potential towards more videos or training for Airtable?
don\'t have ability to close a job anylonger - Amanda - who is doing it at this time? jobs closed and funded that are still in open jobs. Way for Amanda to close a job on the Airtable. Adding an end date to project. Can enter manually. </p>',
);
