<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'metrics-math-money',
  'title' => 'Metrics, Math, and Money - How We Make This All Possible',
  'category' => 'archr101',
  'category_name' => 'ARCHR 101',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Metrics, Math, and Money - How We Make This All Possible',
    'document_type' => 'Financial Guide',
    'version' => '1.0',
    'last_updated' => '2026-07-10',
    'author' => 'ARCHR Development Team',
    'audience' => 'Bursars, Admin, Envoy, Funders',
    'complexity_level' => 'Advanced',
    'estimated_reading_minutes' => '5-8 minutes',
    'tags' => 
    array (
      0 => 'funding',
      1 => 'metrics',
      2 => 'budgeting',
      3 => 'grants',
      4 => 'reimbursement',
    ),
  ),
  'source' => 'archr101\\metrics-math-money.md',
  'html' => '<h3>Outline</h3>
<p><strong>1. Where Does the Money Come From?</strong></p>
<ul>
<li>Federal grants (FEMA, HUD)</li>
<li>State funding (North Carolina disaster relief)</li>
<li>Private foundations (Cisco, Land of Sky, etc.)</li>
<li>Partner organizations (Habitat, CHC, etc.)</li>
<li>Individual donations</li>
</ul>
<p><strong>2. The $50,000 Per Home Cap</strong></p>
<ul>
<li>Each eligible household is capped at $50,000 for disaster-related repairs</li>
<li>This is per disaster, per home (if another disaster hits, new cap applies)</li>
<li>Funds must be spent on eligible repairs only</li>
<li>The cap applies to total cost across all funding sources</li>
</ul>
<p><strong>3. How We Track Funding Per Case</strong></p>
<ul>
<li><strong>Approved Amount</strong>: What we\'ve committed to spend</li>
<li><strong>Incurred Costs</strong>: What we\'ve actually spent (invoices, materials, labor)</li>
<li><strong>Reimbursed Amount</strong>: What has been paid out</li>
<li><strong>Remaining Balance</strong>: What\'s left to spend</li>
<li><strong>On Hold</strong>: Money set aside for pending items</li>
</ul>
<p><strong>4. The Three Key Financial Dashboards</strong></p>
<table>
<thead>
<tr>
<th>Dashboard</th>
<th>Purpose</th>
<th>User</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Past Week</strong></td>
<td>Monitor recent activity</td>
<td>All staff</td>
</tr>
<tr>
<td><strong>All Time</strong></td>
<td>Track historical performance</td>
<td>All staff</td>
</tr>
<tr>
<td><strong>Organization Specific</strong></td>
<td>Per-org metrics</td>
<td>Admin, Bursar</td>
</tr>
</tbody>
</table>
<p><strong>5. The Metrics We Track</strong></p>
<p><strong>Past Week:</strong></p>
<ul>
<li>
<p>Total Applications</p>
</li>
<li>
<p>Assessments Assigned &amp; Completed</p>
</li>
<li>
<p>Average Triage Score</p>
</li>
<li>
<p>Total Individuals Served (from household size)</p>
</li>
<li>
<p>Income, County, Issue Type Breakdowns</p>
</li>
</ul>
<p><strong>All Time:</strong></p>
<ul>
<li>
<p>Total Jobs</p>
</li>
<li>
<p>Jobs In Progress / Completed / Withdrawn</p>
</li>
<li>
<p>Average Job Cost</p>
</li>
<li>
<p>Income &amp; County Breakdowns</p>
</li>
<li>
<p>Highest &amp; Lowest Job Costs</p>
</li>
</ul>
<p><strong>Organization Specific:</strong></p>
<ul>
<li>
<p>Total Jobs per org</p>
</li>
<li>
<p>Jobs In Progress / Completed / Suggested</p>
</li>
<li>
<p>Assessments Assigned / Completed / Pending</p>
</li>
<li>
<p>Cost Extremes and Averages</p>
</li>
</ul>
<p><strong>6. Reimbursement Workflow</strong></p>
<ul>
<li>
<p>Subcontractor submits invoice → enters queue</p>
</li>
<li>
<p>Bursar reviews (checks against scope, budget)</p>
</li>
<li>
<p>Approve or reject with reason</p>
</li>
<li>
<p>If approved → payment issued</p>
</li>
<li>
<p>Track aging: goal &lt; 30 days</p>
</li>
</ul>
<p><strong>7. Preventing Double-Dipping</strong></p>
<ul>
<li>
<p>Case locking prevents two orgs from claiming same case</p>
</li>
<li>
<p>Duplicate address detection</p>
</li>
<li>
<p>Overlapping invoice alerts</p>
</li>
<li>
<p>Every payment has audit trail</p>
</li>
</ul>',
);
