<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'money-trail',
  'title' => 'The Money Trail -- How Do We Track Financial Metrics for Quarterly Reporting and Case Management?',
  'category' => 'feedback-meeting',
  'category_name' => 'Coalition Feedback & Insights',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'The Money Trail -- How Do We Track Financial Metrics for Quarterly Reporting and Case Management?',
    'document_type' => 'Speculative Planning Document',
    'version' => '1.0',
    'last_updated' => '2026-08-06',
    'author' => 'April Chips',
    'audience' => 'Staff involved with ARCHR Platform',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '3',
    'tags' => 
    array (
      0 => 'tasks',
      1 => 'logs',
      2 => 'events',
      3 => 'documentation',
      4 => 'SOP',
    ),
  ),
  'source' => 'feedback-meeting\\money-trail.md',
  'html' => '<p>One of the biggest pain points and priorities brought to my attention is around financial tracking. </p>
<p>We are actively building a practical framework for chaos.</p>
<h2>The Problem, As I Understand It</h2>
<p>We have:</p>
<ul>
<li>A coalition of organizations doing home repairs</li>
<li>A central finance/accounting team for each partner organization with their own systems</li>
<li>A process that relies on spreadsheets, receipts, invoices, and timesheets</li>
<li>A need to keep track on a project-level of what gets spent, held, or is left for a household we are serving.</li>
</ul>
<p>What\'s difficult:</p>
<ul>
<li>Finance team doesn\'t participate in Airtable</li>
<li>Spreadsheets arrive in various formats</li>
<li>Receipts, invoices, timesheets come from multiple sources</li>
<li>Someone (office worker, volunteer) has to manually connect everything</li>
<li>Duplicate work happens across organizations</li>
</ul>
<p>The core tension:</p>
<blockquote>
<p><em>"Two entities doing the same exact financial work is impractical."</em></p>
</blockquote>
<hr />
<h2>The Reality</h2>
<p>You can\'t force the finance team to change their system. They have their own processes, their own security requirements, and their own way of working. They will continue to send spreadsheets. They will continue to work in their own tools.</p>
<p><strong>You need to work with what you have, not what you wish you had.</strong></p>
<hr />
<h2>A Helpful Mindset</h2>
<h3>1. Treat External Systems as Suppliers, Not Adversaries</h3>
<p>The finance team isn\'t "uncooperative"—they have different priorities, different constraints, and different tools. They\'re not trying to make your life harder. They\'re trying to do their job in a system that has its own logic.</p>
<p><strong>Instead of expecting them to change, design your system to accept their output.</strong></p>
<h3>2. Accept That Some Work Will Be Manual</h3>
<p>Automation is great. But when you\'re dealing with external departments, spreadsheets, and legacy systems, some manual work is inevitable.</p>
<p><strong>The goal isn\'t zero manual work. The goal is reducing it to the minimum necessary, and making the manual work easy.</strong></p>
<h3>3. Think Like a Data Pipeline, Not a Single System</h3>
<p>Data flows from one place to another, often in imperfect formats. Your job is to make that flow reliable, consistent, and auditable.</p>
<p><strong>Design for transformation, not integration.</strong></p>
<hr />
<h2>Five Practical Habits to Start Now</h2>
<h3>Habit 1: Standardize the Spreadsheet Import Process</h3>
<p><strong>Current state:</strong> Finance sends spreadsheets in various formats. Someone has to manually interpret them.</p>
<p><strong>Better habit:</strong></p>
<table>
<thead>
<tr>
<th>Step</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>Create a <strong>blank template</strong> for what you need (columns, formats, naming)</td>
</tr>
<tr>
<td>2</td>
<td>Send the template to finance: "This is how we\'ll receive data. You can keep your system, but please export in this format."</td>
</tr>
<tr>
<td>3</td>
<td>If they won\'t use your template, <strong>build a conversion script</strong> that maps their columns to yours</td>
</tr>
<tr>
<td>4</td>
<td>Document the mapping so you can re-run it each month</td>
</tr>
</tbody>
</table>
<p><strong>The habit:</strong> One conversion script per finance partner. Never manually reformat the same spreadsheet twice.</p>
<hr />
<h3>Habit 2: Use Case Codes (Placecodes) as the Universal Key</h3>
<p><strong>The problem:</strong> Receipts, invoices, and timesheets come from different sources and need to be connected.</p>
<p><strong>The solution:</strong> The placecode (e.g., 42-CHERRY) becomes the one consistent identifier across all documents.</p>
<table>
<thead>
<tr>
<th>Document Type</th>
<th>Has Placecode?</th>
<th>Need To Add</th>
</tr>
</thead>
<tbody>
<tr>
<td>Receipts (photos)</td>
<td>❌ No</td>
<td>Add placecode to filename</td>
</tr>
<tr>
<td>Invoices</td>
<td>⚠️ Maybe</td>
<td>Ensure placecode is in invoice reference</td>
</tr>
<tr>
<td>Timesheets</td>
<td>⚠️ Maybe</td>
<td>Add placecode to each entry</td>
</tr>
<tr>
<td>Spreadsheets from finance</td>
<td>❌ No</td>
<td>Add column for placecode</td>
</tr>
</tbody>
</table>
<p><strong>The habit:</strong> Every incoming document gets a placecode assigned before it enters your system. Train finance to include it (even as a reference number), or add it yourself as soon as you receive the document.</p>
<hr />
<h3>Habit 3: Create a "Staging Table" for External Data</h3>
<p>Instead of trying to merge external spreadsheets directly into your database, create a staging area where you can review, validate, and transform data before importing.</p>
<p><strong>Structure:</strong></p>
<p>text</p>
<p>┌─────────────────────────────────────────────────────────────────────────────────┐
│                    DATA PIPELINE                                               │
├─────────────────────────────────────────────────────────────────────────────────┤
│                                                                                  │
│  1. RECEIVE              2. STAGE               3. VALIDATE         4. IMPORT   │
│  ┌─────────────┐      ┌─────────────┐      ┌─────────────┐      ┌───────────┐ │
│  │ Spreadsheet │ →    │ Staging     │ →    │ Review &amp;    │ →    │ Live      │ │
│  │ from Finance│      │ Table       │      │ Transform   │      │ Database  │ │
│  └─────────────┘      └─────────────┘      └─────────────┘      └───────────┘ │
│                            │                                            │        │
│                            ▼                                            │        │
│                      ┌─────────────┐                                    │        │
│                      │ Issues Log  │                                    │        │
│                      │ (fix later) │                                    │        │
│                      └─────────────┘                                    │        │
│                                                                                  │
└─────────────────────────────────────────────────────────────────────────────────┘</p>
<p><strong>The habit:</strong> Never import external data directly. Always stage it, review it, and then import.</p>
<hr />
<h3>Habit 4: Create a "Simple Reporting" Data Mart</h3>
<p>Instead of requiring finance to participate in Airtable, build a lightweight, read-only view that they can access without learning the system.</p>
<p><strong>What this looks like:</strong></p>
<table>
<thead>
<tr>
<th>Element</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Read-Only Dashboard</strong></td>
<td>Finance can view, not edit. It\'s safe, so security is less of a concern.</td>
</tr>
<tr>
<td><strong>Pre-Built Reports</strong></td>
<td>The reports they need most (case costs by period, funding by source, etc.)</td>
</tr>
<tr>
<td><strong>Export to CSV</strong></td>
<td>They can download data in their preferred format</td>
</tr>
<tr>
<td><strong>Weekly Email Digest</strong></td>
<td>Key numbers sent directly to them</td>
</tr>
</tbody>
</table>
<p><strong>The habit:</strong> Make it easier for finance to get what they need from your system than to send you spreadsheets.</p>
<hr />
<h3>Habit 5: Log Everything (Especially the Inconsistent Stuff)</h3>
<p>If you have to manually reconcile receipts, invoices, and timesheets, <strong>document what you did.</strong></p>
<table>
<thead>
<tr>
<th>What to Log</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr>
<td>When you received a spreadsheet</td>
<td>Track timing and delays</td>
</tr>
<tr>
<td>What you changed</td>
<td>Proof of work</td>
</tr>
<tr>
<td>What was missing</td>
<td>Flag recurring issues</td>
</tr>
<tr>
<td>Who you talked to</td>
<td>Follow-up and accountability</td>
</tr>
</tbody>
</table>
<p><strong>The habit:</strong> Every manual reconciliation takes &lt; 5 minutes to document. This creates a trail that eventually reveals patterns and automation opportunities.</p>
<hr />
<h2>Bridging the Gap: Specific Suggestions</h2>
<h3>Suggestion 1: The "One Big Table" Approach</h3>
<p>Instead of trying to link everything automatically, create one master table that tracks case-level finances with a single row per case per month.</p>
<p><strong>Columns:</strong></p>
<ul>
<li>Case Number</li>
<li>Month/Year</li>
<li>Total Receipts (sum)</li>
<li>Total Invoices (sum)</li>
<li>Total Timesheets (sum)</li>
<li>Notes (anything unusual)</li>
</ul>
<p><strong>How it helps:</strong></p>
<ul>
<li>Finance can review one row per case per month</li>
<li>You can quickly check if numbers add up</li>
<li>Discrepancies are easy to spot</li>
</ul>
<p><strong>Implementation:</strong></p>
<ul>
<li>Start with last quarter\'s data manually (15-30 minutes)</li>
<li>Update monthly (5-10 minutes)</li>
<li>Look for patterns: which cases are most expensive? Which funding sources are tapped out?</li>
</ul>
<hr />
<h3>Suggestion 2: The "Staging Table" Alternative</h3>
<p>If you can\'t get finance to use your tools, you can create a lightweight import system using a spreadsheet that you control.</p>
<p><strong>Columns:</strong></p>
<ul>
<li>A timestamp for when the row was created in your system    </li>
<li>The case code</li>
<li>The amount</li>
<li>The category (receipt/invoice/timesheet)</li>
<li>The source (which finance sheet)</li>
<li>The original row ID (to prevent duplicates)</li>
<li>Notes/Date/Etc.</li>
</ul>
<p><strong>How to maintain it:</strong></p>
<ol>
<li>Keep a "copy" of the finance data (which is the same spreadsheets)</li>
<li>Use a script to parse it automatically (or manually, if you can\'t)</li>
<li>Load it into a PostgreSQL staging table    </li>
<li>Use the staging table for reporting</li>
</ol>
<p><strong>How it helps:</strong></p>
<ul>
<li>Once you have the data in a staging table, you can join it with other tables in PostgreSQL</li>
<li>You can run reports on the staging table (as if it were the main database)</li>
<li>You don\'t need to run queries on Airtable or the finance system</li>
</ul>
<p><strong>Important:</strong> Make sure the staging table is read-only and can be "recreated" from the source data at any time (e.g., you can drop and recreate it).</p>
<hr />
<h3>Suggestion 3: The "Reconciliation Report" Approach</h3>
<p>Instead of trying to integrate finance\'s data, create a reconciliation report that tracks what\'s missing.</p>
<p><strong>What the report shows:</strong></p>
<ul>
<li>Receipts uploaded, but not yet reconciled</li>
<li>Invoices sent, but not yet paid</li>
<li>Timesheets submitted, but not yet approved</li>
<li>Spreadsheets received, but not yet imported</li>
</ul>
<p><strong>How it helps:</strong></p>
<ul>
<li>You can see where the gaps are</li>
<li>You can follow up with finance (or your team) about missing items</li>
<li>The report itself documents the reconciliation process</li>
</ul>
<p><strong>Implementation:</strong></p>
<ol>
<li>
<p>Create a view that shows all receipts, invoices, and timesheets for a given period (this is just a reporting view)</p>
</li>
<li>
<p>Create a view that shows what\'s missing (by comparing finance data with your own records)</p>
</li>
<li>
<p>Share the report with finance (it shows them what they need to provide)</p>
</li>
</ol>
<hr />
<h2>The Conversation to Have with Finance</h2>
<p>Instead of asking finance to join your system, ask them:</p>
<blockquote>
<p><em>"We need to track project-level expenses by case code. What\'s the easiest way for us to get that data from you on a regular basis?"</em></p>
</blockquote>
<p><strong>Let them propose the solution.</strong> They\'ll likely suggest a periodic export (weekly, monthly, quarterly) in a specific format.</p>
<p><strong>If they propose the format, they\'ll be more likely to provide it consistently.</strong></p>
<hr />
<h2>The "Jar" Parallel</h2>
<p>The financial data is like the mystery jars in the kitchen:</p>
<ul>
<li>Some of it is old and no longer needed</li>
<li>Some of it is labeled poorly or not at all</li>
<li>Some of it is essential but hard to find</li>
<li>Some of it is duplicated in multiple places</li>
</ul>
<p><strong>The solution is the same:</strong></p>
<ol>
<li>Label everything clearly (placecodes, dates, categories)</li>
<li>Organize what you keep (staging tables, master tables)</li>
<li>Throw away what you don\'t need (archive or delete)</li>
</ol>
<hr />
<h2>Summary: What You Can Do</h2>
<table>
<thead>
<tr>
<th>Action</th>
<th>Effort</th>
<th>Impact</th>
</tr>
</thead>
<tbody>
<tr>
<td>Create a blank template for finance exports</td>
<td>Low</td>
<td>High</td>
</tr>
<tr>
<td>Build a conversion script for each finance partner</td>
<td>Medium</td>
<td>High</td>
</tr>
<tr>
<td>Use placecodes as the universal key</td>
<td>Low</td>
<td>High</td>
</tr>
<tr>
<td>Create a staging table for external data</td>
<td>Medium</td>
<td>High</td>
</tr>
<tr>
<td>Build a reconciliation report</td>
<td>Medium</td>
<td>Medium</td>
</tr>
<tr>
<td>Make it easy for finance to get what they need</td>
<td>Low</td>
<td>Medium</td>
</tr>
</tbody>
</table>
<hr />
<h2>Final Thought</h2>
<p>You\'re right—I don\'t have the answers. But I know this problem is common, and it\'s not a failure of your team or your partners. It\'s a failure of the systems we\'ve inherited.</p>
<p>The goal isn\'t perfection. The goal is reducing the friction.</p>
<p><strong>Every month, you\'ll get spreadsheets. Every month, you\'ll reconcile them. But over time, you\'ll get faster, more accurate, and less frustrated.</strong></p>',
);
