<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'navigate-help',
  'title' => 'How to Use This Help Library',
  'category' => 'sops',
  'category_name' => 'Standard Operating Procedures',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'How to Use This Help Library',
    'document_type' => 'User Guide',
    'version' => '1.0',
    'last_updated' => '2026-09-07',
    'author' => 'ARCHR Development Team',
    'audience' => 'All Platform Users',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '3',
    'tags' => 
    array (
      0 => 'help',
      1 => 'navigation',
      2 => 'documentation',
      3 => 'user-guide',
    ),
  ),
  'source' => 'sops\\navigate-help.md',
  'html' => '<h1>How to Use the ARCHR Help Library</h1>
<blockquote>
<p><strong>Who this is for:</strong> Everyone. If you\'re using the platform, this help system is for you.</p>
</blockquote>
<h2>What This Is</h2>
<p>The ARCHR Help Library is a collection of guides, SOPs, and reference documents built into the platform. It\'s organized by topic and role, so you can find what you need without wading through irrelevant material.</p>
<p><strong>Think of it as the platform\'s instruction manual.</strong> Except one you can search, and the index updates itself.</p>
<hr />
<h2>How to Get Here</h2>
<ul>
<li>From anywhere in the app, click <strong>Help</strong> in the navigation</li>
<li>Or go directly to <code>help.php</code></li>
<li>If you\'re not logged in, you can still see public documents (marked with a 🔓 icon)</li>
</ul>
<hr />
<h2>How It\'s Organized</h2>
<h3>By Category</h3>
<table>
<thead>
<tr>
<th>Category</th>
<th>Who It\'s For</th>
<th>What You\'ll Find</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Start Here</strong></td>
<td>Everyone</td>
<td>Welcome, overview, orientation</td>
</tr>
<tr>
<td><strong>ARCHR 101</strong></td>
<td>Everyone</td>
<td>How the system works, eligibility, funding</td>
</tr>
<tr>
<td><strong>Setting Up</strong></td>
<td>New coalitions</td>
<td>How to start a regional home repair program</td>
</tr>
<tr>
<td><strong>Technical Guides</strong></td>
<td>All users</td>
<td>Account setup, intake process, privacy</td>
</tr>
<tr>
<td><strong>SOPs</strong></td>
<td>Logged-in users</td>
<td>Step-by-step procedures for every role</td>
</tr>
<tr>
<td><strong>Roles &amp; Access</strong></td>
<td>Logged-in users</td>
<td>Who can do what, permission levels</td>
</tr>
<tr>
<td><strong>Funding &amp; Costs</strong></td>
<td>Everyone</td>
<td>Where the money comes from and how it flows</td>
</tr>
<tr>
<td><strong>Platform Anatomy</strong></td>
<td>Admins, Developers</td>
<td>Technical architecture, data flow</td>
</tr>
<tr>
<td><strong>For Developers</strong></td>
<td>Admins, Developers</td>
<td>Schema, code, deployment</td>
</tr>
<tr>
<td><strong>Coalition Feedback</strong></td>
<td>Logged-in users</td>
<td>Partner input, pain points, improvement plans</td>
</tr>
</tbody>
</table>
<h3>By Visibility</h3>
<table>
<thead>
<tr>
<th>Visibility</th>
<th>Who Can See It</th>
<th>Icon</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Public</strong></td>
<td>Anyone, even without an account</td>
<td>🔓</td>
</tr>
<tr>
<td><strong>Authenticated</strong></td>
<td>Any logged-in user</td>
<td>🔐</td>
</tr>
<tr>
<td><strong>Restricted</strong></td>
<td>Specific roles only</td>
<td>🔒</td>
</tr>
</tbody>
</table>
<hr />
<h2>How to Find What You Need</h2>
<h3>1. Browse by Category</h3>
<p>The left sidebar shows all categories and the documents in each. Click a category to expand it, then click a document title to read it.</p>
<h3>2. Search</h3>
<p>Use the search box at the top of the sidebar. Type any keyword — role name, topic, feature — and matching documents appear.</p>
<h3>3. Prev/Next Navigation</h3>
<p>At the bottom of each document, you\'ll find links to the previous and next documents in the same category. Great for reading through a whole section.</p>
<h3>4. Cross-References</h3>
<p>Documents link to related documents. If you\'re reading about assessments and need to know about document types, there\'s probably a link.</p>
<hr />
<h2>How to Read These Documents</h2>
<h3>SOPs (Standard Operating Procedures)</h3>
<p>SOPs follow a consistent format:</p>
<ol>
<li><strong>Who this is for</strong> — the target audience</li>
<li><strong>Why this matters</strong> — the context and stakes</li>
<li><strong>Step-by-step instructions</strong> — numbered or bulleted procedures</li>
<li><strong>Quick reference</strong> — a table of actions, locations, and who does them</li>
<li><strong>Common scenarios</strong> — real-world examples and edge cases</li>
</ol>
<h3>Technical Guides</h3>
<p>These go deeper into how things work under the hood. They may include:</p>
<ul>
<li>Database diagrams</li>
<li>Code snippets</li>
<li>Architecture explanations</li>
<li>Deployment instructions</li>
</ul>
<h3>User Guides</h3>
<p>These explain how to use specific features. They tend to be shorter and more task-oriented.</p>
<hr />
<h2>Troubleshooting &amp; FAQ</h2>
<h3>"I Forgot My Password"</h3>
<p>Contact your organization\'s Admin or the Super Admin. There is no self-service password reset yet — we\'re building it.</p>
<h3>"I Can\'t See a Case I Know Exists"</h3>
<p>Check your permissions. Cases are scoped to your organization unless you\'re an Admin or Super Admin. If you should have access but don\'t, contact your Admin.</p>
<h3>"The System Says I Don\'t Have Permission"</h3>
<p>Your role determines what you can see and do. If you need different permissions, ask your Admin to adjust your role.</p>
<h3>"Email Notifications Aren\'t Arriving"</h3>
<p>Check your spam folder. If they\'re not there, contact the Super Admin — the notification system may need attention.</p>
<h3>"How Do I Request a New Feature or Report a Bug?"</h3>
<p>Contact the Super Admin. Bug reports and feature requests are tracked and prioritized by the development team.</p>
<h3>"The System Is Down"</h3>
<p>If the platform is unavailable, contact your organization\'s Admin or the Super Admin. They\'ll have the most current status and estimated resolution time.</p>
<hr />
<h2>How This Library Is Built</h2>
<p>The help library is generated from markdown files in the <code>documentation/start-here/</code> directory. Each file needs a YAML frontmatter block at the top to be included. The generator (<code>app/generate-help-docs.php</code>) scans for files with frontmatter, converts them to HTML, and builds the navigation index.</p>
<p><strong>If you want to contribute documentation:</strong> Write it in markdown with the standard frontmatter format, place it in the appropriate subfolder of <code>documentation/start-here/</code>, and ask an Admin to regenerate the library.</p>
<hr />
<p><strong>Remember:</strong> If you can\'t find what you\'re looking for here, ask your Admin. If they can\'t help, the Super Admin is the next escalation point.</p>',
);
