<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'platforms-code',
  'title' => 'Current Platforms and The Great Code Migration',
  'category' => 'developers',
  'category_name' => 'For Developers',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Current Platforms and The Great Code Migration',
    'document_type' => 'Technical Overview',
    'version' => '1.0',
    'last_updated' => '2026-07-10',
    'author' => 'ARCHR Development Team',
    'audience' => 'Developers, System Administrators, Technical Leads',
    'complexity_level' => 'Advanced',
    'estimated_reading_minutes' => '5-7 minutes',
    'tags' => 
    array (
      0 => 'migration',
      1 => 'platforms',
      2 => 'softr',
      3 => 'airtable',
      4 => 'fillout',
      5 => 'postgresql',
    ),
  ),
  'source' => 'developers\\platforms-code.md',
  'html' => '<h3>Outline</h3>
<p><strong>1. The Current Stack (SaaS-Based)</strong></p>
<table>
<thead>
<tr>
<th>Platform</th>
<th>Purpose</th>
<th>Why We Started There</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Softr</strong></td>
<td>Frontend UI</td>
<td>Quick setup, no code, visual builder</td>
</tr>
<tr>
<td><strong>Airtable</strong></td>
<td>Database</td>
<td>Flexible schema, easy to modify</td>
</tr>
<tr>
<td><strong>Fillout</strong></td>
<td>Forms</td>
<td>Conditional logic, integrations</td>
</tr>
<tr>
<td><strong>Dropbox</strong></td>
<td>Document Storage</td>
<td>Simple file management</td>
</tr>
</tbody>
</table>
<p><strong>2. Why We\'re Migrating</strong></p>
<table>
<thead>
<tr>
<th>Issue</th>
<th>Impact</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Airtable Limits</strong></td>
<td>50,000 row limit per base, API rate limits</td>
</tr>
<tr>
<td><strong>No True Immutability</strong></td>
<td>Can\'t audit history properly</td>
</tr>
<tr>
<td><strong>Limited Role-Based Permissions</strong></td>
<td>Complex access control is hard</td>
</tr>
<tr>
<td><strong>No Native Ledger</strong></td>
<td>Progress tracking is built manually</td>
</tr>
<tr>
<td><strong>Integration Complexity</strong></td>
<td>Multiple platforms = multiple points of failure</td>
</tr>
<tr>
<td><strong>Cost</strong></td>
<td>SaaS costs scale with usage</td>
</tr>
<tr>
<td><strong>Vendor Lock-in</strong></td>
<td>Hard to move to other platforms</td>
</tr>
</tbody>
</table>
<p><strong>3. The Target Stack (Code-Based)</strong></p>
<table>
<thead>
<tr>
<th>Component</th>
<th>Technology</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Frontend</strong></td>
<td>HTML5, CSS, JavaScript</td>
<td>No dependency, works everywhere</td>
</tr>
<tr>
<td><strong>Backend</strong></td>
<td>PHP 8.1</td>
<td>Widely supported, good for APIs</td>
</tr>
<tr>
<td><strong>Database</strong></td>
<td>PostgreSQL</td>
<td>Full SQL, JSON support, row-level security</td>
</tr>
<tr>
<td><strong>Document Generation</strong></td>
<td>PHP libraries</td>
<td>PDF, DOCX generation</td>
</tr>
<tr>
<td><strong>Document Storage</strong></td>
<td>Dropbox/Z-Drive/S3</td>
<td>Flexible cloud storage</td>
</tr>
<tr>
<td><strong>Forms</strong></td>
<td>Fillout (phasing out) → Custom HTML/JS</td>
<td>Full control, no vendor lock</td>
</tr>
<tr>
<td><strong>UI</strong></td>
<td>Softr (phasing out) → Custom</td>
<td>Full control, mobile-first</td>
</tr>
</tbody>
</table>
<p><strong>4. Migration Phases</strong></p>
<table>
<thead>
<tr>
<th>Phase</th>
<th>Timeline</th>
<th>What Happens</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Phase 1: Database</strong></td>
<td>Complete</td>
<td>PostgreSQL schema designed and implemented</td>
</tr>
<tr>
<td><strong>Phase 2: Backend API</strong></td>
<td>In Progress</td>
<td>PHP API endpoints built</td>
</tr>
<tr>
<td><strong>Phase 3: Document System</strong></td>
<td>In Progress</td>
<td>Document generation + bucket integration</td>
</tr>
<tr>
<td><strong>Phase 4: Task Engine</strong></td>
<td>In Progress</td>
<td>Immutable ledger, Quick Add</td>
</tr>
<tr>
<td><strong>Phase 5: Frontend</strong></td>
<td>Not Started</td>
<td>Custom HTML/CSS/JS interfaces</td>
</tr>
<tr>
<td><strong>Phase 6: Migration</strong></td>
<td>Not Started</td>
<td>Data migration from Airtable to PostgreSQL</td>
</tr>
</tbody>
</table>
<p><strong>5. What Data is Moving</strong></p>
<table>
<thead>
<tr>
<th>Source</th>
<th>Target</th>
<th>Priority</th>
</tr>
</thead>
<tbody>
<tr>
<td>Intake Submissions</td>
<td><code>intake_submissions</code></td>
<td>High</td>
</tr>
<tr>
<td>Case Data</td>
<td><code>cases</code></td>
<td>High</td>
</tr>
<tr>
<td>Financial Records</td>
<td><code>invoices</code>, <code>funding_sources</code></td>
<td>High</td>
</tr>
<tr>
<td>Documents</td>
<td>Document Bucket</td>
<td>High</td>
</tr>
<tr>
<td>User Accounts</td>
<td><code>system_users</code></td>
<td>High</td>
</tr>
<tr>
<td>Assessments</td>
<td><code>property_assessments</code></td>
<td>Medium</td>
</tr>
<tr>
<td>Communications</td>
<td><code>case_communications</code></td>
<td>Medium</td>
</tr>
<tr>
<td>Volunteer Records</td>
<td><code>volunteer_profiles</code></td>
<td>Medium</td>
</tr>
</tbody>
</table>
<p><strong>6. What Stays the Same</strong></p>
<ul>
<li>
<p>The folder structure (document-storage.md)</p>
</li>
<li>
<p>Document naming convention</p>
</li>
<li>
<p>Role definitions and permissions</p>
</li>
<li>
<p>The six-phase workflow</p>
</li>
<li>
<p>Eligibility criteria</p>
</li>
</ul>
<p><strong>7. What Gets Better</strong></p>
<ul>
<li>
<p><strong>Performance</strong>: Faster queries, real-time updates</p>
</li>
<li>
<p><strong>Audit Trail</strong>: Complete, immutable history</p>
</li>
<li>
<p><strong>Flexibility</strong>: Can modify any part of the system</p>
</li>
<li>
<p><strong>Cost</strong>: No per-user/per-record fees</p>
</li>
<li>
<p><strong>Control</strong>: Full ownership of data and code</p>
</li>
<li>
<p><strong>Scalability</strong>: No row limits, unlimited growth</p>
</li>
</ul>
<p><strong>8. Migration Timeline</strong></p>
<ul>
<li>
<p><strong>Current State</strong>: Softr + Airtable + Fillout</p>
</li>
<li>
<p><strong>Q2-Q3 2026</strong>: Backend migration complete</p>
</li>
<li>
<p><strong>Q4 2026</strong>: Frontend migration begins</p>
</li>
<li>
<p><strong>Q1 2027</strong>: Full migration complete</p>
</li>
<li>
<p><strong>Q2 2027</strong>: Sunset SaaS platforms</p>
</li>
</ul>
<p><strong>9. How Developers Can Prepare</strong></p>
<ul>
<li>
<p>Learn PostgreSQL (the target database)</p>
</li>
<li>
<p>Understand the schema mappings</p>
</li>
<li>
<p>Review the API documentation</p>
</li>
<li>
<p>Get familiar with the codebase (GitHub)</p>
</li>
<li>
<p>Test with the staging environment</p>
</li>
</ul>',
);
