<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'progress-task-doccode-docact-completion-map',
  'title' => 'Progress Task to DocCode × DocAct Completion Map',
  'category' => 'developers',
  'category_name' => 'For Developers',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Progress Task to DocCode × DocAct Completion Map',
    'document_type' => 'Technical Reference',
    'version' => '1.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'Developers, Admins',
    'complexity_level' => 'Advanced',
    'estimated_reading_minutes' => '8',
    'tags' => 
    array (
      0 => 'progress-tasks',
      1 => 'completion-mapping',
      2 => 'airtable',
    ),
    'visibility' => 
    array (
      0 => 'admin',
      1 => 'super-admin',
    ),
  ),
  'source' => 'developers\\progress-task-doccode-docact-completion-map.md',
  'html' => '<h1>Progress Task to DocCode x DocAct Completion Map</h1>
<p>Sources:</p>
<ul>
<li><code>C:\\Users\\bwyatt\\Downloads\\⚙️Progress Tasks-⚙️Progress Tasks CSV.csv</code></li>
<li><code>C:\\Users\\bwyatt\\Downloads\\🔷Tables-docs.csv</code></li>
<li><a href="help.php?doc=progress-tracker">progress-tracker.md</a></li>
<li><a href="document-classification-doc-types.md">document-classification-doc-types.md</a></li>
</ul>
<p>This document identifies which <code>DocCode x DocAct</code> combinations should be expected before document-related progress tasks can be inferred as complete.</p>
<p>The progress task CSV only includes <code>Task Title</code>, <code>phaseTaskNum</code>, and <code>Role</code>. It does not include the actual linked DocCode records. The mapping below therefore uses expected DocCode families derived from the task title, and the canonical DocAct slots exposed by the docs table:</p>
<ul>
<li><code>act0</code></li>
<li><code>act1</code></li>
<li><code>act2</code></li>
<li><code>actDest</code></li>
<li><code>actFin</code></li>
</ul>
<h2>Completion Rule</h2>
<p>For progress inference, use this default rule:</p>
<blockquote>
<p>A document-related progress task is complete when the project has a linked document with the expected <code>DocCode</code>, and the document has a positive/final <code>DocAct</code> event appropriate to that task.</p>
</blockquote>
<p>The exact final action can vary by DocCode, but the expected slots are:</p>
<table>
<thead>
<tr>
<th>DocAct slot</th>
<th>Expected meaning for completion inference</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>act0</code></td>
<td>Requirement/request exists. Usually not enough to complete a task by itself.</td>
</tr>
<tr>
<td><code>act1</code></td>
<td>File exists, was uploaded, or generated draft exists. Enough for collection/upload tasks.</td>
</tr>
<tr>
<td><code>act2</code></td>
<td>File was submitted for review or moved into an intermediate review step. Usually not enough for verification/approval tasks.</td>
</tr>
<tr>
<td><code>actDest</code></td>
<td>Review decision or destination action, such as approve, reject, request revision, or route to another step. Positive <code>actDest</code> can complete approval/verification tasks; negative <code>actDest</code> completes rejection tasks but should not satisfy the underlying required document.</td>
</tr>
<tr>
<td><code>actFin</code></td>
<td>Final accepted/signed/complete state. This is the safest completion signal for documents that require approval, signature, or closeout.</td>
</tr>
</tbody>
</table>
<h2>DocCode x DocAct Matrix</h2>
<table>
<thead>
<tr>
<th>Progress task</th>
<th style="text-align: right;">Phase</th>
<th>Role availability</th>
<th>Expected DocCode family</th>
<th>DocAct needed to infer this task complete</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>0. Submission: Application Submitted</code></td>
<td style="text-align: right;"><code>.0</code></td>
<td></td>
<td>Application / intake submission</td>
<td><code>act1</code> or source submission event</td>
<td>If represented as a file/form artifact, the application DocCode only needs evidence of submission/presence.</td>
</tr>
<tr>
<td><code>1. Intake: Collect Income Documents</code></td>
<td style="text-align: right;"><code>1.4</code></td>
<td>Admin</td>
<td>Income documents</td>
<td><code>act1</code></td>
<td>Collection is complete when required income document files are present, not necessarily verified.</td>
</tr>
<tr>
<td><code>1. Intake: Collect Ownership Documents</code></td>
<td style="text-align: right;"><code>1.4</code></td>
<td>Admin</td>
<td>Ownership documents</td>
<td><code>act1</code></td>
<td>Collection is complete when required ownership/home documents are present.</td>
</tr>
<tr>
<td><code>2. Processing: Verify Income Documents</code></td>
<td style="text-align: right;"><code>2.1</code></td>
<td>Admin</td>
<td>Income documents</td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
<td>Verification requires approval/acceptance, not just upload. Rejection/question/revision events should keep this incomplete.</td>
</tr>
<tr>
<td><code>2. Processing: Verify Ownership Documents</code></td>
<td style="text-align: right;"><code>2.1</code></td>
<td>Admin</td>
<td>Ownership documents</td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
<td>Same pattern as income verification.</td>
</tr>
<tr>
<td><code>2. Processing: Collect Program Specific Paperwork</code></td>
<td style="text-align: right;"><code>2.1</code></td>
<td></td>
<td>Program-specific accepted documentation</td>
<td><code>act1</code> for collection; <code>actFin</code> if the program requires review</td>
<td>Use partner-program accepted documentation linked from DocCode.</td>
</tr>
<tr>
<td><code>2. Processing: Upload Before Photos</code></td>
<td style="text-align: right;"><code>2.2.1</code></td>
<td>Assessor</td>
<td>Before photos</td>
<td><code>act1</code> or <code>actFin</code></td>
<td>If photo DocCodes do not require review, upload/presence is enough.</td>
</tr>
<tr>
<td><code>2. Processing: Create Assessment Report</code></td>
<td style="text-align: right;"><code>2.3</code></td>
<td>Assessor</td>
<td>Assessment report</td>
<td><code>act1</code> if generated/uploaded; <code>actFin</code> if reviewed</td>
<td>Generated report should link to project and assessment context.</td>
</tr>
<tr>
<td><code>2. Processing: Create Repair Task List</code></td>
<td style="text-align: right;"><code>2.4</code></td>
<td>Project Manager</td>
<td>Repair task list</td>
<td><code>act1</code> or <code>actFin</code></td>
<td>If the task list drives later work, prefer final/accepted state.</td>
</tr>
<tr>
<td><code>2. Processing: Create Project Scope of Work</code></td>
<td style="text-align: right;"><code>2.4.2</code></td>
<td>Project Manager</td>
<td>Project scope of work / SOW</td>
<td><code>act1</code> for draft created; <code>actFin</code> if scope approval is required</td>
<td>Scope is a generated/structured document artifact.</td>
</tr>
<tr>
<td><code>2. Processing: Upload Subcontractor Estimate</code></td>
<td style="text-align: right;"><code>2.4.3</code></td>
<td>Subcontractor, Project Manager</td>
<td>Subcontractor quote/estimate</td>
<td><code>act1</code></td>
<td>Upload task is complete on file presence. Later approval is a separate task.</td>
</tr>
<tr>
<td><code>2. Processing: Determine Project Budget</code></td>
<td style="text-align: right;"><code>2.5</code></td>
<td>Crew Lead, Project Manager</td>
<td>Project budget / estimate summary</td>
<td><code>act1</code> or <code>actFin</code></td>
<td>Budget may be calculated rather than a document; only require DocCode if stored as a budget artifact.</td>
</tr>
<tr>
<td><code>3. Planning: Create Contract</code></td>
<td style="text-align: right;"><code>3.3</code></td>
<td>Project Manager, Admin</td>
<td>Contract</td>
<td><code>act1</code></td>
<td>Draft/generated contract exists. Do not require signature here.</td>
</tr>
<tr>
<td><code>3. Planning: Approve Contract</code></td>
<td style="text-align: right;"><code>3.3.1</code></td>
<td>Project Manager, Admin</td>
<td>Contract</td>
<td>positive <code>actDest</code></td>
<td>Approval decision completes this task. Signed contract is separate.</td>
</tr>
<tr>
<td><code>3. Planning: Reject Contract</code></td>
<td style="text-align: right;"><code>3.3.1</code></td>
<td>Project Manager, Admin</td>
<td>Contract</td>
<td>negative/destructive <code>actDest</code></td>
<td>Completes the rejection task but should not mark contract requirement satisfied.</td>
</tr>
<tr>
<td><code>3. Planning: Sign Contract</code></td>
<td style="text-align: right;"><code>3.4</code></td>
<td>Project Manager, Admin</td>
<td>Signed contract</td>
<td><code>actFin</code></td>
<td>Requires signature/final event. The docs CSV has <code>ContractSignedEvent</code> on subcontractor/application document records.</td>
</tr>
<tr>
<td><code>3. Planning: Create Initial Materiasl List</code></td>
<td style="text-align: right;"><code>3.5.1</code></td>
<td>Project Manager, Crew Lead, Crew Member</td>
<td>Initial materials list</td>
<td><code>act1</code></td>
<td>Task is complete when the list artifact exists.</td>
</tr>
<tr>
<td><code>3. Planning: Reject Subcontractor Estimate</code></td>
<td style="text-align: right;"><code>3.5.1</code></td>
<td>Project Manager, Admin</td>
<td>Subcontractor quote/estimate</td>
<td>negative/destructive <code>actDest</code></td>
<td>Completes rejection task only. Should not satisfy estimate approval.</td>
</tr>
<tr>
<td><code>3. Planning: Approve Subcontractor Estimate</code></td>
<td style="text-align: right;"><code>3.5.1</code></td>
<td>Project Manager, Admin</td>
<td>Subcontractor quote/estimate</td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
<td>Approval state should be explicit; upload alone is not enough.</td>
</tr>
<tr>
<td><code>4. Project: Create Scope of Work Change Order</code></td>
<td style="text-align: right;"><code>4.0</code></td>
<td>Crew Lead, Project Manager, Admin</td>
<td>Scope of work change order</td>
<td><code>act1</code> for created; <code>actFin</code> if approval required</td>
<td>If change orders require signoff, use final accepted action.</td>
</tr>
<tr>
<td><code>4. Project: Perform Final Walkthrough</code></td>
<td style="text-align: right;"><code>4.4</code></td>
<td>Crew Lead, Crew Member, Project Manager, Admin</td>
<td>Final walkthrough checklist/report</td>
<td><code>act1</code> or <code>actFin</code></td>
<td>If the walkthrough includes signoff, use final action.</td>
</tr>
<tr>
<td><code>4. Project: Sign Completion</code></td>
<td style="text-align: right;"><code>4.5</code></td>
<td>Crew Lead, Crew Member, Project Manager</td>
<td>Completion certificate / signed completion</td>
<td><code>actFin</code></td>
<td>Final signed completion document should be required.</td>
</tr>
<tr>
<td><code>4. Project: Upload After Photos</code></td>
<td style="text-align: right;"><code>4.6</code></td>
<td>Crew Lead, Crew Member, Project Manager</td>
<td>After photos</td>
<td><code>act1</code> or <code>actFin</code></td>
<td>Upload/presence is usually sufficient unless review is required.</td>
</tr>
<tr>
<td><code>4. Project: Upload Progress Photos</code></td>
<td style="text-align: right;"><code>4.10.2</code></td>
<td>Crew Lead, Crew Member</td>
<td>Progress photos</td>
<td><code>act1</code></td>
<td>Upload task completes on file presence.</td>
</tr>
<tr>
<td><code>4. Project: Fill Timesheet</code></td>
<td style="text-align: right;"><code>4.10.3</code></td>
<td>Crew Member</td>
<td>Timesheet</td>
<td><code>act1</code> or <code>actFin</code></td>
<td>If timesheets require approval, final/approved action should complete payroll/reporting tasks.</td>
</tr>
<tr>
<td><code>4. Project: Code Receipts</code></td>
<td style="text-align: right;"><code>4.11</code></td>
<td>Crew Lead, Crew Member</td>
<td>Receipts / material receipts</td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
<td>Coding implies classification/review, not merely upload.</td>
</tr>
<tr>
<td><code>4. Project: Sign In Volunteers</code></td>
<td style="text-align: right;"><code>4.12.1</code></td>
<td>Crew Lead</td>
<td>Volunteer sign-in sheet</td>
<td><code>act1</code> or <code>actFin</code></td>
<td>Presence is likely enough unless volunteer hours require approval.</td>
</tr>
<tr>
<td><code>4. Project: Create Subcontractor Change Order</code></td>
<td style="text-align: right;"><code>4.13</code></td>
<td>Crew Lead, Project Manager, Admin</td>
<td>Subcontractor change order</td>
<td><code>act1</code> for created; <code>actFin</code> if approval/signature required</td>
<td>Treat like scope/change order artifact.</td>
</tr>
<tr>
<td><code>4. Project: Approve Subcontractor Invoice</code></td>
<td style="text-align: right;"><code>4.13.1</code></td>
<td>Project Manager</td>
<td>Subcontractor invoice</td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
<td>Invoice must be approved/accepted, not only uploaded.</td>
</tr>
<tr>
<td><code>5. Report: Record Actual Material Expenses</code></td>
<td style="text-align: right;"><code>5.1</code></td>
<td>Project Manager, Admin</td>
<td>Receipts / material expense records</td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
<td>Completion requires coded/accepted expense evidence.</td>
</tr>
<tr>
<td><code>5. Report: Record Actual Labor Expenses</code></td>
<td style="text-align: right;"><code>5.1</code></td>
<td>Project Manager, Admin</td>
<td>Timesheets / labor expense records</td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
<td>Completion requires accepted labor evidence.</td>
</tr>
<tr>
<td><code>5. Report: Record Actual Subcontractor Expenses</code></td>
<td style="text-align: right;"><code>5.2</code></td>
<td>Project Manager, Admin</td>
<td>Subcontractor invoice / subcontractor expense records</td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
<td>Completion requires accepted invoice/expense evidence.</td>
</tr>
<tr>
<td><code>5. Report: Complete ARCHR Draw Request Workbook</code></td>
<td style="text-align: right;"><code>5.3</code></td>
<td>Admin</td>
<td>ARCHR draw request workbook</td>
<td><code>actFin</code></td>
<td>Reporting closeout should require final generated/uploaded workbook.</td>
</tr>
</tbody>
</table>
<h2>Universal DocAct Expectations by Task Verb</h2>
<p>Use this when adding new document-related progress tasks:</p>
<table>
<thead>
<tr>
<th>Task verb/pattern</th>
<th>Expected DocAct slot</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>Collect ... Documents</code></td>
<td><code>act1</code></td>
</tr>
<tr>
<td><code>Upload ...</code></td>
<td><code>act1</code></td>
</tr>
<tr>
<td><code>Create ...</code></td>
<td><code>act1</code>, or <code>actFin</code> when approval/signature is built into the artifact</td>
</tr>
<tr>
<td><code>Verify ... Documents</code></td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
</tr>
<tr>
<td><code>Approve ...</code></td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
</tr>
<tr>
<td><code>Reject ...</code></td>
<td>negative/destructive <code>actDest</code>; do not satisfy the underlying required document</td>
</tr>
<tr>
<td><code>Sign ...</code></td>
<td><code>actFin</code></td>
</tr>
<tr>
<td><code>Code ...</code></td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
</tr>
<tr>
<td><code>Record Actual ... Expenses</code></td>
<td>positive <code>actDest</code> or <code>actFin</code></td>
</tr>
<tr>
<td><code>Complete ... Workbook</code></td>
<td><code>actFin</code></td>
</tr>
</tbody>
</table>
<h2>Inference Logic</h2>
<pre><code class="language-mermaid">flowchart TD
    A["Progress task requires document evidence"] --&gt; B["Find expected DocCode family"]
    B --&gt; C["Find project-linked file/document"]
    C --&gt; D{"DocCode matches?"}
    D --&gt;|"No"| X["Do not infer complete"]
    D --&gt;|"Yes"| E["Read linked Doc Events"]
    E --&gt; F{"Expected DocAct present?"}
    F --&gt;|"Upload/collect task: act1"| G["Infer complete"]
    F --&gt;|"Review/approve task: positive actDest or actFin"| G
    F --&gt;|"Sign/final task: actFin"| G
    F --&gt;|"Reject task: negative actDest"| H["Infer rejection task complete only"]
    F --&gt;|"Missing or wrong action"| X
    H --&gt; I["Underlying document remains unsatisfied"]</code></pre>
<h2>Recommended Key</h2>
<p>For Progress V2 completion records, use a deterministic key shaped like:</p>
<pre><code class="language-text">{projectRecordId}:{phaseTaskId}:{docCodeId}:{docActId}</code></pre>
<p>For collection tasks where any one of several accepted documents can satisfy a requirement, include the accepted-document group:</p>
<pre><code class="language-text">{projectRecordId}:{phaseTaskId}:{docRequirementGroup}:{docCodeId}:{docActId}</code></pre>
<p>This prevents a rejected contract from completing the signed contract task, and prevents an uploaded estimate from completing the estimate approval task.</p>
<h2>Items That Need Record-Level Confirmation</h2>
<p>The table above should be treated as the expected policy layer until the actual DocCode and DocAct records are exported. The next confirmation pass should verify:</p>
<ol>
<li>Actual <code>DocCode.docCode</code> values for each expected family.</li>
<li>Actual <code>DocAct.docEventCode</code> values for positive approval, negative rejection, revision requested, signed, uploaded, generated, and final accepted.</li>
<li>Which DocCodes have <code>[⚙️Progress Tasks] Complete When Present</code>.</li>
<li>Which DocCodes have <code>actFin_DONE</code>, <code>destAct_DONE</code>, or other final-state rollups.</li>
<li>Which tasks are intentionally completed by non-document events despite having document evidence nearby.</li>
</ol>',
);
