<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'progress-tracker',
  'title' => 'Progress Event Tracking V2',
  'category' => 'platform-anatomy',
  'category_name' => 'Platform Anatomy',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Progress Event Tracking V2',
    'document_type' => 'Technical Reference',
    'version' => '2.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'Admins, Super-Admins, Developers',
    'complexity_level' => 'Advanced',
    'estimated_reading_minutes' => '15',
    'tags' => 
    array (
      0 => 'progress-tracker',
      1 => 'events',
      2 => 'automation',
      3 => 'airtable',
    ),
    'visibility' => 
    array (
      0 => 'admin',
      1 => 'super-admin',
    ),
  ),
  'source' => 'platform-anatomy\\progress-tracker.md',
  'html' => '<h1>Progress Event Tracking V2</h1>
<p>Source: <code>C:\\Users\\bwyatt\\Downloads\\🔷Tables-progress tracker.csv</code>, exported from <code>[P] ARCHR Progress Tracker</code>.</p>
<p>This document describes the V2 progress event process as inferred from the table inventory, field names, linked-record fields, views, and automation trigger metadata in the progress tracker base. Where behavior depends on automation/script bodies that are not in the CSV, the document labels the behavior as inferred.</p>
<h2>Purpose</h2>
<p>Progress tracking V2 turns user actions, sync records, migrated V1 events, and automation-generated events into canonical project progress records.</p>
<p>The V2 process separates four concerns that were blended together in V1:</p>
<table>
<thead>
<tr>
<th>Concern</th>
<th>Main table</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr>
<td>Raw/canonical event record</td>
<td><code>🔷[◼️Project Event V2]</code></td>
<td>Capture inbound event payloads, parse them, resolve intent, and link evidence/actors/project context.</td>
</tr>
<tr>
<td>Project/task completion fact</td>
<td><code>🔷[☑️Project Task Completion]</code></td>
<td>Store the durable fact that a project task was completed, skipped, inferred, or otherwise resolved.</td>
</tr>
<tr>
<td>Task catalog and dependency rules</td>
<td><code>🔶[⚙️Progress Tasks]</code></td>
<td>Define phase tasks, event lookup keys, completion scopes, autocomplete rules, triggers, required evidence, and parent/child task relationships.</td>
</tr>
<tr>
<td>Resolver queue</td>
<td><code>🔷[🔮Queue V2]</code></td>
<td>Coordinate multi-step event resolution, chained/autocomplete writes, retries, lock state, and audit/error state.</td>
</tr>
</tbody>
</table>
<h2>Core Tables</h2>
<table>
<thead>
<tr>
<th>Table</th>
<th style="text-align: right;">Table ID</th>
<th>Role in V2</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>🔶[🎯 Sync]</code></td>
<td style="text-align: right;"><code>tbl4HhGi7F6lKzhfB</code></td>
<td>Project-level hub. Links project records to V2 events, task completions, queue records, checklists, claims, and setup.</td>
</tr>
<tr>
<td><code>🔷[◼️Project Event]</code></td>
<td style="text-align: right;"><code>tblJpKhigM6vcRiwm</code></td>
<td>Legacy/V1 event table and bridge. Contains migration views such as <code>toV2</code>, <code>toV2 copy</code>, and <code>🟣 V2 Migration Queue</code>.</td>
</tr>
<tr>
<td><code>🔷[◼️Project Event V2]</code></td>
<td style="text-align: right;"><code>tblOhnfdIlabxXOqL</code></td>
<td>V2 event inbox and canonical event log. Automation views: <code>🟡 Needs Parse</code> and <code>🟣 Needs Resolve</code>.</td>
</tr>
<tr>
<td><code>🔷[☑️Project Task Completion]</code></td>
<td style="text-align: right;"><code>tbl1mIQg2utmj7Vqt</code></td>
<td>Normalized completion records linked to project, event, and progress task.</td>
</tr>
<tr>
<td><code>🔷[🔮Queue V2]</code></td>
<td style="text-align: right;"><code>tblr1T9FrTtqMefV7</code></td>
<td>Resolver work queue linked to <code>🎯 Sync</code>.</td>
</tr>
<tr>
<td><code>🔶[⚙️Progress Tasks]</code></td>
<td style="text-align: right;"><code>tblECgtClvoenWXJn</code></td>
<td>Canonical task definitions and event lookup mapping.</td>
</tr>
<tr>
<td><code>🔷_EVENT_LOOKUP_PIVOT_</code></td>
<td style="text-align: right;"><code>tbl4Uf5fAdiBUIE2C</code></td>
<td>V1-style lookup bridge between project events and progress tasks. Still useful as migration/reference context.</td>
</tr>
<tr>
<td><code>🔷[🧭Interface Action Map]</code></td>
<td style="text-align: right;"><code>tblDyFlcFI2816ZQu</code></td>
<td>Interface-to-event registry: action keys, event lookup, event type, phase task ID, roles, prerequisites, blocking rules, and idempotency mode.</td>
</tr>
</tbody>
</table>
<h2>Data Model</h2>
<pre><code class="language-mermaid">erDiagram
    PROJECT_SYNC ||--o{ PROJECT_EVENT_V2 : "has events"
    PROJECT_SYNC ||--o{ TASK_COMPLETION : "has completions"
    PROJECT_SYNC ||--o{ QUEUE_V2 : "has resolver jobs"
    PROJECT_SYNC ||--o{ CHECKLIST : "has checklist"

    PROJECT_EVENT_V1 ||--o{ PROJECT_EVENT_V2 : "migrates/bridges"
    PROJECT_EVENT_V2 ||--o{ TASK_COMPLETION : "creates/links"
    PROJECT_EVENT_V2 }o--o{ PROGRESS_TASK : "resolves to task"
    TASK_COMPLETION }o--|| PROGRESS_TASK : "completes"

    PROGRESS_TASK ||--o{ EVENT_LOOKUP_PIVOT : "defines lookup"
    PROJECT_EVENT_V1 ||--o{ EVENT_LOOKUP_PIVOT : "legacy mapping"
    INTERFACE_ACTION_MAP }o--|| PROGRESS_TASK : "maps action to phaseTaskId"

    PROJECT_SYNC {
      string airtable_table "🔶[🎯 Sync]"
      string id "projectRecordId / id(⚓🎯)"
    }

    PROJECT_EVENT_V2 {
      string airtable_table "🔷[◼️Project Event V2]"
      string eventKey
      string eventType
      string parseStatus
      string resolveStatus
      string chainId
      string sourceTable
      string sourceRecordId
    }

    TASK_COMPLETION {
      string airtable_table "🔷[☑️Project Task Completion]"
      string completionKey
      string completionSource
      string status
      date completedDate
      string phaseTaskId
    }

    PROGRESS_TASK {
      string airtable_table "🔶[⚙️Progress Tasks]"
      string EVENT_LOOKUP
      string completionScope
      string autocompleteRuleJSON
      string triggers
    }

    QUEUE_V2 {
      string airtable_table "🔷[🔮Queue V2]"
      string status
      boolean lock
      string resolverRunId
      string pendingEventsJSON
      string processedEventsJSON
    }</code></pre>
<h2>Event Lifecycle</h2>
<pre><code class="language-mermaid">flowchart TD
    A["Event source&lt;br/&gt;Softr action, Airtable sync row, V1 event, automation, claim/checklist action"] --&gt; B["Create or link&lt;br/&gt;🔷[◼️Project Event V2]"]
    B --&gt; C{"parseStatus"}
    C --&gt;|"Needs Parse view"| D["Automation: 🟪🟡Parse"]
    D --&gt; E["Populate normalized fields&lt;br/&gt;eventJSON, eventLookupJSON, eventLookupText,&lt;br/&gt;eventProjectId, actor IDs, partnerJSON,&lt;br/&gt;eventEvidenceJSON, eventDisplayJSON"]
    E --&gt; F{"resolveStatus"}
    F --&gt;|"Needs Resolve view"| G["Automation: 🟪🟣Resolve Intent"]
    G --&gt; H["Match intent to progress task&lt;br/&gt;via eventLookupText / phaseTaskId / Interface Action Map / task rules"]
    H --&gt; I{"Creates completion?"}
    I --&gt;|"Yes"| J["Write 🔷[☑️Project Task Completion]"]
    I --&gt;|"Needs chain / autocomplete"| K["Write or update 🔷[🔮Queue V2]"]
    K --&gt; L["Automation on 🎯 Sync view&lt;br/&gt;🔮Resolve Event Queue"]
    L --&gt; G
    J --&gt; M["Roll up to 🔶[🎯 Sync], 🔶[⚙️Progress Tasks], checklist/current phase views"]
    G --&gt;|"Skipped / blocked / error"| N["Set resolveStatus + error / resolverRunId for audit"]</code></pre>
<h3>1. Event Intake</h3>
<p>V2 event intake appears to come from several places:</p>
<table>
<thead>
<tr>
<th>Source pattern</th>
<th>Evidence in CSV</th>
</tr>
</thead>
<tbody>
<tr>
<td>Project-level actions</td>
<td><code>🔶[🎯 Sync]</code> has event-oriented views such as <code>addSubmissionEvent</code>, <code>🔮Add to Queue</code>, <code>🔮Resolve Event Queue</code>, <code>Create [🏁Checklist Record]</code>, <code>💛UPDATE_CLAIM</code>, and multiple <code>[🎯&gt;🏁&gt;...] Sync</code> views.</td>
</tr>
<tr>
<td>Legacy/V1 event migration</td>
<td><code>🔷[◼️Project Event]</code> has <code>toV2</code>, <code>toV2 copy</code>, and <code>🟣 V2 Migration Queue</code> views, and links to <code>[◼️Project Event V2]</code>.</td>
</tr>
<tr>
<td>Checklist actions</td>
<td><code>🔷[🏁✔️Checklist Items]</code> has <code>Marked Complete</code> views and completion fields; V2 completions link back to <code>🎯 Sync</code> and <code>⚙️Progress Tasks</code>.</td>
</tr>
<tr>
<td>Domain sync tables</td>
<td>Tables such as <code>🔶[✅Sync]</code>, <code>🔶[🔍Sync]</code>, <code>🔷[💬Sync]</code>, and <code>🔷[🪧Sync]</code> have <code>Create Project Event</code> or <code>Create Progress Event</code> views and <code>_EVENT_LOOKUP_</code> / <code>_EVENT_DATE_</code> fields.</td>
</tr>
<tr>
<td>Interface actions</td>
<td><code>🔷[🧭Interface Action Map]</code> stores <code>actionKey</code>, <code>eventLookup</code>, <code>eventType</code>, <code>phaseTaskId</code>, prerequisites, blockers, evidence rules, and idempotency mode.</td>
</tr>
</tbody>
</table>
<p>The canonical V2 event record stores both raw and resolved data:</p>
<ul>
<li>Raw/source: <code>rawInboundJSON</code>, <code>sourceTable</code>, <code>sourceRecordId</code>, <code>sourceEventId</code>, <code>sourceUrl</code>, <code>datasource</code>, <code>sessionId</code>.</li>
<li>Event identity: <code>eventKey</code>, <code>eventType</code>, <code>eventDate</code>, <code>chainId</code>, <code>triggeredByEventKey</code>, <code>triggeredByPhaseTaskId</code>.</li>
<li>Project/actor context: linked <code>[🎯 Sync]</code>, <code>[💜Orgs]</code>, <code>[💜People]</code>, <code>🪝Claims</code>, <code>actorOrgId</code>, <code>actorPersonId</code>, <code>actorRole</code>, <code>eventProjectId</code>.</li>
<li>Parsed/resolved payloads: <code>eventJSON</code>, <code>eventLookupJSON</code>, <code>eventLookupText</code>, <code>eventDisplayJSON</code>, <code>eventEvidenceJSON</code>, <code>eventResolutionJSON</code>, <code>partnerJSON</code>, <code>writeListJSON</code>.</li>
<li>Workflow state: <code>parse</code>, <code>parseStatus</code>, <code>resolve</code>, <code>resolveStatus</code>, <code>resolverRunId</code>, <code>error</code>.</li>
</ul>
<h3>2. Parse</h3>
<p>The <code>🔷[◼️Project Event V2]</code> table has a <code>🟡 Needs Parse</code> view wired to automation <code>🟪🟡Parse</code>.</p>
<p>Parse normalizes the event into structured V2 fields. Inferred responsibilities:</p>
<ol>
<li>Read <code>rawInboundJSON</code> plus source metadata.</li>
<li>Determine <code>eventKey</code>, <code>eventType</code>, <code>eventDate</code>, and <code>eventProjectId</code>.</li>
<li>Produce lookup payloads: <code>eventLookupJSON</code> and <code>eventLookupText</code>.</li>
<li>Extract display/evidence payloads into <code>eventDisplayJSON</code> and <code>eventEvidenceJSON</code>.</li>
<li>Link known project, org, person, claim, and V1 event records when possible.</li>
<li>Set <code>parseStatus</code> to parsed, skipped, or error.</li>
</ol>
<h3>3. Resolve Intent</h3>
<p>The same V2 table has a <code>🟣 Needs Resolve</code> view wired to automation <code>🟪🟣Resolve Intent</code>.</p>
<p>Resolve translates a parsed event into one or more write intents:</p>
<pre><code class="language-mermaid">flowchart LR
    A["Parsed V2 event"] --&gt; B["Resolve lookup"]
    B --&gt; C["🔶[⚙️Progress Tasks]&lt;br/&gt;EVENT_LOOKUP / phaseTaskId / triggers"]
    B --&gt; D["🔷[🧭Interface Action Map]&lt;br/&gt;actionKey / eventLookup / idempotency"]
    C --&gt; E["Completion write intent"]
    D --&gt; E
    E --&gt; F["🔷[☑️Project Task Completion]"]
    E --&gt; G["🔷[🔮Queue V2]&lt;br/&gt;when chained/autocomplete work remains"]</code></pre>
<p>Resolution uses task and action metadata:</p>
<ul>
<li><code>⚙️Progress Tasks.EVENT_LOOKUP</code> and <code>eventLookupNormalized</code> map event labels to phase tasks.</li>
<li><code>⚙️Progress Tasks.completionScope</code> defines what counts as complete.</li>
<li><code>⚙️Progress Tasks.autocompleteRuleJSON</code>, <code>Triggers Completion Of</code>, <code>triggers</code>, <code>triggerEvent</code>, and <code>TriggeredEvents</code> define chained completion logic.</li>
<li><code>⚙️Progress Tasks.requiresEvidence</code> controls whether an event can complete the task without supporting evidence.</li>
<li><code>Interface Action Map.phaseTaskId</code> maps product actions directly to phase tasks.</li>
<li><code>Interface Action Map.requiresCompletedPhaseTaskIdsJSON</code> and <code>blocksIfCompletedPhaseTaskIdsJSON</code> provide workflow gating.</li>
<li><code>Interface Action Map.idempotencyMode</code> describes duplicate/retry handling for an action.</li>
</ul>
<h3>4. Completion Write</h3>
<p>The durable outcome of resolution is a record in <code>🔷[☑️Project Task Completion]</code>.</p>
<p>Important completion fields:</p>
<table>
<thead>
<tr>
<th>Field</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>[🎯 Sync]</code></td>
<td>Project this completion belongs to.</td>
</tr>
<tr>
<td><code>[◼️Project Event V2]</code></td>
<td>Event that created or justified this completion.</td>
</tr>
<tr>
<td><code>[⚙️Progress Tasks]</code></td>
<td>Phase task completed by the event.</td>
</tr>
<tr>
<td><code>completionKey</code></td>
<td>Idempotency key for the project/task/event completion fact.</td>
</tr>
<tr>
<td><code>completionSource</code></td>
<td>Indicates whether the completion came from the source event or autocomplete/inference. Views include <code>completionSource="source"</code> and <code>completionSource="autocomplete"</code>.</td>
</tr>
<tr>
<td><code>status</code></td>
<td>Completion state. Likely supports active/complete/skipped/error-style statuses depending on resolver output.</td>
</tr>
<tr>
<td><code>completedDate</code></td>
<td>Effective completion date.</td>
</tr>
<tr>
<td><code>completedByEventKey</code> / <code>completedByEventRecordId</code></td>
<td>Trace back to the creating event.</td>
</tr>
<tr>
<td><code>resolverRunId</code></td>
<td>Trace back to the resolver execution.</td>
</tr>
<tr>
<td><code>rawEventJSON</code>, <code>eventLookupText</code>, <code>partnerJSON</code>, <code>notes</code></td>
<td>Audit and reporting context.</td>
</tr>
</tbody>
</table>
<p>The key V2 design choice is that progress is not only inferred from the latest event row. It is materialized as explicit completion facts, which can be rolled up, audited, deduped, and displayed.</p>
<h3>5. Queue and Chained Resolution</h3>
<p><code>🔷[🔮Queue V2]</code> stores resolver work at the project level. The table links to <code>[🎯 Sync]</code> and includes:</p>
<ul>
<li><code>status</code></li>
<li><code>lock</code></li>
<li><code>currentLevel</code></li>
<li><code>chainId</code></li>
<li><code>projectRecordId</code></li>
<li><code>resolverRunId</code></li>
<li><code>pendingEventsJSON</code></li>
<li><code>processedEventsJSON</code></li>
<li><code>startedAt</code></li>
<li><code>finishedAt</code></li>
<li><code>lastError</code></li>
</ul>
<p>The <code>🔶[🎯 Sync]</code> table has resolver views/automations:</p>
<ul>
<li><code>🔮Add to Queue</code></li>
<li><code>🔮Has WRITE_LIST</code></li>
<li><code>🔮Resolve Event Queue</code> -&gt; automation <code>🟪🔮Resolve Queue</code></li>
<li><code>🔮Set Next Try</code></li>
<li><code>🔮ResetTrigger</code></li>
</ul>
<p>Inferred queue process:</p>
<pre><code class="language-mermaid">sequenceDiagram
    participant Event as Project Event V2
    participant Resolver as Resolve Intent
    participant Queue as Queue V2
    participant Project as 🎯 Sync
    participant Completion as Project Task Completion

    Event-&gt;&gt;Resolver: parsed event enters Needs Resolve
    Resolver-&gt;&gt;Completion: write source completion(s)
    Resolver-&gt;&gt;Queue: enqueue pending autocomplete / triggered events
    Queue-&gt;&gt;Project: link queue item to project
    Project-&gt;&gt;Resolver: Resolve Event Queue automation runs
    Resolver-&gt;&gt;Completion: write autocomplete completion(s)
    Resolver-&gt;&gt;Queue: append processedEventsJSON, update currentLevel/status
    Queue--&gt;&gt;Project: finishedAt or lastError</code></pre>
<p>The queue gives V2 a controlled place for cascading writes. This matters because completing one phase task can imply downstream completions, unlock another action, or generate follow-up events.</p>
<h2>V2 State Machine</h2>
<pre><code class="language-mermaid">stateDiagram-v2
    [*] --&gt; Created
    Created --&gt; NeedsParse: rawInboundJSON/source fields written
    NeedsParse --&gt; Parsed: 🟪🟡Parse succeeds
    NeedsParse --&gt; ParseError: parse fails
    NeedsParse --&gt; ParseSkipped: event not actionable

    Parsed --&gt; NeedsResolve
    NeedsResolve --&gt; Resolved: 🟪🟣Resolve Intent writes completions
    NeedsResolve --&gt; Queued: resolver creates pending write list
    NeedsResolve --&gt; ResolveSkipped: gated, duplicate, or non-completing event
    NeedsResolve --&gt; ResolveError: resolver fails

    Queued --&gt; ResolvingQueue: 🎯 Sync / 🔮Resolve Event Queue
    ResolvingQueue --&gt; Resolved: all pending events processed
    ResolvingQueue --&gt; ResolveError: lastError set

    Resolved --&gt; [*]
    ParseSkipped --&gt; [*]
    ResolveSkipped --&gt; [*]</code></pre>
<h2>Idempotency and Deduping</h2>
<p>V2 appears to rely on explicit keys instead of only Airtable links:</p>
<ul>
<li><code>eventKey</code> identifies the event.</li>
<li><code>completionKey</code> identifies the completion fact.</li>
<li><code>chainId</code> groups related events in a resolver chain.</li>
<li><code>sourceTable</code> + <code>sourceRecordId</code> + <code>sourceEventId</code> trace back to the origin.</li>
<li><code>completedByEventKey</code> + <code>completedByEventRecordId</code> preserve the write source.</li>
<li><code>Interface Action Map.idempotencyMode</code> tells the resolver how repeated UI/actions should be treated.</li>
</ul>
<p>Recommended rule: a project should not receive two active <code>☑️Project Task Completion</code> records with the same <code>completionKey</code> unless the status model explicitly supports superseded/reversed completion records.</p>
<h2>Reporting and Rollups</h2>
<p>The V2 model supports reporting through links and rollups:</p>
<ul>
<li><code>🎯 Sync</code> links to <code>[◼️Project Event V2]</code>, <code>[☑️Project Task Completion]</code>, <code>[🔮Queue V2]</code>, <code>[🏁Checklist]</code>, <code>completeCountTable</code>, and <code>🕰️FQ Table</code>.</li>
<li><code>⚙️Progress Tasks</code> links to <code>[☑️Project Task Completion]</code> and has rollup fields such as <code>[🎯 Sync] Rollup</code>.</li>
<li><code>🏁Checklist</code> and checklist item records surface current phase/task status for human workflow.</li>
<li><code>completeCountTable</code> remains a bridge for count-style completion reporting, especially where V1 project events are still involved.</li>
</ul>
<h2>V1 to V2 Bridge</h2>
<p>V1 is still present in the model:</p>
<ul>
<li><code>🔷[◼️Project Event]</code> has migration and compatibility views: <code>toV2</code>, <code>toV2 copy</code>, <code>🟣 V2 Migration Queue</code>, <code>New Events</code>, <code>anyComplete</code>, <code>completionEvidence</code>, <code>update [🏁Progress]</code>.</li>
<li><code>🔷_EVENT_LOOKUP_PIVOT_</code> links V1 <code>Project Event</code> records to <code>⚙️Progress Tasks</code>.</li>
<li><code>🔶[🎯 Sync]</code> still contains rollups/fields for <code>[⬛] Project Event</code>, <code>_EVENT_LOOKUP_PIVOT_</code>, <code>[🟥Status Changes]</code>, and v1 status updates.</li>
</ul>
<p>The practical migration path is:</p>
<ol>
<li>Keep V1 project events as source/audit records.</li>
<li>Create corresponding <code>Project Event V2</code> records from V1 migration views.</li>
<li>Parse and resolve V2 records.</li>
<li>Materialize completions in <code>Project Task Completion</code>.</li>
<li>Prefer V2 completions for new progress calculations; use V1 pivots only for backfill/compatibility until retired.</li>
</ol>
<h2>Operational Checklist</h2>
<p>Use this checklist when debugging progress tracking:</p>
<ol>
<li>Find the project in <code>🔶[🎯 Sync]</code>.</li>
<li>Check linked <code>🔷[◼️Project Event V2]</code> records.</li>
<li>If an event did not process, inspect <code>parseStatus</code>, <code>resolveStatus</code>, <code>error</code>, <code>rawInboundJSON</code>, and <code>eventLookupText</code>.</li>
<li>If parse is pending, check whether the record is in <code>🟡 Needs Parse</code>.</li>
<li>If resolve is pending, check whether the record is in <code>🟣 Needs Resolve</code>.</li>
<li>If a chained action is missing, check linked <code>🔷[🔮Queue V2]</code> records for <code>status</code>, <code>lock</code>, <code>pendingEventsJSON</code>, <code>processedEventsJSON</code>, and <code>lastError</code>.</li>
<li>If progress is not showing complete, check <code>🔷[☑️Project Task Completion]</code> for the expected <code>completionKey</code>, <code>phaseTaskId</code>, <code>[⚙️Progress Tasks]</code> link, and <code>[🎯 Sync]</code> link.</li>
<li>If the event cannot match a task, inspect <code>🔶[⚙️Progress Tasks].EVENT_LOOKUP</code>, <code>eventLookupNormalized</code>, <code>phaseTaskId</code>, and related <code>🔷[🧭Interface Action Map]</code> records.</li>
</ol>
<h2>Open Questions</h2>
<p>These need automation/script bodies or sample records to confirm:</p>
<ul>
<li>Exact allowed values for <code>parseStatus</code>, <code>resolveStatus</code>, <code>completionSource</code>, queue <code>status</code>, and completion <code>status</code>.</li>
<li>Whether <code>completionKey</code> is enforced by automation, Airtable constraints, or resolver logic only.</li>
<li>How reversals/withdrawals are represented: negative event, superseded completion, status change, or deletion.</li>
<li>Whether <code>writeListJSON</code> is authoritative for queue writes or a diagnostic artifact.</li>
<li>Which V1 event types are still active versus migration-only.</li>
</ul>',
);
