<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'project-cost',
  'title' => 'The Money Trail — Funding Flow & Project Costs',
  'category' => 'funding',
  'category_name' => 'Funding & Costs',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'The Money Trail — Funding Flow & Project Costs',
    'document_type' => 'Financial Reference',
    'version' => '1.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'All Platform Users, Bursars, Admins',
    'complexity_level' => 'Intermediate',
    'estimated_reading_minutes' => '3',
    'tags' => 
    array (
      0 => 'funding',
      1 => 'finance',
      2 => 'grants',
      3 => 'project-cost',
    ),
  ),
  'source' => 'funding\\project cost.md',
  'html' => '<p>getting money - way before anyone submits an application
grants, fund development, applies for funding - timeline completely totally random, inconsistent from one to next.
Get approved by funder: CISCO, Land of Sky, Dogwood Trust, City Funds, VOAD - Volunteer organizations assisting disaster
Habitat accountants and finance team - move received funds to ARCHR account
THEN
some things happen
Projects are completed by partner organizations
partner organizations submits draw request
who handles? <em>an office worker</em> compiles receipts, invoices, timesheets, and fills out draw request workbook
Habitat grants team reviews completed draw request workbook. 
If is all good -&gt; Habitat finance cuts check
If is all bad -&gt; lots of bullshit, goes back for review/tweaks</p>
<p>INTERNALLY</p>
<p>Jenny &amp; Cassidy determine how to layer funding sources to pay for projects</p>
<p>Multiple buckets of money analogy
bucket 1 : need red hair to qualify
bucket b: need to be 6 foot tall or morer to qualify
square bucket: must live in a blue house to qualify
default to most restrictive - bad thing</p>',
);
