<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'roles-and-access-levels',
  'title' => 'Roles & Access Levels — Who Sees What in ARCHR',
  'category' => 'sops',
  'category_name' => 'Standard Operating Procedures',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Roles & Access Levels — Who Sees What in ARCHR',
    'document_type' => 'Standard Operating Procedure',
    'version' => '1.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'Admins, Super-Admins, Organizational Administrators',
    'complexity_level' => 'Intermediate',
    'estimated_reading_minutes' => '8',
    'tags' => 
    array (
      0 => 'roles',
      1 => 'permissions',
      2 => 'access',
      3 => 'SOP',
    ),
    'visibility' => 'authenticated',
  ),
  'source' => 'sops\\roles-and-access-levels.md',
  'html' => '<h2>Decision 1 — What\'s the default landing view per role?</h2>
<p>The question: When an Admin / PM / Crew / Volunteer logs into Archer, what\'s the first thing they see, and in what layout?</p>
<p>What Softr offers for collection views:</p>
<ul>
<li>
<p>List (with sub-layouts: cards, small cards, timeline, inbox)</p>
</li>
<li>
<p>Grid (image-forward cards)</p>
</li>
<li>
<p>Table (spreadsheet, dense scanning)</p>
</li>
<li>
<p>Kanban (column-grouped board, drag-to-update)</p>
</li>
<li>
<p>Calendar (date-anchored)</p>
</li>
<li>
<p>Map (location-anchored)</p>
</li>
<li>
<p>Org chart (hierarchical, niche)</p>
</li>
</ul>
<p>Sub-layout call-outs:</p>
<ul>
<li>
<p>Inbox layout (Pro plan+) — left sidebar list, right pane shows the selected item\'s details. Strong fit for triage/queue work where users process items one at a time. Worth prototyping for the triage queue.</p>
</li>
<li>
<p>Timeline (Business plan+) — vertical date-anchored list. Useful for activity history.</p>
</li>
</ul>
<p>Patrick\'s starting recommendation:</p>
<ul>
<li>
<p>Admin → Inbox layout for triage; Table view available as a secondary tab for bulk review</p>
</li>
<li>
<p>PM → Kanban grouped by phase as primary; List as secondary</p>
</li>
<li>
<p>Crew → List (cards) filtered to "my assigned work this week"</p>
</li>
<li>
<p>Volunteer → List (cards) filtered to "available to claim"</p>
</li>
</ul>
<p>Need from Ben: Confirm role priorities, push back where the work pattern is different from what I\'m assuming.  </p>
<table>
<thead>
<tr>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td>Role Priority Hierarchy (top 3)</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Role</td>
<td>1st</td>
<td>2nd</td>
<td>3rd</td>
</tr>
<tr>
<td>Admin</td>
<td>Confirm Eligibility</td>
<td>Contact/Schedule</td>
<td>Edit Triage</td>
</tr>
<tr>
<td>Notes:</td>
<td>Filter: Confirmed Eligible!=✅  <br>List: sorted by Triage 9-1, Date1-9</td>
<td>List: sorted by Triage 9-1, Date1-9, last Contact:9-1</td>
<td>List: sorted by Triage 9-1, Date1-9  <br>Automatic Triage will sort “New Applicant List” and will</td>
</tr>
<tr>
<td>Project Manager</td>
<td>Active Projects</td>
<td>Upcoming Projects</td>
<td>Past Projects</td>
</tr>
<tr>
<td>Notes</td>
<td>Filter: Projects Status = Active  <br>Cards:</td>
<td>Filter: Confirmed Eligible=✅, Status!=Active|Closed</td>
<td>Status=Closed</td>
</tr>
<tr>
<td>Crew</td>
<td>Add Notes, Photos, Timesheets, Mark Repair Tasks Complete</td>
<td>Review Upcoming Projects</td>
<td>Review Past Projects</td>
</tr>
<tr>
<td>Notes</td>
<td>Details: Mobile Friendly</td>
<td>Cards: Mobile Friendly</td>
</tr>
<tr>
<td>Volunteer</td>
<td>See Upcoming Projects</td>
<td>Review Past Projects</td>
<td>Set Preferences</td>
</tr>
<tr>
<td>Notes</td>
<td>No PII, No Address until Signed In</td>
<td>Scope of Work, Site Lead, Dates, Notes</td>
<td>Set Liked&amp;Disliked Trades/Tasks, Emergency Contacts, Dietary Restrictions, etc</td>
</tr>
</tbody>
</table>
<p>Level 11: ARCHR SuperAdmin
Primary Responsibilities: Oversee system and platform, monitor bug reporting, documentation, and live support as needed.
Information Access: Everything
Action Permissions: Everything</p>
<pre><code>↓</code></pre>
<p>Level 10: Admin (Full system access)
Primary Responsibilities: System configuration, user management, org settings, eligibility rules
Information Access: Full system access within organization
Action Permissions: CRUD all records, manage users, configure rules</p>
<pre><code>↓</code></pre>
<p>Level 9:  Project Manager (Oversees projects)
Primary Responsibilities: Oversees multiple projects, budget tracking, timeline management
Information Access: All projects within organization, budgets, timelines, subcontractor quotes
Action Permissions: Approve estimates, manage budget, coordinate resources</p>
<pre><code>↓</code></pre>
<p>Level 8:  Bursar (Financial - separate track)
Primary Responsibilities: Financial management, payments, invoicing, funding tracking
Information Access: Financial data, payments, invoices, funding sources
Action Permissions: Process payments, create invoices, track expenses</p>
<pre><code>↓</code></pre>
<p>Level 7:  Caseworker (Manages cases)
Primary Responsibilities: Primary point of contact, manages, applicant communication, coordinates services
Information Access: All cases assigned to their org, applicant contact info
Action Permissions: Update case status, communicate with applicants, request additional information</p>
<pre><code>↓</code></pre>
<p>Level 6:  Assessor (Technical evaluation)
Primary Responsibilities: Conducts home visits, evaluates repair needs, creates estimates
Information Access: Case files assigned to them, property details
Action Permissions: View cases, add assessments, upload photos, create estimates</p>
<pre><code>↓</code></pre>
<p>Level 5:  Crew Lead (On-site supervision)
Primary Responsibilities: Manages on-site repair crew, schedules work, ensures quality
Information Access: Active repair projects, crew assignments, materials list
Action Permissions: Assign crew members, update work progress, request materials</p>
<pre><code>↓</code></pre>
<p>Level 4:  Subcontractor (Specialized trade)
Primary Responsibilities: External trade specialist (plumbing, electrical, etc.)
Information Access: Specific repair categories assigned to them
Action Permissions: View assigned repairs, submit quotes, report completion</p>
<pre><code>↓</code></pre>
<p>Level 3:  Envoy (Community support)
Primary Responsibilities: Community Liaison, outreach, applicant support
Information Access: Basic case information, applicant contact information
Action Permissions: View case status, add notes, assist applicants with forms</p>
<p>Organizational and program specific, not really project oriented</p>
<pre><code>↓</code></pre>
<p>Level 2:  Crew Member (Physical work)
Primary Responsibilities: Performs actual repair work
Information Access: Daily assignments, task lists, safety information, hour logging
Action Permissions: View tasks, mark complete, report issues</p>
<pre><code>↓</code></pre>
<p>Level 1:  Requestor (Application only)
Primary Responsibilities: Submits initial intake application, uploads documents
Information Access: Own submissions only
Action Permissions: Create, vew own, edit until submitted</p>
<pre><code>↓</code></pre>
<p>Level 0:  Volunteer (Limited assistance)
Primary Responsibilities: Unpaid helpers, supervised by Crew Lead
Information Access: Limited task assignments, safety information
Action Permissions: View assigned tasks, log hours</p>',
);
