<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'schema-mapping',
  'title' => 'Schema Mapping and Database - The Flow of Data',
  'category' => 'developers',
  'category_name' => 'For Developers',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Schema Mapping and Database - The Flow of Data',
    'document_type' => 'Technical Reference',
    'version' => '1.0',
    'last_updated' => '2026-07-10',
    'author' => 'ARCHR Development Team',
    'audience' => 'Developers, Database Administrators, Technical Leads',
    'complexity_level' => 'Advanced',
    'estimated_reading_minutes' => '8-12 minutes',
    'tags' => 
    array (
      0 => 'database',
      1 => 'schema',
      2 => 'data-flow',
      3 => 'postgresql',
      4 => 'relationships',
    ),
  ),
  'source' => 'developers\\schema-mapping.md',
  'html' => '<h3>Outline</h3>
<p><strong>1. Database Overview</strong></p>
<ul>
<li>
<p>PostgreSQL (target), currently Airtable</p>
</li>
<li>
<p>40+ tables organized by domain</p>
</li>
<li>
<p>Row-level security for multi-organization isolation</p>
</li>
<li>
<p>Immutable ledger for audit trail</p>
</li>
<li>
<p>Materialized views for reporting</p>
</li>
</ul>
<p><strong>2. Core Domain Tables</strong></p>
<table>
<thead>
<tr>
<th>Domain</th>
<th>Key Tables</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Users &amp; Roles</strong></td>
<td><code>system_users</code>, <code>roles</code>, <code>permissions</code>, <code>user_role_assignments</code></td>
<td>Authentication, authorization</td>
</tr>
<tr>
<td><strong>Applications</strong></td>
<td><code>intake_submissions</code>, <code>submission_repair_categories</code>, <code>submission_household_attributes</code></td>
<td>Intake data</td>
</tr>
<tr>
<td><strong>Cases</strong></td>
<td><code>cases</code>, <code>case_statuses</code>, <code>case_status_history</code></td>
<td>Case lifecycle</td>
</tr>
<tr>
<td><strong>Progress</strong></td>
<td><code>progress_ledger</code></td>
<td>Immutable task log</td>
</tr>
<tr>
<td><strong>Tasks</strong></td>
<td><code>task_definitions</code>, <code>work_tasks</code>, <code>task_status_history</code></td>
<td>Task management</td>
</tr>
<tr>
<td><strong>Work Orders</strong></td>
<td><code>work_orders</code>, <code>project_assignments</code></td>
<td>Repair projects</td>
</tr>
<tr>
<td><strong>Assessments</strong></td>
<td><code>property_assessments</code>, <code>repair_estimates</code></td>
<td>Property inspections</td>
</tr>
<tr>
<td><strong>Documents</strong></td>
<td><code>case_documents</code>, <code>document_templates</code></td>
<td>Document management</td>
</tr>
<tr>
<td><strong>Finance</strong></td>
<td><code>case_funding</code>, <code>invoices</code>, <code>reimbursement_requests</code>, <code>funding_sources</code></td>
<td>Financial tracking</td>
</tr>
<tr>
<td><strong>Communications</strong></td>
<td><code>case_communications</code></td>
<td>Message logging</td>
</tr>
<tr>
<td><strong>Scheduling</strong></td>
<td><code>scheduled_events</code>, <code>applicant_availability</code></td>
<td>Calendar management</td>
</tr>
</tbody>
</table>
<p><strong>3. The Immutable Ledger Table</strong></p>
<ul>
<li>
<p><code>progress_ledger</code> - The single source of truth</p>
</li>
<li>
<p>INSERT only, never UPDATE or DELETE</p>
</li>
<li>
<p>Every change is a new row</p>
</li>
<li>
<p>Provides complete audit trail</p>
</li>
<li>
<p>Powers all metrics and reporting</p>
</li>
</ul>
<p><strong>4. Key Relationships</strong></p>
<p>text</p>
<p>User → Role → Permission (Many-to-Many)
User → Organization (Many-to-One)
Intake Submission → Case (One-to-One)
Case → Work Orders (One-to-Many)
Work Order → Tasks (One-to-Many)
Case → Documents (One-to-Many)
Case → Funding (One-to-Many)
Progress Ledger → Everything (Immutable Reference)</p>
<p><strong>5. Data Flow Diagrams</strong></p>
<p><strong>Application to Case:</strong></p>
<p>text</p>
<p>Intake Submission → Eligibility Check → Case Created → Status: PENDING</p>
<p><strong>Task Creation:</strong></p>
<p>text</p>
<p>Quick Add → Progress Ledger (New Row) → Task Definition → Task Metrics Updated</p>
<p><strong>Document Generation:</strong></p>
<p>text</p>
<p>Task Complete → Document Generated → File Stored in Bucket → Document Table → Ledger Updated</p>
<p><strong>6. Key Views for Reporting</strong></p>
<table>
<thead>
<tr>
<th>View</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>case_funding_summary</code></td>
<td>Per-case funding status</td>
</tr>
<tr>
<td><code>reimbursement_aging</code></td>
<td>Invoice aging report</td>
</tr>
<tr>
<td><code>funding_source_summary</code></td>
<td>Grant utilization</td>
</tr>
<tr>
<td><code>duplicate_case_alerts</code></td>
<td>Overlap detection</td>
</tr>
<tr>
<td><code>current_tasks</code></td>
<td>Active task list</td>
</tr>
<tr>
<td><code>task_metrics</code></td>
<td>Dashboard metrics</td>
</tr>
<tr>
<td><code>project_status_view</code></td>
<td>Project health</td>
</tr>
<tr>
<td><code>staff_review_queue</code></td>
<td>Application queue</td>
</tr>
</tbody>
</table>
<p><strong>7. Row-Level Security (RLS)</strong></p>
<p>sql</p>
<p>-- Example: Users only see their organization\'s data
CREATE POLICY org_access_policy ON cases
USING (organization_id = current_setting(\'app.current_org_id\')::INTEGER);
-- Example: Users only see their assigned cases
CREATE POLICY caseworker_access_policy ON cases
USING (assigned_to = current_user_id());</p>
<p><strong>8. Migration from Airtable to PostgreSQL</strong></p>
<table>
<thead>
<tr>
<th>Airtable Concept</th>
<th>PostgreSQL Equivalent</th>
</tr>
</thead>
<tbody>
<tr>
<td>Base → Database</td>
<td>Database</td>
</tr>
<tr>
<td>Table → Table</td>
<td>Table</td>
</tr>
<tr>
<td>Record → Row</td>
<td>Row</td>
</tr>
<tr>
<td>Field → Column</td>
<td>Column</td>
</tr>
<tr>
<td>View → Materialized View</td>
<td>Materialized View</td>
</tr>
<tr>
<td>Linked Record → Foreign Key</td>
<td>Foreign Key</td>
</tr>
<tr>
<td>Formula → Computed Column</td>
<td>Generated Column</td>
</tr>
<tr>
<td>Automation → Trigger/Function</td>
<td>PL/pgSQL Function</td>
</tr>
</tbody>
</table>
<p><strong>9. Query Examples</strong></p>
<p>sql</p>
<p>-- Get active cases with funding status
SELECT <em> FROM case_funding_summary WHERE status NOT IN (\'completed\', \'denied\');
-- Get overdue reimbursement requests
SELECT </em> FROM reimbursement_aging WHERE days_aging &gt; 30;
-- Get duplicate alerts
SELECT <em> FROM duplicate_case_alerts ORDER BY detected_at DESC;
-- Get task metrics for dashboard
SELECT </em> FROM task_metrics;
-- Get all progress for a case
SELECT * FROM progress_ledger WHERE case_id = 123 ORDER BY event_timestamp DESC;</p>
<p><strong>10. Schema Documentation</strong></p>
<ul>
<li>
<p>All tables documented with comments</p>
</li>
<li>
<p>Fields have descriptions</p>
</li>
<li>
<p>Relationships have foreign key constraints</p>
</li>
<li>
<p>Views have purpose statements</p>
</li>
<li>
<p>Functions have usage examples</p>
</li>
</ul>',
);
