<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'setting-up',
  'title' => 'Setting up a Regional Home Repair Coalition',
  'category' => 'setting-up',
  'category_name' => 'Setting Up',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Setting up a Regional Home Repair Coalition',
    'document_type' => 'Introduction',
    'version' => '1.0',
    'last_updated' => '2026-07-17',
    'author' => 'ARCHR Development Team',
    'audience' => 'All Platform Users (Requestors, Volunteers, Crew, Assessors, Subcontractors, Caseworkers, Project Managers, Bursars, Admins)',
    'complexity_level' => 'Advanced',
    'estimated_reading_minutes' => '6-10 minutes',
    'tags' => 
    array (
      0 => 'tasks',
      1 => 'logs',
      2 => 'events',
      3 => 'documentation',
      4 => 'SOP',
    ),
  ),
  'source' => 'setting-up\\index.md',
  'html' => '<p>Alright, so you want to start your own local home repair coalition? You wish to set up the frameworks and systems, before a natural disaster strikes your region. </p>
<p>This platform is open-source and licensed under GNU - General Public License. This guarantees end users the freedom to run, study, share, or modify the software. However; if you distribute a derivative work or modification, you must provide the source code to those recipients under the same or equivalent license terms.</p>
<p>What that means: This software has an [open repository you can find here]. You are free to download and run with this as long as you are helping people and not repurposing out of it\'s original intention or selling it for profit.</p>
<p>Even with the source code, you will need a few skillsets and resources to set up. </p>
<ul>
<li>First you will need private web hosting. If you are partnering with local groups, someone may have web hosting they are willing to share.</li>
<li>Second, you will need to be comfortable working in a code repository to get this set up and running. You will need to import a database script file and configure a workspace to work with on the back-end.</li>
<li>Third, you will need a team. Of individuals. Of groups. Organizations. Non-profits. Businesses. Local Government, even. Be ready to write grants and solicit funders. Have evidence and documentation of your work.</li>
</ul>
<p>This isn\'t easy. It\'s not a simple download. It\'s blood, sweat, and tears. And it\'s lots of fun when you make it into a game that helps your neighbors.</p>
<p>And even with all of this, you may need to reach out to our development team for assistance. </p>
<p>We are available for basic support requests and for anything more than that, contracting to help you establish your local home repair fronts. </p>
<p>We can help modify the source code into a branch that is more particular to your local needs and infrastructure.</p>
<p>For now, there is more documentation and support pages on how you can get started, forming partnerships, soliciting financial support for home repairs, and delegating volunteer and staff crew teams.</p>',
);
