<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'start-here',
  'title' => 'Welcome to the Asheville Regional Coalition for Home Repair (ARCHR) Platform',
  'category' => 'start-here',
  'category_name' => 'Start Here',
  'visibility' => 'public',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Welcome to the Asheville Regional Coalition for Home Repair (ARCHR) Platform',
    'document_type' => 'Introduction',
    'version' => '1.0',
    'last_updated' => '2026-07-10',
    'author' => 'ARCHR Development Team',
    'audience' => 'All Platform Users (Requestors, Volunteers, Crew, Assessors, Subcontractors, Caseworkers, Project Managers, Bursars, Admins)',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '1-2 minutes',
    'tags' => 
    array (
      0 => 'tasks',
      1 => 'logs',
      2 => 'events',
      3 => 'documentation',
      4 => 'SOP',
    ),
  ),
  'source' => 'start-here.md',
  'html' => '<p>Welcome to the Asheville Regional Coalition for Home Repair\'s Help section. If you find yourself on here, you may be an employee, contractor, administrator, volunteer, or simply someone exploring in the future how this system works.</p>
<p>On September 28, 2024, our region was devastated by Hurricane Helene. Homes were completely uprooted in an instant. Many, many trees fell. We experienced, especially in our valleys and riverbound areas, flooding of up to 20 feet. We were not prepared for the level of complete destruction, nor would there have been any way to prepare. </p>
<p>In the aftermath, we saw neighbors organizing and meeting each other, like never before. And making sure that others were taken care of. The worst of a natural disaster brought out the best in people helping people. </p>
<p>Our coalition will cover disaster-related home repairs for qualifying households. Up to 50,000 dollars in  </p>
<p>This generosity extended to the level of non-profit institutions getting funding and forming partnership to enable projects like this. </p>
<p>Hurricane Helene was deemed a 10,000 year probability natural disaster and described in it\'s damages and devastation as \'biblical.\' We are seeing more and more of these extreme catastrophic natural disasters around the world. We wanted to take the system we built, and automate it with a platform. </p>
<p>Some aspirations with this tool:</p>
<ul>
<li>Create an automated system for every day people and organizations to provide aid after a natural disaster.</li>
<li>Have this tool be known about before a natural disaster comes to your region. </li>
<li>Make the process of mutual care after devastation some level of fun and game-like. There is nothing fun about the devastation and loss after a disaster, or repairing damaged roofing and drywall. But we believe game-ifying helping our neighbors survive the aftermath of a storm can bring out the best in us.</li>
</ul>
<p>Our existing home repair coalition is made possible by donors and partners, such as Cisco, Land of Sky, Habitat for Humanity, Community Housing Coalition of Madison County, PODER Emma....</p>
<p>Here are some helpful support documents you might be interested in reading next:</p>
<ul>
<li><a href="help.php?doc=archr101">How does this platform work? ARCHR 101 - Dummy Proof Edition</a> - An overview of how this system works, from repair application, to completed home repair. </li>
<li><a href="help.php?doc=eligibility">Who Qualifies? Eligibility Determination &amp; Assuming Eligibility till proven otherwise</a> - Our process assumes eligibility until proven otherwise. Eligibility is based on income, home ownership, cause of damage, demographics, and geography.</li>
<li><a href="help.php?doc=metrics-math-money">Metrics, Math, and Money - How we make this all possible</a> - How donors, organizations, and everyday people who give a damn, make this all possible.</li>
</ul>
<p>Here\'s some more technical support items on how to get started:</p>
<ul>
<li>
<p><a href="help.php?doc=making-an-account">How do I make an account?</a> - The short answer is, you don\'t. There is not an option to register an account because that is not how this works. If you are in need of a home repair, you complete an intake form, and an account will be made for you at the end to track the status of your application. If you are looking to volunteer with us, we have a form for that as well that will generate a volunteer account. If you are a representative, employee, or administrator with a participating organization, we will make your accounts for you. For the public, there is a demo account you can log onto with placeholder data, so you can explore how the platform works. <a href="help.php?doc=making-an-account">Read more here</a></p>
</li>
<li>
<p><a href="help.php?doc=open-source-home-repair">This project is open-source - You can start one in your region before a disaster hits.</a> - As we develop, we are building an open source repository. This project is copylefted under <a href="https://opensource.org/license/gpl-3.0">GNU - General Public License</a>. This allows others access to the code and freedom to change and modify, as long as the project is being used for it\'s original intention. This repository is under construction, and not available publicly yet. But if you are interested in once it is available, you can sign up for our news list. <a href="help.php?doc=open-source-home-repair">Read more here</a></p>
</li>
<li>
<p><a href="help.php?doc=intake-privacy">What information do I need to provide in an intake for home repair assistance?</a> - To confirm eligibility, and to process an intake, we need certain information from applicants. Our goal is to only require the bare minimum information, and to not require more than that. Your privacy is important, and sometimes the less information we have on a private household, the better. But we do need to keep track of who lives there, who owns the home, the demographics data, household income, and geography. We will not share your private household information with law enforcement without a warrant, or with data brokers and ad agencies. Everything you share as an applicant is Protected and Privileged Information (PPI) under the [Privacy Act of 1974?].</p>
</li>
</ul>
<p>For Developers and Technicians:</p>
<ul>
<li><a href="help.php?doc=system-anatomy">Anatomy of a Home Repair Platform</a> - Here\'s the different parts and systems of how this works under the hood!</li>
<li><a href="help.php?doc=platforms-code">Current Platforms and The Great Code Migration</a> - ARCHR is built on several software as a service platforms. We are actively migrating to a shareable code-based solution built on HTML5, PHP 8.1, JavaScript, and PostgreSQL. <a href="help.php?doc=platforms-code">Learn More Here</a></li>
<li><a href="help.php?doc=schema-mapping">Schema-Mapping and Database - Mapping the flow of data</a> - This is how it works on the back-end.  </li>
</ul>',
);
