<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'submission',
  'title' => 'Application',
  'category' => 'developers',
  'category_name' => 'For Developers',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Application',
    'document_type' => 'Technical Specification',
    'version' => '1.0',
    'last_updated' => '2024-12-10',
    'author' => 'ARCHR Development Team',
    'contributors' => 'Product Owner, Database Architect',
    'status' => 'Ready for Implementation',
    'review_date' => '2024-12-17',
    'audience' => 'Developers, Database Administrators, System Architects',
    'complexity_level' => 'Intermediate to Advanced',
    'estimated_reading_minutes' => '30',
    'tags' => 
    array (
      0 => 'workflow',
      1 => 'postgresql',
      2 => 'triggers',
      3 => 'notifications',
      4 => 'eligibility',
    ),
  ),
  'source' => 'developers\\submission.md',
  'html' => '<h1>Application Submission &amp; Triage Workflow</h1>
<h2>PostgreSQL Implementation Guide for ARCHR Platform</h2>
<h3>Document Purpose</h3>
<p>This document defines the complete submission-to-triage pipeline for home repair applications, including:</p>
<ul>
<li>Optional requestor account creation</li>
<li>Real-time notifications for staff</li>
<li>FIFO (First-In-First-Out) review queue</li>
<li>"Accept until disqualification" eligibility logic</li>
<li>Anchor registration for all applications (including ineligible)</li>
</ul>
<hr />
<h2>Process Flow Overview</h2>
<pre><code class="language-mermaid">
graph TB
    subgraph "Applicant Journey"
        A[Start Intake Form] --&gt; B[Complete 14 Pages]
        B --&gt; C{Create Account?}
        C --&gt;|Yes| D[Set Password]
        C --&gt;|No| E[Continue as Guest]
        D --&gt; F[Requestor Dashboard Access]
        E --&gt; G[Email-only Updates]
    end

    subgraph "System Processing"
        B --&gt; H[Validate Submission]
        H --&gt; I[Generate Application Record]
        I --&gt; J[ANCHOR: Register Application]
        J --&gt; K[Run Eligibility Checker]
        K --&gt; L{Eligible?}
        L --&gt;|Yes| M[Mark: PENDING_REVIEW]
        L --&gt;|No| N[Mark: INELIGIBLE]
        N --&gt; O[Record Reason Codes]
    end

    subgraph "Staff Notifications"
        M --&gt; P[Trigger: NEW_APPLICATION]
        P --&gt; Q[Push to Review Queue]
        Q --&gt; R[Notify Roles via Dashboard]
        R --&gt; S[Email Digest to Staff]
    end

    subgraph "Review Queue"
        Q --&gt; T[FIFO Order by submitted_at]
        T --&gt; U[Admin View]
        T --&gt; V[Caseworker View]
        T --&gt; W[Project Manager View]
        U --&gt; X[Assign to Organization]
        V --&gt; Y[Initial Triage]
        W --&gt; Z[Resource Planning]
    end

    subgraph "Requestor Experience"
        D --&gt; AA[Login to Dashboard]
        F --&gt; AB[View Status]
        G --&gt; AC[Click Email Link]
        AA --&gt; AD[Upload Documents]
        AB --&gt; AE[See Eligibility Results]
        AD --&gt; AF[Secure Document Storage]
    end</code></pre>',
);
