<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'sync-map-data-flows',
  'title' => 'Sync Map Data Flows — Base-to-Base Diagrams',
  'category' => 'developers',
  'category_name' => 'For Developers',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Sync Map Data Flows — Base-to-Base Diagrams',
    'document_type' => 'Technical Reference',
    'version' => '1.0',
    'last_updated' => '2026-08-01',
    'author' => 'ARCHR Development Team',
    'audience' => 'Developers, Admins',
    'complexity_level' => 'Advanced',
    'estimated_reading_minutes' => '20',
    'tags' => 
    array (
      0 => 'data-flow',
      1 => 'sync',
      2 => 'airtable',
      3 => 'architecture',
    ),
    'visibility' => 
    array (
      0 => 'admin',
      1 => 'super-admin',
    ),
  ),
  'source' => 'developers\\sync-map-data-flows.md',
  'html' => '<h1>Sync Map Data Flows</h1>
<p>Source: <code>C:\\Users\\bwyatt\\Downloads\\🔷Tables-Sync Map.csv</code></p>
<p>This document translates the Sync Map table into base-level data-flow diagrams. Counts represent the number of sync-map rows/tables connecting two bases, not record volume.</p>
<h2>How to Read This</h2>
<ul>
<li><strong>Inbound</strong> means this base has local tables populated from another base through a synced table relationship.</li>
<li><strong>Outbound</strong> means this base has source tables that feed synced tables in another base.</li>
<li><strong>Automation surface</strong> counts local tables where the CSV shows automation triggers, reads, or writes.</li>
<li><strong>Linked record surface</strong> counts local tables where the CSV shows linked-record paths.</li>
</ul>
<h2>System Overview</h2>
<pre><code class="language-mermaid">flowchart LR
  fillout["🟦(📗) Fillout Results"]
  anchor["🟦[D](v1-2) ANCHOR Records"]
  directory["🟦[D] (v2) ARCHR Directory"]
  documents["🟦[D] ARCHR Project Documents"]
  repairs["🟦[D] ARCHR Repair Requests"]
  eligibility["🟦[P] ARCHR Eligibility"]
  progress["🟦[P] ARCHR Progress Tracker"]
  partners["🟦ARCHR Partner Programs"]
  model["🟦[X] ARCHR Architecture Model"]
  emergency["🟦[A] (v1) ARCHR Emergency"]
  tasks["🟦[D] ARCHR Multi Axis Task Library"]

  model --&gt;|"forms, phases, roles, interfaces"| fillout
  model --&gt;|"architecture refs"| directory
  model --&gt;|"task/phase refs"| progress

  fillout --&gt;|"intake submissions"| eligibility
  fillout --&gt;|"request intake"| repairs
  fillout --&gt;|"anchor intake"| anchor
  fillout --&gt;|"directory sync"| directory

  anchor --&gt;|"anchor/project/place syncs"| progress
  anchor --&gt;|"project docs + anchor records"| documents
  anchor --&gt;|"eligibility anchors"| eligibility
  anchor --&gt;|"fillout backlinks"| fillout
  anchor --&gt;|"repair anchors"| repairs

  directory --&gt;|"people/org/session/project syncs"| progress
  directory --&gt;|"people/org docs"| documents
  directory --&gt;|"eligibility people/orgs"| eligibility
  directory --&gt;|"partner orgs"| partners
  directory --&gt;|"repair directory refs"| repairs

  documents --&gt;|"doc events/doc codes"| progress
  documents --&gt;|"program/doc syncs"| partners

  eligibility --&gt;|"eligibility docs/reports"| documents
  eligibility --&gt;|"fillout result feedback"| fillout
  eligibility --&gt;|"program eligibility"| partners
  eligibility --&gt;|"eligibility event sync"| progress

  progress --&gt;|"task/project/session events"| directory
  progress --&gt;|"repair progress events"| repairs
  progress --&gt;|"anchor progress events"| anchor
  progress --&gt;|"doc progress events"| documents

  emergency --&gt;|"v1 tasks/jobs/events"| tasks
  emergency --&gt;|"v1 events/status"| progress
  emergency --&gt;|"jobs/docs"| documents
  emergency --&gt;|"legacy anchor + fillout"| anchor
  emergency --&gt;|"funding requests"| fillout</code></pre>
<h2>Per-Base Diagrams</h2>
<h3>🟦(📗) Fillout Results</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦(📗) Fillout Results"]
  anchor["🟦[D](v1-2) ANCHOR Records"] --&gt;|"2 inbound sync tables"| base
  repairs["🟦[D] ARCHR Repair Requests"] --&gt;|"2 inbound sync tables"| base
  emergency["🟦[A] (v1) ARCHR Emergency"] --&gt;|"1 inbound sync table"| base
  partners["🟦ARCHR Partner Programs"] --&gt;|"1 inbound sync table"| base
  model["🟦[X] ARCHR Architecture Model"] --&gt;|"1 inbound sync table"| base
  eligibility["🟦[P] ARCHR Eligibility"] --&gt;|"1 inbound sync table"| base
  base --&gt;|"2 outbound sync tables"| repairs
  base --&gt;|"2 outbound sync tables"| anchor
  base --&gt;|"2 outbound sync tables"| eligibility
  base --&gt;|"1 outbound sync table"| directory["🟦[D] (v2) ARCHR Directory"]</code></pre>
<p>Fillout is the intake and raw-submission hub. It receives reference/sync data from model, eligibility, partner, anchor, repair, and emergency bases, then pushes cleaned intake/request/submission tables into eligibility, repair requests, ANCHOR, and directory flows.</p>
<ul>
<li>Tables mapped: 12</li>
<li>Automation surface: 5 trigger tables, 5 write tables, 5 read tables</li>
<li>Linked record surface: 12 tables</li>
</ul>
<h3>🟦[A] (v1) ARCHR Emergency</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[A] (v1) ARCHR Emergency"]
  base --&gt;|"3 outbound sync tables"| tasks["🟦[D] ARCHR Multi Axis Task Library"]
  base --&gt;|"2 outbound sync tables"| progress["🟦[P] ARCHR Progress Tracker"]
  base --&gt;|"1 outbound sync table"| fillout["🟦(📗) Fillout Results"]
  base --&gt;|"1 outbound sync table"| anchor["🟦[D](v1-2) ANCHOR Records"]
  base --&gt;|"1 outbound sync table"| docs["🟦[D] ARCHR Project Documents"]</code></pre>
<p>The v1 emergency base acts mainly as a source into shared systems: task library, progress events, documents, ANCHOR, and Fillout-derived request flows.</p>
<ul>
<li>Tables mapped: 6</li>
<li>Automation surface: none shown in this CSV</li>
<li>Linked record surface: none shown in this CSV</li>
</ul>
<h3>🟦[A] (v2) ARCHR Applicants</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[A] (v2) ARCHR Applicants"]
  base --&gt;|"2 outbound sync tables"| docs["🟦[D] ARCHR Project Documents"]</code></pre>
<p>The v2 applicants base feeds applicant home and FEMA/HOI/attestation data into the project document system.</p>
<ul>
<li>Tables mapped: 2</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦[D] (v1) ARCHR Disaster Funding Sources</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[D] (v1) ARCHR Disaster Funding Sources"]
  base --&gt;|"1 outbound sync table"| anchor["🟦[D](v1-2) ANCHOR Records"]</code></pre>
<p>The disaster funding source base contributes draw request data into ANCHOR records.</p>
<ul>
<li>Tables mapped: 1</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦[D] (v2) AAHH Traditional Home Repair</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[D] (v2) AAHH Traditional Home Repair"]
  base --&gt;|"1 outbound sync table"| anchor["🟦[D](v1-2) ANCHOR Records"]</code></pre>
<p>The AAHH traditional home repair base contributes CS/NRI data into ANCHOR records.</p>
<ul>
<li>Tables mapped: 1</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦[D] (v2) ARCHR Directory</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[D] (v2) ARCHR Directory"]
  progress["🟦[P] ARCHR Progress Tracker"] --&gt;|"4 inbound sync tables"| base
  model["🟦[X] ARCHR Architecture Model"] --&gt;|"3 inbound sync tables"| base
  fillout["🟦(📗) Fillout Results"] --&gt;|"1 inbound sync table"| base
  email["🟦[P] ARCHR Email Handler"] --&gt;|"1 inbound sync table"| base
  base --&gt;|"3 outbound sync tables"| progress
  base --&gt;|"2 outbound sync tables"| docs["🟦[D] ARCHR Project Documents"]
  base --&gt;|"2 outbound sync tables"| eligibility["🟦[P] ARCHR Eligibility"]
  base --&gt;|"1 outbound sync table"| partners["🟦ARCHR Partner Programs"]
  base --&gt;|"1 outbound sync table"| repairs["🟦[D] ARCHR Repair Requests"]</code></pre>
<p>Directory is the people/org/session/project coordination layer. It receives architecture definitions and progress events, then republishes people, organizations, projects, sessions, and eligibility/reporting joins across the operational bases.</p>
<ul>
<li>Tables mapped: 12</li>
<li>Automation surface: 6 trigger tables, 6 write tables, 4 read tables</li>
<li>Linked record surface: 11 tables</li>
</ul>
<h3>🟦[D] ARCHR Multi Axis Task Library</h3>
<pre><code class="language-mermaid">flowchart LR
  emergency["🟦[A] (v1) ARCHR Emergency"] --&gt;|"3 inbound sync tables"| base["🟦[D] ARCHR Multi Axis Task Library"]
  subcontractors["🟦[P] Subcontractor Log"] --&gt;|"1 inbound sync table"| base</code></pre>
<p>The task library receives v1 task/job/library data and subcontractor task data. In this CSV it appears as a sink rather than a source.</p>
<ul>
<li>Tables mapped: 4</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: 4 tables</li>
</ul>
<h3>🟦[D] ARCHR Project Documents</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[D] ARCHR Project Documents"]
  eligibility["🟦[P] ARCHR Eligibility"] --&gt;|"3 inbound sync tables"| base
  directory["🟦[D] (v2) ARCHR Directory"] --&gt;|"2 inbound sync tables"| base
  anchor["🟦[D](v1-2) ANCHOR Records"] --&gt;|"2 inbound sync tables"| base
  applicants["🟦[A] (v2) ARCHR Applicants"] --&gt;|"2 inbound sync tables"| base
  progress["🟦[P] ARCHR Progress Tracker"] --&gt;|"2 inbound sync tables"| base
  emergency["🟦[A] (v1) ARCHR Emergency"] --&gt;|"1 inbound sync table"| base
  subcontractors["🟦[P] Subcontractor Log"] --&gt;|"1 inbound sync table"| base
  email["🟦[P] ARCHR Email Handler"] --&gt;|"1 inbound sync table"| base
  partners["🟦ARCHR Partner Programs"] --&gt;|"1 inbound sync table"| base
  base --&gt;|"3 outbound sync tables"| progress
  base --&gt;|"2 outbound sync tables"| partners</code></pre>
<p>Project Documents is the document/document-event hub. It receives applicant, eligibility, anchor, directory, email, subcontractor, emergency, partner, and progress context, then pushes document events and document-code/program data back to Progress Tracker and Partner Programs.</p>
<ul>
<li>Tables mapped: 19</li>
<li>Automation surface: 7 trigger tables, 7 write tables, 6 read tables</li>
<li>Linked record surface: 16 tables</li>
</ul>
<h3>🟦[D] ARCHR Repair Requests</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[D] ARCHR Repair Requests"]
  progress["🟦[P] ARCHR Progress Tracker"] --&gt;|"3 inbound sync tables"| base
  fillout["🟦(📗) Fillout Results"] --&gt;|"2 inbound sync tables"| base
  anchor["🟦[D](v1-2) ANCHOR Records"] --&gt;|"1 inbound sync table"| base
  directory["🟦[D] (v2) ARCHR Directory"] --&gt;|"1 inbound sync table"| base
  marketplace["🟦[P] ARCHR Marketplace"] --&gt;|"1 inbound sync table"| base
  base --&gt;|"2 outbound sync tables"| fillout</code></pre>
<p>Repair Requests consolidates request intake, marketplace events, anchor links, directory context, and progress status. It also sends repair/request tables back toward Fillout.</p>
<ul>
<li>Tables mapped: 10</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: 7 tables</li>
</ul>
<h3>🟦[D] ARCHR Reports</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[D] ARCHR Reports"]
  base --&gt;|"1 outbound sync table"| progress["🟦[P] ARCHR Progress Tracker"]</code></pre>
<p>Reports contributes financial/reporting progress data into Progress Tracker.</p>
<ul>
<li>Tables mapped: 1</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦[D] DSW Updates Sheet</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[D] DSW Updates Sheet"]
  base --&gt;|"1 outbound sync table"| anchor["🟦[D](v1-2) ANCHOR Records"]
  base --&gt;|"1 outbound sync table"| progress["🟦[P] ARCHR Progress Tracker"]</code></pre>
<p>DSW updates are shared into both ANCHOR and Progress Tracker.</p>
<ul>
<li>Tables mapped: 2</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦<a href="v1-2">D</a> ANCHOR Records</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[D](v1-2) ANCHOR Records"]
  progress["🟦[P] ARCHR Progress Tracker"] --&gt;|"2 inbound sync tables"| base
  fillout["🟦(📗) Fillout Results"] --&gt;|"2 inbound sync tables"| base
  emergency["🟦[A] (v1) ARCHR Emergency"] --&gt;|"1 inbound sync table"| base
  partners["🟦ARCHR Partner Programs"] --&gt;|"1 inbound sync table"| base
  funding["🟦[D] (v1) ARCHR Disaster Funding Sources"] --&gt;|"1 inbound sync table"| base
  dsw["🟦[D] DSW Updates Sheet"] --&gt;|"1 inbound sync table"| base
  aahh["🟦[D] (v2) AAHH Traditional Home Repair"] --&gt;|"1 inbound sync table"| base
  base --&gt;|"3 outbound sync tables"| progress
  base --&gt;|"2 outbound sync tables"| eligibility["🟦[P] ARCHR Eligibility"]
  base --&gt;|"2 outbound sync tables"| docs["🟦[D] ARCHR Project Documents"]
  base --&gt;|"2 outbound sync tables"| fillout
  base --&gt;|"1 outbound sync table"| repairs["🟦[D] ARCHR Repair Requests"]</code></pre>
<p>ANCHOR is a central record spine for projects, places, dates, DSW updates, draw requests, and anchor/project backlinks. It both receives project context and republishes anchor-level relationships to Progress Tracker, Documents, Eligibility, Fillout, and Repair Requests.</p>
<ul>
<li>Tables mapped: 12</li>
<li>Automation surface: 7 trigger tables, 6 write tables, 7 read tables</li>
<li>Linked record surface: 12 tables</li>
</ul>
<h3>🟦[P] ARCHR Eligibility</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[P] ARCHR Eligibility"]
  directory["🟦[D] (v2) ARCHR Directory"] --&gt;|"2 inbound sync tables"| base
  fillout["🟦(📗) Fillout Results"] --&gt;|"2 inbound sync tables"| base
  partners["🟦ARCHR Partner Programs"] --&gt;|"2 inbound sync tables"| base
  anchor["🟦[D](v1-2) ANCHOR Records"] --&gt;|"2 inbound sync tables"| base
  base --&gt;|"3 outbound sync tables"| docs["🟦[D] ARCHR Project Documents"]
  base --&gt;|"1 outbound sync table"| fillout
  base --&gt;|"1 outbound sync table"| partners
  base --&gt;|"1 outbound sync table"| progress["🟦[P] ARCHR Progress Tracker"]</code></pre>
<p>Eligibility sits between intake, programs, directory identity, ANCHOR records, reports, and project documents. It pushes eligibility/report/document context to Project Documents and Progress Tracker while also maintaining partner and Fillout feedback loops.</p>
<ul>
<li>Tables mapped: 10</li>
<li>Automation surface: 3 trigger tables, 5 write tables, 3 read tables</li>
<li>Linked record surface: 9 tables</li>
</ul>
<h3>🟦[P] ARCHR Email Handler</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[P] ARCHR Email Handler"]
  base --&gt;|"1 outbound sync table"| directory["🟦[D] (v2) ARCHR Directory"]
  base --&gt;|"1 outbound sync table"| docs["🟦[D] ARCHR Project Documents"]</code></pre>
<p>Email Handler sends received-message and alert-log data into Directory and Project Documents.</p>
<ul>
<li>Tables mapped: 2</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦[P] ARCHR Marketplace</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[P] ARCHR Marketplace"]
  base --&gt;|"1 outbound sync table"| repairs["🟦[D] ARCHR Repair Requests"]</code></pre>
<p>Marketplace events feed Repair Requests.</p>
<ul>
<li>Tables mapped: 1</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦[P] ARCHR Progress Tracker</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[P] ARCHR Progress Tracker"]
  docs["🟦[D] ARCHR Project Documents"] --&gt;|"3 inbound sync tables"| base
  directory["🟦[D] (v2) ARCHR Directory"] --&gt;|"3 inbound sync tables"| base
  anchor["🟦[D](v1-2) ANCHOR Records"] --&gt;|"3 inbound sync tables"| base
  emergency["🟦[A] (v1) ARCHR Emergency"] --&gt;|"2 inbound sync tables"| base
  model["🟦[X] ARCHR Architecture Model"] --&gt;|"2 inbound sync tables"| base
  assessments["🟦[R] ARCHR Assessments"] --&gt;|"1 inbound sync table"| base
  partners["🟦ARCHR Partner Programs"] --&gt;|"1 inbound sync table"| base
  eligibility["🟦[P] ARCHR Eligibility"] --&gt;|"1 inbound sync table"| base
  dsw["🟦[D] DSW Updates Sheet"] --&gt;|"1 inbound sync table"| base
  reports["🟦[D] ARCHR Reports"] --&gt;|"1 inbound sync table"| base
  base --&gt;|"4 outbound sync tables"| directory
  base --&gt;|"3 outbound sync tables"| repairs["🟦[D] ARCHR Repair Requests"]
  base --&gt;|"2 outbound sync tables"| anchor
  base --&gt;|"2 outbound sync tables"| docs</code></pre>
<p>Progress Tracker is the cross-system event and task state hub. It receives events from documents, directory, ANCHOR, emergency, model, assessments, eligibility, DSW, reports, and partner programs, then republishes task/project/session/anchor/document progress state back to Directory, Repair Requests, ANCHOR, and Project Documents.</p>
<ul>
<li>Tables mapped: 19</li>
<li>Automation surface: 13 trigger tables, 3 write tables, 14 read tables</li>
<li>Linked record surface: 19 tables</li>
</ul>
<h3>🟦[P] Subcontractor Log</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[P] Subcontractor Log"]
  base --&gt;|"1 outbound sync table"| tasks["🟦[D] ARCHR Multi Axis Task Library"]
  base --&gt;|"1 outbound sync table"| docs["🟦[D] ARCHR Project Documents"]</code></pre>
<p>Subcontractor jobs/tasks feed the task library and project document system.</p>
<ul>
<li>Tables mapped: 2</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦[R] ARCHR Assessments</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[R] ARCHR Assessments"]
  base --&gt;|"1 outbound sync table"| progress["🟦[P] ARCHR Progress Tracker"]</code></pre>
<p>Assessment reports feed Progress Tracker.</p>
<ul>
<li>Tables mapped: 1</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦[X] ARCHR Architecture Model</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦[X] ARCHR Architecture Model"]
  base --&gt;|"3 outbound sync tables"| directory["🟦[D] (v2) ARCHR Directory"]
  base --&gt;|"2 outbound sync tables"| progress["🟦[P] ARCHR Progress Tracker"]
  base --&gt;|"1 outbound sync table"| fillout["🟦(📗) Fillout Results"]</code></pre>
<p>Architecture Model publishes definitions for progress tasks, roles, phases, interfaces, and Fillout forms into the runtime bases.</p>
<ul>
<li>Tables mapped: 5</li>
<li>Automation surface: none shown</li>
<li>Linked record surface: none shown</li>
</ul>
<h3>🟦ARCHR Partner Programs</h3>
<pre><code class="language-mermaid">flowchart LR
  base["🟦ARCHR Partner Programs"]
  docs["🟦[D] ARCHR Project Documents"] --&gt;|"2 inbound sync tables"| base
  directory["🟦[D] (v2) ARCHR Directory"] --&gt;|"1 inbound sync table"| base
  eligibility["🟦[P] ARCHR Eligibility"] --&gt;|"1 inbound sync table"| base
  base --&gt;|"2 outbound sync tables"| eligibility
  base --&gt;|"1 outbound sync table"| anchor["🟦[D](v1-2) ANCHOR Records"]
  base --&gt;|"1 outbound sync table"| fillout["🟦(📗) Fillout Results"]
  base --&gt;|"1 outbound sync table"| docs
  base --&gt;|"1 outbound sync table"| progress["🟦[P] ARCHR Progress Tracker"]</code></pre>
<p>Partner Programs is a program/organization reference base with loops into Eligibility, ANCHOR, Fillout, Documents, and Progress Tracker.</p>
<ul>
<li>Tables mapped: 6</li>
<li>Automation surface: none shown in this CSV</li>
<li>Linked record surface: 5 tables</li>
</ul>
<h2>High-Level Roles</h2>
<ul>
<li><strong>Reference/config publishers:</strong> Architecture Model, Partner Programs, Multi Axis Task Library.</li>
<li><strong>Intake and source capture:</strong> Fillout Results, Email Handler, Marketplace, Applicant bases, DSW Updates, Assessments.</li>
<li><strong>Operational record hubs:</strong> Directory, ANCHOR Records, Repair Requests, Eligibility.</li>
<li><strong>Document hub:</strong> Project Documents.</li>
<li><strong>Event/task hub:</strong> Progress Tracker.</li>
</ul>
<h2>Notes and Caveats</h2>
<ul>
<li>The Sync Map CSV describes discovered table-level relationships. It does not prove direction of individual field formulas or automation side effects beyond the explicit sync parent/child and automation read/write columns.</li>
<li>Some bases are both upstream and downstream of each other. Those are intentional feedback loops, especially around Fillout, ANCHOR, Eligibility, Project Documents, and Progress Tracker.</li>
<li>Automation counts are local table counts with automation metadata, not automation step counts.</li>
</ul>',
);
