<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'system-anatomy',
  'title' => 'Anatomy of a Home Repair Platform',
  'category' => 'developers',
  'category_name' => 'For Developers',
  'visibility' => 'roles',
  'roles' => 
  array (
    0 => 'admin',
    1 => 'super-admin',
  ),
  'meta' => 
  array (
    'document_name' => 'Anatomy of a Home Repair Platform',
    'document_type' => 'Technical Overview',
    'version' => '1.0',
    'last_updated' => '2026-07-10',
    'author' => 'ARCHR Development Team',
    'audience' => 'Developers, System Administrators, Technical Leads',
    'complexity_level' => 'Advanced',
    'estimated_reading_minutes' => '8-10 minutes',
    'tags' => 
    array (
      0 => 'architecture',
      1 => 'systems',
      2 => 'data-flow',
      3 => 'integration',
      4 => 'database',
    ),
  ),
  'source' => 'developers\\system-anatomy.md',
  'html' => '<h3>Outline</h3>
<p><strong>1. The Big Picture - System Architecture</strong></p>
<p>text</p>
<p>┌─────────────────────────────────────────────────────────────────────────────────┐
│  Frontend Layer         │  Business Logic Layer  │  Data Layer                 │
│  ┌─────────────────────┐│  ┌────────────────────┐│  ┌──────────────────────┐   │
│  │ Softr (UI)          ││  │ Task Engine        ││  │ PostgreSQL Database  │   │
│  │ Custom HTML/CSS/JS  ││  │ Progress Tracker   ││  │ - Schema: 40+ tables │   │
│  │ Mobile-First Design ││  │ Eligibility Engine ││  │ - Immutable Ledger   │   │
│  └─────────────────────┘│  │ Document Generator ││  │ - Row-Level Security │   │
│                         │  │ Notification System││  │ - Full-Text Search   │   │
│                         │  │ Reporting Engine   ││  └──────────────────────┘   │
│                         │  └────────────────────┘│                             │
│                         │                        │  ┌──────────────────────┐   │
│                         │  ┌────────────────────┐│  │ Document Bucket     │   │
│                         │  │ Fillout Forms      ││  │ - Dropbox/Z-Drive   │   │
│                         │  │ - Intake           ││  │ - Encrypted Storage │   │
│                         │  │ - Quick Add        ││  │ - Standardized      │   │
│                         │  │ - Task Approval    ││  │   Folder Structure  │   │
│                         │  └────────────────────┘│  └──────────────────────┘   │
└─────────────────────────────────────────────────────────────────────────────────┘</p>
<p><strong>2. The Core Systems</strong></p>
<table>
<thead>
<tr>
<th>System</th>
<th>Purpose</th>
<th>Key Tables/Components</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>User &amp; Role Management</strong></td>
<td>Authentication, authorization, permissions</td>
<td><code>system_users</code>, <code>roles</code>, <code>user_role_assignments</code></td>
</tr>
<tr>
<td><strong>Application Intake</strong></td>
<td>Capture applicant information</td>
<td><code>intake_submissions</code>, <code>submission_*</code> tables</td>
</tr>
<tr>
<td><strong>Case Management</strong></td>
<td>Track case lifecycle</td>
<td><code>cases</code>, <code>case_statuses</code>, <code>case_status_history</code></td>
</tr>
<tr>
<td><strong>Progress Tracker</strong></td>
<td>Immutable task log</td>
<td><code>progress_ledger</code>, views</td>
</tr>
<tr>
<td><strong>Task Engine</strong></td>
<td>Create, assign, complete tasks</td>
<td><code>task_definitions</code>, <code>tasks</code></td>
</tr>
<tr>
<td><strong>Document Management</strong></td>
<td>Generate, store, organize docs</td>
<td><code>case_documents</code>, <code>document_templates</code></td>
</tr>
<tr>
<td><strong>Financial Tracking</strong></td>
<td>Track funding, invoices, reimbursements</td>
<td><code>case_funding</code>, <code>invoices</code>, <code>reimbursement_requests</code></td>
</tr>
<tr>
<td><strong>Assessment</strong></td>
<td>Property inspections, estimates</td>
<td><code>property_assessments</code>, <code>repair_estimates</code></td>
</tr>
<tr>
<td><strong>Work Orders</strong></td>
<td>Repair project management</td>
<td><code>work_orders</code>, <code>work_tasks</code></td>
</tr>
<tr>
<td><strong>Scheduling</strong></td>
<td>Calendar, appointments</td>
<td><code>scheduled_events</code>, <code>availability</code></td>
</tr>
<tr>
<td><strong>Communications</strong></td>
<td>Messages, logs</td>
<td><code>case_communications</code>, <code>communications_log</code></td>
</tr>
</tbody>
</table>
<p><strong>3. The Immutable Ledger (Progress Tracker)</strong></p>
<ul>
<li>
<p>Single source of truth for all case activity</p>
</li>
<li>
<p>Every change is a new row (never overwritten)</p>
</li>
<li>
<p>Complete audit trail</p>
</li>
<li>
<p>Powers task metrics and reporting</p>
</li>
</ul>
<p><strong>4. Data Flow Through the System</strong></p>
<p><strong>Application Submission Flow:</strong></p>
<ol>
<li>
<p>User fills intake form (Fillout)</p>
</li>
<li>
<p>Data stored in <code>intake_submissions</code></p>
</li>
<li>
<p>Eligibility check runs</p>
</li>
<li>
<p>Case created (if eligible)</p>
</li>
<li>
<p>Notification sent to staff</p>
</li>
<li>
<p>Entry added to Progress Ledger</p>
</li>
</ol>
<p><strong>Task Completion Flow:</strong></p>
<ol>
<li>
<p>User clicks "+ Add Event"</p>
</li>
<li>
<p>Form adapts to task type</p>
</li>
<li>
<p>Data submitted to API</p>
</li>
<li>
<p>Document generated (if needed)</p>
</li>
<li>
<p>Progress Ledger updated</p>
</li>
<li>
<p>Task counts updated</p>
</li>
<li>
<p>Metrics recalculated</p>
</li>
</ol>
<p><strong>5. Key Database Tables (40+ Total)</strong></p>
<table>
<thead>
<tr>
<th>Table</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>intake_submissions</code></td>
<td>Raw application data</td>
</tr>
<tr>
<td><code>cases</code></td>
<td>Case records</td>
</tr>
<tr>
<td><code>progress_ledger</code></td>
<td>Immutable task log</td>
</tr>
<tr>
<td><code>case_documents</code></td>
<td>Document metadata</td>
</tr>
<tr>
<td><code>work_orders</code></td>
<td>Repair projects</td>
</tr>
<tr>
<td><code>work_tasks</code></td>
<td>Individual tasks</td>
</tr>
<tr>
<td><code>invoices</code></td>
<td>Financial records</td>
</tr>
<tr>
<td><code>property_assessments</code></td>
<td>Inspection reports</td>
</tr>
<tr>
<td><code>system_users</code></td>
<td>User accounts</td>
</tr>
<tr>
<td><code>roles</code></td>
<td>Role definitions</td>
</tr>
<tr>
<td><code>permissions</code></td>
<td>Access control</td>
</tr>
</tbody>
</table>
<p><strong>6. How Softr Interacts With the Backend</strong></p>
<ul>
<li>
<p>Softr handles UI rendering</p>
</li>
<li>
<p>Custom code (HTML/CSS/JS) for complex components</p>
</li>
<li>
<p>Fillout for forms with dynamic logic</p>
</li>
<li>
<p>API calls to backend for data operations</p>
</li>
<li>
<p>Webhooks for event triggers</p>
</li>
</ul>
<p><strong>7. Security Architecture</strong></p>
<ul>
<li>
<p><strong>Row-Level Security</strong>: Users see only their org\'s data</p>
</li>
<li>
<p><strong>Column-Level Security</strong>: Sensitive fields redacted</p>
</li>
<li>
<p><strong>Encryption</strong>: AES-256 at rest, TLS in transit</p>
</li>
<li>
<p><strong>Audit Log</strong>: Every access and change logged</p>
</li>
<li>
<p><strong>Permissions</strong>: Granular role-based access control</p>
</li>
</ul>',
);
