<?php
// AUTO-GENERATED by app/generate-help-docs.php — do not edit by hand.
return array (
  'slug' => 'volunteer-mgmt',
  'title' => 'Volunteer Management & Hour Tracking SOP',
  'category' => 'sops',
  'category_name' => 'Standard Operating Procedures',
  'visibility' => 'authenticated',
  'roles' => 
  array (
  ),
  'meta' => 
  array (
    'document_name' => 'Volunteer Management & Hour Tracking SOP',
    'document_type' => 'Standard Operating Procedure',
    'version' => '1.0',
    'last_updated' => '2026-09-07',
    'author' => 'ARCHR Development Team',
    'audience' => 'Volunteers, Crew Leads, Admins',
    'complexity_level' => 'Beginner',
    'estimated_reading_minutes' => '6',
    'tags' => 
    array (
      0 => 'volunteers',
      1 => 'hours',
      2 => 'scheduling',
      3 => 'recognition',
      4 => 'SOP',
    ),
    'visibility' => 'authenticated',
  ),
  'source' => 'sops\\volunteer-mgmt.md',
  'html' => '<h1>Volunteer Management &amp; Hour Tracking</h1>
<blockquote>
<p><strong>Who this is for:</strong> Volunteers who want to help, Crew Leads who manage volunteer teams, and Admins who track volunteer contributions.</p>
</blockquote>
<h2>Why It\'s Important</h2>
<p>Volunteers are the lifeblood of disaster recovery. They show up, work hard, and ask for nothing but the satisfaction of helping their neighbors. <strong>Make it easy for them.</strong></p>
<p>Volunteer hours also count as in-kind contributions for grant reporting. Tracked properly, they\'re worth real money to the coalition. Tracked poorly, they\'re invisible — and the coalition loses funding because of it.</p>
<hr />
<h2>Signing Up as a Volunteer</h2>
<h3>For New Volunteers</h3>
<ol>
<li><strong>Complete the volunteer application</strong> — this generates your Level 0 volunteer account</li>
<li><strong>Set your profile</strong> — availability, skills, experience level, any trade preferences</li>
<li><strong>Complete any required training</strong> — safety orientation, platform basics</li>
<li><strong>Get assigned to a Crew Lead</strong> — you\'ll report to someone experienced</li>
</ol>
<blockquote>
<p><strong>Volunteer vs. Crew Member:</strong> Volunteers are unpaid helpers supervised by a Crew Lead. Crew Members are paid staff. The platform treats them differently — volunteers see available tasks to claim; crew members see assigned tasks.</p>
</blockquote>
<h3>Profile Setup</h3>
<p>In your volunteer profile, fill out:</p>
<ul>
<li><strong>General availability</strong> — when can you work? (weekdays, weekends, both)</li>
<li><strong>Skills &amp; experience</strong> — what can you do? (demo, painting, roofing basics, etc.)</li>
<li><strong>Physical limitations</strong> — any restrictions we should know about? (heights, heavy lifting)</li>
<li><strong>Emergency contact</strong> — who do we call if something happens?</li>
<li><strong>Dietary restrictions</strong> — if meals are provided on-site</li>
</ul>
<hr />
<h2>Viewing and Claiming Tasks</h2>
<h3>What You\'ll See</h3>
<p>Your volunteer dashboard shows:</p>
<ul>
<li><strong>Available tasks</strong> — volunteer-friendly tasks that need help</li>
<li><strong>Upcoming projects</strong> — where and when you can show up</li>
<li><strong>Your logged hours</strong> — running total of your contributions</li>
<li><strong>Your certifications</strong> — any training or clearance you\'ve completed</li>
</ul>
<h3>Claiming a Task</h3>
<ol>
<li><strong>Browse available tasks</strong> — filtered to your area and skill level</li>
<li><strong>Click "Claim"</strong> — this reserves a volunteer slot for that task</li>
<li><strong>Show up</strong> — at the scheduled time and location</li>
<li><strong>Check in with the Crew Lead</strong> — they\'ll confirm your assignment</li>
</ol>
<blockquote>
<p><strong>Don\'t claim a task you can\'t complete.</strong> If your plans change, release the slot so someone else can take it.</p>
</blockquote>
<hr />
<h2>Clocking In and Out</h2>
<h3>On-Site Time Tracking</h3>
<p>When you arrive on-site:</p>
<ol>
<li><strong>Open the platform</strong> on your phone or the site tablet</li>
<li><strong>Navigate to your assigned task</strong></li>
<li><strong>Click "Clock In"</strong> — this starts tracking your hours</li>
<li><strong>Work the task</strong> — do what the Crew Lead assigned</li>
<li><strong>Click "Clock Out"</strong> when done — this stops the timer</li>
</ol>
<p><strong>If you forget to clock in:</strong></p>
<ul>
<li>Tell the Crew Lead — they can manually add your hours</li>
<li>Do it the same day — memories fade fast</li>
</ul>
<blockquote>
<p><strong>GPS verification:</strong> Some programs require GPS check-in to confirm you were on-site. This isn\'t about surveillance — it\'s about verifying volunteer hours for grant reporting.</p>
</blockquote>
<hr />
<h2>Logging Hours Worked</h2>
<h3>What Gets Recorded</h3>
<p>Each clock-in session records:</p>
<ul>
<li><strong>Date and time</strong> — when you worked</li>
<li><strong>Duration</strong> — how long you worked</li>
<li><strong>Task worked on</strong> — which repair task</li>
<li><strong>Location</strong> — which property</li>
<li><strong>Crew Lead confirmation</strong> — they verify you were there</li>
</ul>
<h3>Why Accurate Hours Matter</h3>
<table>
<thead>
<tr>
<th>Reason</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>Grant reporting</strong></td>
<td>Funders count volunteer hours as in-kind contributions</td>
</tr>
<tr>
<td><strong>Volunteer recognition</strong></td>
<td>Milestones (50 hrs, 100 hrs, 500 hrs) get certificates</td>
</tr>
<tr>
<td><strong>Project tracking</strong></td>
<td>PMs need to know how much labor went into each task</td>
</tr>
<tr>
<td><strong>Tax documentation</strong></td>
<td>Some programs provide documentation for volunteer tax deductions</td>
</tr>
</tbody>
</table>
<hr />
<h2>Reporting Volunteer Hours (For Crew Leads)</h2>
<h3>End of Day</h3>
<ol>
<li><strong>Review the day\'s volunteers</strong> — who showed up?</li>
<li><strong>Verify logged hours</strong> — do the clock-in/out times look right?</li>
<li><strong>Add any manual entries</strong> — volunteers who forgot to clock in</li>
<li><strong>Submit the daily report</strong> — this logs all hours for the day</li>
</ol>
<h3>End of Week</h3>
<ol>
<li><strong>Review the week\'s totals</strong> — any anomalies?</li>
<li><strong>Recognize top contributors</strong> — a shout-out goes a long way</li>
<li><strong>Plan next week\'s volunteer needs</strong> — what tasks need more hands?</li>
</ol>
<hr />
<h2>Volunteer Recognition &amp; Certification</h2>
<h3>Milestones</h3>
<p>The platform tracks volunteer hours and recognizes milestones:</p>
<table>
<thead>
<tr>
<th>Milestone</th>
<th>Recognition</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>10 hours</strong></td>
<td>Thank-you email</td>
</tr>
<tr>
<td><strong>50 hours</strong></td>
<td>Certificate of appreciation</td>
</tr>
<tr>
<td><strong>100 hours</strong></td>
<td>Recognition at coalition meeting</td>
</tr>
<tr>
<td><strong>500 hours</strong></td>
<td>Special recognition event</td>
</tr>
</tbody>
</table>
<h3>Converting from Volunteer to Crew Member</h3>
<p>Sometimes a volunteer wants to become paid staff:</p>
<ol>
<li><strong>Express interest</strong> — tell your Crew Lead or Admin</li>
<li><strong>Complete the staff application</strong> — separate from volunteer application</li>
<li><strong>Your volunteer history follows you</strong> — all your logged hours stay on your record</li>
<li><strong>Your role changes</strong> — from Level 0 volunteer to Level 1 or 2 staff</li>
</ol>
<hr />
<h2>Safety Rules for Volunteers</h2>
<p><strong>Volunteers should NEVER:</strong></p>
<ul>
<li>Work at heights without proper fall protection</li>
<li>Handle hazardous materials (asbestos, lead paint, mold)</li>
<li>Perform licensed work (electrical, plumbing, gas)</li>
<li>Operate heavy machinery</li>
<li>Work alone on-site</li>
</ul>
<p><strong>Always:</strong></p>
<ul>
<li>Follow Crew Lead instructions</li>
<li>Wear provided safety gear</li>
<li>Stay in your assigned area</li>
<li>Ask if you\'re unsure about something</li>
<li>Report any injuries immediately</li>
</ul>
<hr />
<h2>Quick Reference</h2>
<table>
<thead>
<tr>
<th>Action</th>
<th>Where</th>
<th>Who</th>
</tr>
</thead>
<tbody>
<tr>
<td>Set availability</td>
<td>Profile → "My Availability"</td>
<td>Volunteer</td>
</tr>
<tr>
<td>Browse tasks</td>
<td>Volunteer dashboard → "Available Tasks"</td>
<td>Volunteer</td>
</tr>
<tr>
<td>Claim a task</td>
<td>Task detail → "Claim"</td>
<td>Volunteer</td>
</tr>
<tr>
<td>Clock in/out</td>
<td>Task detail → "Clock In/Out"</td>
<td>Volunteer</td>
</tr>
<tr>
<td>Verify hours</td>
<td>Task detail → Crew Lead view</td>
<td>Crew Lead</td>
</tr>
<tr>
<td>Add manual hours</td>
<td>Task detail → "Add Hours"</td>
<td>Crew Lead</td>
</tr>
<tr>
<td>View volunteer report</td>
<td>Reports → Volunteer Hours</td>
<td>Admin, Bursar</td>
</tr>
<tr>
<td>Assign volunteers</td>
<td>Project detail → "Assign Volunteers"</td>
<td>Crew Lead</td>
</tr>
</tbody>
</table>
<hr />
<p><strong>Remember:</strong> Every volunteer hour is a gift. Log it well, recognize it generously, and never take it for granted.</p>',
);
